example/lib/example_editor.dart
example/lib/main.dart
example/macos/Runner/MainFlutterWindow.swift

Configured example app window size + hidden window toolbar.

Configured example app window size + hidden window toolbar.

---

example/lib/example_editor.dart

#4 #5: Example editor title and content entry
**Merge #3 before merging this.**

#4 #5 example editor title and content entry

---

.run/Spike_ Tap Selection.run.xml
README.md
example/lib/spikes/selection/_multi_tap_gesture.dart
example/lib/spikes/selection/_single_selectable_paragraph.dart
example/lib/spikes/selection/_triple_tap_gesture.dart
example/lib/spikes/selection/tap_selection_spike.dart

Spike: non-editable text selection.

Spike: non-editable text selection.

---

example/lib/spikes/copy_paste/spike_copy_paste.dart

Spike: copy and paste plain text.

Spike: copy and paste plain text.

---

.run/Spike_ Inline Spans.run.xml
example/lib/spikes/inline/inline_spans.dart

`EditableText` and therefore `TextField` does not support `WidgetSpan` on any platform.
Tested WidgetSpan on Web and works.
#36

Spike inline editing emoji

---

example/lib/demo_selectable_text.dart
example/lib/main.dart
example/macos/Flutter/GeneratedPluginRegistrant.swift
example/pubspec.lock
example/pubspec.yaml
lib/flutter_richtext.dart
lib/src/infrastructure/selectable_text.dart
pubspec.lock
pubspec.yaml

Added `SelectableText` widget to the package.
As part of this PR, the following changes were made:
- Configured the package to be non-null by default (NNBD)
- Copied and improved the `SelectableText` widget from the abstractions spike
- Refactored the demo entrypoint to support a menu of demos that we can expand moving forward
- Created a demo of `SelectableText` that demonstrates a variety of visual configurations

Added SelectableText widget to the package.

---

example/lib/example_editor.dart
example/lib/sliver_example_editor.dart
lib/src/default_editor/document_interaction.dart
lib/src/default_editor/editor.dart

Fixed focus bug and publicly exposed a FocusNode in Editor widget (#72)

Fixed focus bug and publicly exposed a FocusNode in Editor widget (#72)

---

CONTRIBUTING.md
README.md

Drafted README.md and CONTRIBUTING.md

Drafted README.md and CONTRIBUTING.md

---

lib/src/default_editor/document_interaction.dart
lib/src/default_editor/editor.dart

Changed Editor param from EdgeInsets to EdgeInsetsGeometry, fixed unhandled key error sound on desktop. (#61, #62)

Changed Editor param from EdgeInsets to EdgeInsetsGeometry, fixed unhandled key error sound on desktop. (#61, #62)

---

super_editor/lib/src/default_editor/document_interaction.dart
super_editor/lib/src/infrastructure/attributed_spans.dart
super_editor/test/serialization/markdown_test.dart
super_editor/test/src/infrastructure/attributed_text_test.dart

The mono-repo refactor overwrote changes from #99 and #100 - this commit brings those changes back.

The mono-repo refactor overwrote changes from #99 and #100 - this commit brings those changes back.

---

super_editor/example/lib/demos/demo_document_loses_focus.dart
super_editor/example/lib/demos/demo_switch_document_content.dart
super_editor/example/lib/main.dart
super_editor/lib/src/core/document_layout.dart
super_editor/lib/src/default_editor/editor.dart
super_editor/lib/src/default_editor/layout.dart
super_editor/lib/src/default_editor/list_items.dart
super_editor/lib/src/default_editor/paragraph.dart

Redo fix for #97 and #98 because mono-repo accidentally undid the work.

Redo fix for #97 and #98 because mono-repo accidentally undid the work.

---

super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/infrastructure/attributed_text.dart
super_editor/test/src/infrastructure/attributed_text_test.dart

Adds `ChangeNotifier` to `AttributedText` so that whenever style changes occur within existing text, document listeners are updated.
I think this should address #105 and possibly #107

AttributedText now notifies listeners when it changes. Also propogates up as a Document change.

---

super_editor/example/lib/demos/example_editor.dart
super_editor/lib/src/default_editor/blockquote.dart
super_editor/lib/src/default_editor/document_keyboard_actions.dart
super_editor/lib/src/default_editor/editor.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/super_editor.dart

Adds support for blockquotes, including markdown serialization.

Add blockquote support

---

super_editor/README.md
super_editor/example/l10n.yaml
super_editor/example/lib/demos/example_editor.dart
super_editor/example/lib/l10n/app_en.arb
super_editor/example/lib/l10n/app_es.arb
super_editor/example/lib/main.dart
super_editor/example/pubspec.lock
super_editor/example/pubspec.yaml
super_editor/lib/src/core/document_layout.dart
super_editor/lib/src/default_editor/box_component.dart
super_editor/lib/src/default_editor/editor.dart
super_editor/lib/src/default_editor/layout.dart
super_editor/lib/src/default_editor/list_items.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/default_editor/text_tools.dart
super_editor/lib/src/infrastructure/attributed_text.dart
super_editor/lib/src/infrastructure/selectable_text.dart
super_editor/lib/src/serialization/markdown.dart
super_editor/test/src/infrastructure/attributed_text_test.dart

#132 - fixes web bug that prints control character names when it shouldn't
#148 - added README updates that describe platform support
#142 - created a floating text format bar in the demo app. It's still missing link control and localized hint text.
EDIT - Added a couple more small fixes:
#145 - exception thrown when inserting text at start of styled text blob
#147 - exception thrown when triple tapping after final character in text blob
#143 - deserializing a markdown blockquote produces an extra paragraph node
#42 - localization for the example editor toolbar

Multiple v0.1.0 issues

---

super_editor/analysis_options.yaml
super_editor/example/analysis_options.yaml
super_editor/example/lib/demos/demo_textfield.dart
super_editor/example/lib/demos/supertextfield/_emojis_demo.dart
super_editor/example/lib/demos/supertextfield/_expanding_multi_line_demo.dart
super_editor/example/lib/demos/supertextfield/_interactive_demo.dart
super_editor/example/lib/demos/supertextfield/_robot.dart
super_editor/example/lib/demos/supertextfield/_single_line_demo.dart
super_editor/example/lib/demos/supertextfield/_static_multi_line_demo.dart
super_editor/example/lib/demos/supertextfield/_textfield_demo_screen.dart
super_editor/example/lib/demos/supertextfield/demo_textfield.dart
super_editor/example/lib/main.dart
super_editor/lib/src/core/document_layout.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/default_editor/text_tools.dart
super_editor/lib/src/infrastructure/composable_text.dart
super_editor/lib/src/infrastructure/selectable_text.dart
super_editor/lib/src/infrastructure/super_textfield.dart
super_editor/lib/src/infrastructure/text_layout.dart
super_editor/lib/super_editor.dart
super_editor/test/src/_text_entry_test_tools.dart
super_editor/test/src/default_editor/document_keyboard_actions_test.dart
super_editor/test/src/default_editor/text_test.dart
super_editor/test/src/infrastructure/super_textfield_test.dart

This PR introduces a custom implementation for a text field that's called `SuperTextField`.
This work is initially intended to help Turtle. After it meets Turtle's needs then it will be maintained for general consumption.
This PR adds a demo screen to the `super_editor` demo app that shows a handful of use-cases for `SuperTextField`.

Introduce a custom text field called SuperTextField

---

.github
.github/workflows/pr_validation.yaml
.gitignore
super_editor/lib/src/default_editor/document_interaction.dart
super_editor/test/src/infrastructure/super_textfield_test.dart

Added GitHub CI workflow for PR validation. (#84)

Added GitHub CI workflow for PR validation. (#84)

---

super_editor/lib/src/default_editor/document_keyboard_actions.dart

Bugfix: changed attributions from Strings to Attributions when setting the composer style preference.

Bugfix: changed attributions from Strings to Attributions when setting the composer style preference.

---

super_editor/lib/src/infrastructure/selectable_text.dart

Bugfix: Don't access debugNeedsLayout in profile or release modes. (#164)

Bugfix: Don't access debugNeedsLayout in profile or release modes. (#164)

---

super_editor/lib/src/infrastructure/super_textfield.dart

Automatically set text selection and show cursor when SuperTextField receives focus. (#173)

Automatically set text selection and show cursor when SuperTextField receives focus. (#173)

---

super_editor/lib/src/infrastructure/super_textfield.dart

Shift + click to expand selection in SuperTextField. (#171)

Shift + click to expand selection in SuperTextField. (#171)

---

super_editor/example/lib/demos/demo_markdown_serialization.dart
super_editor/example/lib/demos/example_editor/_example_document.dart
super_editor/example/lib/demos/sliver_example_editor.dart

Fixes #195.
`imgur.com` provides `*` CORS headers, which resolves the issue.

Resolve example image CORS issue

---

super_editor/lib/src/core/document_selection.dart
super_editor/lib/src/default_editor/blockquote.dart
super_editor/lib/src/default_editor/list_items.dart

204: Fix the selection problem on null safe projects.

---

super_editor/example/README.md

Updated the README for the example app

Updated the README for the example app

---

super_editor/.run/Marketing Video.run.xml
super_editor/.run/Spike_ Inline Spans.run.xml
super_editor/.run/Spike_ Tap Selection.run.xml
super_editor/.run/Spike_ editor input delegation.run.xml
super_editor/pubspec.yaml

- added 'collection' dependency to satisfy pub analysis
- removed spike and marketing video run configurations

Prep for v0.1.0:

---

website/lib/homepage/featured_editor.dart
website/lib/homepage/inside_the_toolbox.dart
website/pubspec.lock

Fixed marketing website build after a couple widget name changes. (#240)

Fixed marketing website build after a couple widget name changes. (#240)

---

super_editor/lib/src/infrastructure/attributed_spans.dart

Closes https://github.com/superlistapp/super_editor/issues/260
| Before                                                                                                                                                                 | After                                                                                                                                                                  |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="1112" alt="Screenshot 2021-06-26 at 23 31 …

Store a copy of attributions provided to AttributedSpans

---

super_editor/lib/src/infrastructure/multi_tap_gesture.dart

Fixes https://github.com/superlistapp/super_editor/issues/279

Only allow primary button pointer in TapSequenceGestureRecognizer

---

super_editor/lib/src/infrastructure/super_selectable_text.dart

Converted cursor blinking from AnimationController to Timer for performance improvement (Resolves #282)
Please see the issue ticket for discussion about why this is necessary for now.

Converted cursor blinking from AnimationController to Timer for performance improvement (Resolves #282)

---

super_editor/lib/src/default_editor/document_keyboard_actions.dart
super_editor/lib/src/default_editor/super_editor.dart

Closes https://github.com/superlistapp/super_editor/issues/219

Cmd + X cuts content

---

super_editor/lib/src/infrastructure/attributed_spans.dart
super_editor/test/src/infrastructure/attributed_spans_test.dart

Closes https://github.com/superlistapp/super_editor/issues/270

AttributedSpans equality check disregards order of attributions

---

super_editor/example/lib/demos/scrolling/demo_task_and_chat.dart
super_editor/example/lib/demos/scrolling/demo_task_and_chat_with_customscrollview.dart
super_editor/example/lib/demos/scrolling/demo_task_and_chat_with_renderobject.dart
super_editor/example/lib/demos/sliver_example_editor.dart
super_editor/example/lib/main.dart
super_editor/lib/src/default_editor/document_interaction.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/infrastructure/_logging.dart

I'm working on figuring out what it will take to make `SuperEditor` work in a `CustomScrollView`.
I separated all keyboard handling from gesture handling.
Within the gesture interactor, I added behavior to check for an ancestor `Scrollable`. If there is an ancestor `Scrollable` then the gesture interactor bases all of its position and auto-scrolling behaviors on the ancestor.
https://user-images.githubusercontent.com/7259036/139408329-e944e718-7299-48c7-ad2f-add597414a88.mov

Making SuperEditor work in a CustomScrollView

---

super_editor/lib/src/default_editor/document_gestures_mouse.dart

Re-implemented shift+click selection based on PR #289 due to project changes since then (Resolves #237)

Re-implemented shift+click selection based on PR #289 due to project changes since then (Resolves #237)

---

super_editor/lib/src/default_editor/horizontal_rule.dart
super_editor/lib/src/default_editor/image.dart
super_editor/lib/src/default_editor/list_items.dart
super_editor/lib/src/default_editor/text.dart
super_editor/test/src/core/document_editor_test.dart
super_editor/test/src/core/document_test.dart
super_editor/test/src/infrastructure/attributed_text_test.dart

Fixed MutableDocument equality by implementing some downstream equality checks that were missing (Resolves #353)

Fixed MutableDocument equality by implementing some downstream equality checks that were missing (Resolves #353)

---

super_editor/example/lib/demos/components/demo_unselectable_hr.dart
super_editor/example/lib/main.dart
super_editor/lib/src/core/document.dart
super_editor/lib/src/core/document_layout.dart
super_editor/lib/src/default_editor/box_component.dart
super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/document_gestures_mouse.dart
super_editor/lib/src/default_editor/multi_node_editing.dart
super_editor/test/src/default_editor/unselectable_component_test.dart

Implemented non-selectable components (Resolves #359)
Includes a test suite that contrasts the behavior between selectable and non-selectable horizontal rules.
https://user-images.githubusercontent.com/7259036/145670217-ff2ee625-43d4-4f8b-b256-cc69fdf916ef.mov

Implemented non-selectable components (Resolves #359)

---

super_editor/lib/src/default_editor/super_editor.dart

Show the caret on desktop/web based on the passed or resolved value of `SuperEditor.gestureMode`.
Fixes #366

[Bugfix] Show caret on desktop/web

---

super_editor/lib/src/default_editor/document_keyboard_actions.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/src/default_editor/text.dart

Don't insert characters when CMD/CNTL pressed (Resolves #405)

Don't insert characters when CMD/CNTL pressed (Resolves #405)

---

super_editor/lib/src/default_editor/document_input_ime.dart

Added list item and HR pattern matching to IME input (Resolves #422)

Added list item and HR pattern matching to IME input (Resolves #422)

---

super_editor/lib/src/default_editor/blockquote.dart
super_editor/lib/src/default_editor/list_items.dart

Update OrderedListItemComponent, UnorderedListItemComponent and BlockquoteComponent to show a selection highlight when empty

---

super_editor/pubspec.yaml
super_selectable_text/pubspec.yaml

Replaced relative deps with GitHub deps.
@miguelcmedeiros can you try this PR and see if it solves the relative dependency issue that you're having?

Replaced relative deps with GitHub deps

---

super_editor/example/pubspec.lock
super_editor/pubspec.yaml

Removed superfluous attributed_text dep in super_editor, because super_text already exports it

Removed superfluous attributed_text dep in super_editor, because super_text already exports it

---

super_editor/example/lib/demos/example_editor/example_editor.dart
super_editor/example/lib/demos/styles/demo_doc_styles.dart
super_editor/example/lib/marketing_video/main_marketing_video.dart
super_editor/lib/src/core/styles.dart
super_editor/lib/src/default_editor/layout_single_column/_styler_shylesheet.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/test/src/default_editor/super_editor_test.dart
super_editor/test/src/default_editor/test_documents.dart
super_editor/test/src/default_editor/unselectable_component_test.dart
super_editor/test/src/default_editor/upstream_downstream_selection_test.dart

Fixed bug where changing stylesheet didn't update SuperEditor rendering, also added a dark mode example to example editor (Resolves #541)
https://user-images.githubusercontent.com/7259036/166181754-8797bf66-1c5d-4cc5-b580-20e3e24fdd2c.mov

Fixed bug where changing stylesheet didn't update SuperEditor rendering

---

super_text/pubspec.yaml

Adjusted super_text pubspec for Pub release

Adjusted super_text pubspec for Pub release

---

super_editor/example/lib/demos/debugging/simple_deltas_input.dart

Fixed an old reference SuperSelectableText that I missed in simple_deltas_input.dart

Fixed an old reference SuperSelectableText that I missed in simple_deltas_input.dart

---

super_editor/example/.metadata
super_editor/lib/src/infrastructure/multi_tap_gesture.dart
super_editor/test/src/infrastructure/multi_tap_gesture_test.dart
super_editor/test_goldens/editor/components/_components_test_utils.dart
super_editor/test_goldens/editor/mobile/mobile_selection_test.dart

This PR is pretty straightforward, there wasn't too much to fix , and the fixes required just refactoring to the new recommended behavior from the deprecated API's

Fix deprecations from flutter 3 (#554)

---

attributed_text/CHANGELOG.md
attributed_text/pubspec.yaml
super_editor/pubspec.yaml

Upgrade super editor attributed text dep

Upgrade super editor attributed text dep

---

super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_user_interaction.dart
super_editor/test/super_textfield/super_textfield_gestures_test.dart

[SuperTextField] - changed mobile tap gesture to only give focus on UP instead of DOWN (Resolves #657)

[SuperTextField] - changed mobile tap gesture to only give focus on UP instead of DOWN (Resolves #657)

---

run_flutter_test_repository_tests

Added a root-level script to run tests from the Flutter test repository
See Flutter's test repo:
https://github.com/flutter/tests

Added a root-level script to run tests from the Flutter test repository

---

super_editor/lib/src/infrastructure/attributed_text_styles.dart

Fixed a typo and removed a TODO. I decided the TODO isn't necessary. (Resolves #78)

Fixed a typo and removed a TODO. I decided the TODO isn't necessary. (Resolves #78)

---

super_editor/lib/src/default_editor/document_keyboard_actions.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/infrastructure/keyboard.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/test/infrastructure/keyboard_blacklist_test.dart
super_editor/test/src/default_editor/document_keyboard_actions_test.dart

Switch web key blacklist from list to algorithm (Resolves #193)

Switch web key blacklist from list to algorithm (Resolves #193)

---

super_editor/test/super_editor/supereditor_keyboard_test.dart

Added SuperEditor tests for typical keyboard caret movements (Resolves #212)

Added SuperEditor tests for typical keyboard caret movements (Resolves #212)

---

attributed_text/CHANGELOG.md
attributed_text/pubspec.yaml
super_editor/pubspec.yaml
super_editor_markdown/CHANGELOG.md
super_editor_markdown/pubspec.yaml
super_text_layout/CHANGELOG.md
super_text_layout/pubspec.yaml

Released attributed_text v0.2.0, super_text_layout v0.1.3

Released attributed_text v0.2.0, super_text_layout v0.1.3

---

super_editor_markdown/lib/src/markdown.dart
super_editor_markdown/test/attributed_text_markdown_test.dart

[super_editor_markdown] - serialization fixes (Resolves #712)
Changed pulled from PR #704

[super_editor_markdown] - serialization fixes (Resolves #712)

---

super_editor/CHANGELOG.md
super_editor/pubspec.yaml
super_editor_markdown/CHANGELOG.md
super_editor_markdown/LICENSE
super_editor_markdown/pubspec.yaml

Release super_editor v0.2.2, super_editor_markdown v0.1.3

Release super_editor v0.2.2, super_editor_markdown v0.1.3

---

flutter_test_registry/flutter_test_repo_test.bat
flutter_test_registry/flutter_test_repo_test.sh

Updated Flutter test registry scripts to exit on failure (Resolves #728)

Updated Flutter test registry scripts to exit on failure (Resolves #728)

---

super_editor/lib/src/default_editor/layout_single_column/_presenter.dart
super_editor/lib/src/default_editor/text.dart
super_editor/test/super_reader/super_reader_stylesheet_test.dart

Added ability to align text with stylesheet rules (Resolves #823)

Added ability to align text with stylesheet rules (Resolves #823)

---

.github/workflows/pr_validation.yaml
super_editor/lib/src/default_editor/document_gestures_touch.dart
super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/lib/src/default_editor/document_scrollable.dart
super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
super_text_layout/example/lib/main.dart

Run CI against Flutter 'master' for super_editor 'main' branch.
This PR includes fixes due to more Flutter breaking changes.

Run CI against Flutter 'master' for super_editor 'main' branch

---

super_editor/dart_test.yaml

Added dart_test.yaml to silence meaningless test warnings about golden tags

Added dart_test.yaml to silence meaningless test warnings about golden tags

---

super_editor/example/lib/demos/example_editor/example_editor.dart
super_editor/example/lib/demos/supertextfield/_interactive_demo.dart
super_editor/example/pubspec.lock
super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/infrastructure/fill_width_if_constrained.dart
super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/test/super_editor/supereditor_popover_focus_test.dart
super_text_layout/example/pubspec.lock

Fixed a few of() to maybeOf() uses that I missed before

Fixed a few of() to maybeOf() uses that I missed before

---

super_editor/lib/src/core/document_selection.dart
super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/layout_single_column/_presenter.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/default_editor/text_tools.dart
super_editor/lib/src/infrastructure/_listenable_builder.dart
super_editor/lib/src/infrastructure/multi_tap_gesture.dart
super_editor/lib/src/infrastructure/super_textfield/android/_caret.dart
super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_caret.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart
super_editor/lib/src/test/super_reader_test/super_reader_robot.dart
super_editor/test/src/default_editor/document_input_ime_test.dart
super_editor/test/src/default_editor/list_items_test.dart
super_editor/test/src/default_editor/super_editor_content_conversion_test.dart
super_editor/test/super_editor/document_test_tools.dart
super_editor/test/super_editor/mutable_document_test.dart
super_editor/test/super_textfield/super_textfield_auto_scroll_test.dart
super_editor/test/super_textfield/super_textfield_robot.dart
super_editor/test_goldens/editor/mobile/mobile_selection_test.dart

Fixed a bunch of Dart analysis complaints for Flutter test registry

Fixed a bunch of Dart analysis complaints for Flutter test registry

---

super_editor/dart_test.yaml
super_editor/lib/src/core/document_selection.dart
super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/layout_single_column/_presenter.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/default_editor/text_tools.dart
super_editor/lib/src/infrastructure/_listenable_builder.dart
super_editor/lib/src/infrastructure/multi_tap_gesture.dart
super_editor/lib/src/infrastructure/super_textfield/android/_caret.dart
super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_caret.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart
super_editor/lib/src/test/super_reader_test/super_reader_robot.dart
super_editor/test/src/default_editor/document_input_ime_test.dart
super_editor/test/src/default_editor/list_items_test.dart
super_editor/test/src/default_editor/super_editor_content_conversion_test.dart
super_editor/test/super_editor/document_test_tools.dart
super_editor/test/super_editor/mutable_document_test.dart
super_editor/test/super_textfield/super_textfield_auto_scroll_test.dart
super_editor/test/super_textfield/super_textfield_robot.dart
super_editor/test_goldens/editor/mobile/mobile_selection_test.dart

Cherry pick analysis fixes and test config file

Cherry pick analysis fixes and test config file

---

super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
super_editor/test/super_textfield/super_textfield_test.dart

This PR cherry-picks #846 to stable.

Cherry-pick "[SuperTextField] Fix selection and input when initializing with a focused FocusNode (Resolves #843) (#846)" to stable

---

super_editor/pubspec.yaml
super_editor/test/test_tools.dart

This PR cherry-picks [SuperEditor] Annotate custom test methods (#878) to stable

Cherry-pick "[SuperEditor] Annotate custom test methods (#878)" to stable

---

super_editor/example/lib/demos/supertextfield/android/demo_superandroidtextfield.dart
super_editor/example/lib/demos/supertextfield/ios/demo_superiostextfield.dart
super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart
super_editor/test/super_textfield/super_textfield_caret_test.dart

This PR cherry-picks "[SuperTextField] Expose caretStyle property (Resolves #884) (#889)" to stable

Cherry-pick "[SuperTextField] Expose caretStyle property (Resolves #884) (#889)" to stable

---

super_editor/lib/src/default_editor/document_gestures_mouse.dart
super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_user_interaction.dart
super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_mouse_interactor.dart
super_editor/test/super_textfield/super_textfield_gestures_test.dart

Fixes https://github.com/superlistapp/super_editor/issues/907

Respect GestureSettings from MediaQuery

---

super_editor/example/lib/demos/example_editor/_example_document.dart
super_editor/example/lib/demos/example_editor/_toolbar.dart
super_editor/example/lib/demos/example_editor/example_editor.dart
super_editor/example/lib/main.dart
super_editor/lib/src/core/document_layout.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/default_editor/tasks.dart
super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart
super_editor/lib/src/test/super_editor_test/supereditor_robot.dart
super_editor/lib/src/test/super_editor_test/tasks_test_tools.dart
super_editor/lib/super_editor.dart
super_editor/test/super_editor/components/task_test.dart

Cherry pick: Moved tasks into Super Editor and fixed bug that prevented creating new tasks after texisting tasks (Resolves #923) (#928)

Moved tasks into Super Editor and fixed bug that prevented creating new tasks after texisting tasks (Resolves #923) (#928)

---

super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart
super_editor/test/super_textfield/super_textfield_ime_test.dart

Expose Text InputAction cherry-picked to stable

Expose TextInputAction from SuperTextField (#906)

---

super_editor/example/lib/demos/demo_document_loses_focus.dart
super_editor/example/lib/demos/example_editor/example_editor.dart
super_editor/lib/src/default_editor/debug_visualization.dart
super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/super_editor.dart

Cherry pick: Added focus and IME debug visuals to Super Editor (Resolves #942) (#943)

Added focus and IME debug visuals to Super Editor (Resolves #942) (#943)

---

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart

Cherry Pick: [SuperTextField] Implement missing methods in ImeAttributedTextEditingController (#977)

[SuperTextField] Implement missing methods in ImeAttributedTextEditingController (#977)

---

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/test/super_textfield/super_textfield_ime_test.dart

Resolves #987.
I uncommented the tests for handling the ENTER key press and added new ones for NUMPAD ENTER.

Insert new line SuperTextField when NUMPAD ENTER is pressed

---

super_editor/example/lib/demos/example_editor/example_editor.dart
super_editor/example/lib/demos/supertextfield/_interactive_demo.dart
super_editor/example/pubspec.lock
super_editor/lib/src/default_editor/document_gestures_touch.dart
super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/lib/src/default_editor/document_ime/ime_decoration.dart
super_editor/lib/src/default_editor/document_scrollable.dart
super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/infrastructure/fill_width_if_constrained.dart
super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/test/super_editor/supereditor_popover_focus_test.dart
super_text_layout/example/lib/main.dart
super_text_layout/example/pubspec.lock
website/lib/homepage/featured_editor.dart

[SuperEditor] Fix build errors and warnings after upgrading to flutter 3.7.0. Resolves #999

[SuperEditor] Fix build errors and warnings after upgrading to flutter 3.7.0 (Resolves #999)

---

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
super_editor/test/super_textfield/super_textfield_test.dart
super_editor/test/test_tools.dart

This PR cherry-picks "[SuperTextField] Add ability to update keyboard appearance (Resolves #991) (#993)" to stable

Cherry-pick "[SuperTextField] Add ability to update keyboard appearance (Resolves #991) (#993)" to stable

---

super_editor/lib/src/default_editor/text.dart

[SuperEditor] Expose TextComponentState

---

super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/test/super_editor/supereditor_content_insertion_test.dart

This PR cherry-picks "[SuperEditor] Fix image insertion at the middle of a paragraph (Resolves #1018) (#1019)" to stable

Cherry-pick "[SuperEditor] Fix image insertion at the middle of a paragraph (Resolves #1018) (#1019)" to stable

---

super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/test/super_editor/document_test_tools.dart
super_editor/test/super_editor/supereditor_scrolling_test.dart
super_editor/test/super_editor/test_documents.dart

Don't change selection when the user taps to stop scrolling momentum on mobile (Resolves #1035) (#1036)

Don't change selection when the user taps to stop scrolling momentum on mobile (Resolves #1035) (#1036)

---

super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart
super_editor/test/super_textfield/super_textfield_emoji_test.dart

This PR cherry-picks "[SuperTextField][Android] Fix emoji deletion (Resolves #1031) (#1042)" to stable

Cherry-pick "[SuperTextField][Android] Fix emoji deletion (Resolves #1031) (#1042)" to stable

---

super_editor/example/lib/demos/example_editor/_toolbar.dart
super_editor/lib/src/core/document_composer.dart
super_editor/lib/src/default_editor/document_gestures_interaction_overrides.dart
super_editor/lib/src/default_editor/document_gestures_mouse.dart
super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart
super_editor/lib/src/default_editor/document_hardware_keyboard/document_physical_keyboard.dart
super_editor/lib/src/default_editor/list_items.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/default_editor/tasks.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/infrastructure/links.dart
super_editor/lib/src/test/super_editor_test/supereditor_robot.dart
super_editor/lib/super_editor.dart
super_editor/pubspec.yaml
super_editor/test/src/_text_entry_test_tools.dart
super_editor/test/src/default_editor/document_keyboard_actions_test.dart
super_editor/test/src/default_editor/list_items_test.dart
super_editor/test/src/default_editor/text_test.dart
super_editor/test/super_editor/document_test_tools.dart
super_editor/test/super_editor/supereditor_gestures_test.dart
super_editor/test/super_editor/test_documents.dart
super_editor/test/test_tools.dart

Cherry pick: [SuperEditor] Make links tappable when in "interaction mode" (Resolves #1024) (#1028)

[SuperEditor] Make links tappable when in "interaction mode" (Resolves #1024) (#1028)

---

super_editor/example/lib/demos/demo_animated_task_height.dart
super_editor/example/lib/main.dart

Cherry pick: Add a demo where the height of the content (e.g. task) can animate (#1056)

Add a demo where the height of the content (e.g. task) can animate (#1056)

---

super_editor/lib/src/default_editor/document_ime/document_serialization.dart

Added IME deserialization logs to help debug a Samsung issue.

Added IME deserialization logs to help debug a Samsung issue.

---

super_editor/lib/src/default_editor/document_ime/document_serialization.dart

Cherry pick: Added IME deserialization logs to help debug a Samsung issue. (Resolves #1047) (#1050)

Added IME deserialization logs to help debug a Samsung issue. (Resolves #1047) (#1050)

---

super_editor/example/lib/demos/demo_animated_task_height.dart
super_editor/lib/src/default_editor/document_caret_overlay.dart
super_editor/lib/src/default_editor/layout_single_column/_layout.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/infrastructure/_logging.dart
super_editor/lib/src/infrastructure/content_layers.dart
super_editor/lib/src/infrastructure/multi_tap_gesture.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
super_editor/lib/src/test/super_editor_test/supereditor_robot.dart
super_editor/test/infrastructure/content_layers_test.dart
super_editor/test/super_editor/bug_fix_test.dart
super_editor/test/super_editor/supereditor_scrolling_test.dart

Cherry pick: Rebuild document layers when document layout components change (Resolves #1022) (#1064)

Rebuild document layers when document layout components change (Resolves #1022) (#1064)

---

super_editor/lib/src/core/document_composer.dart

I noticed this leak of a stream controller as I was browsing the source code to get familiar with how Super Editor works.
Added a test as well.

[SuperEditor] Fix stream leak

---

super_editor/example/lib/demos/editor_configs/demo_mobile_editing_ios.dart
super_editor/example/lib/demos/example_editor/example_editor.dart
super_editor/example/lib/demos/super_document/demo_super_reader.dart
super_editor/example/pubspec.yaml
super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/lib/src/infrastructure/platforms/android/colors.dart
super_editor/lib/src/infrastructure/platforms/android/toolbar.dart
super_editor/lib/src/infrastructure/platforms/ios/colors.dart
super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
super_editor/lib/src/infrastructure/platforms/ios/toolbar.dart
super_editor/lib/src/infrastructure/platforms/mobile_documents.dart
super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/metrics.dart
super_editor/lib/src/infrastructure/toolbar_position_delegate.dart
super_editor/lib/src/infrastructure/touch_controls.dart
super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/lib/src/super_reader/super_reader.dart
super_editor/pubspec.yaml

This PR cherry-picks "[SuperEditor] Update mobile toolbar design (Resolves #963) (#1008)" to stable

Cherry-pic "[SuperEditor] Update mobile toolbar design (Resolves #963) (#1008)" to stable

---

super_editor/test/super_editor/supereditor_text_layout_test.dart
super_text_layout/CHANGELOG.md
super_text_layout/lib/super_text_layout.dart
super_text_layout/lib/super_text_layout_inspector.dart
super_text_layout/pubspec.yaml

Cherry pick: Make super_text_layout releasable again (Resolves #1083) (#1092)

Cherry pick: Make super_text_layout releasable again (Resolves #1083) (#1092)

---

super_editor/lib/src/core/editor.dart

Add new 'Editor' class and edit pipeline without breaking anything (Related to #748)(Resolves #1087) (#1088)

Add new 'Editor' class and edit pipeline without breaking anything (Related to #748)(Resolves #1087) (#1088)

---

attributed_text/lib/src/attributed_spans.dart

Make markers public on AttributedSpans to fix static analysis error (Resolves #1131)

Make markers public on AttributedSpans to fix static analysis error (Resolves #1131)

---

attributed_text/lib/src/attributed_spans.dart

Cherry Pick - Make markers public on AttributedSpans to fix static analysis error (Resolves #1131) (#1134)

Make markers public on AttributedSpans to fix static analysis error (Resolves #1131) (#1134)

---

attributed_text/CHANGELOG.md
attributed_text/pubspec.yaml
super_editor/CHANGELOG.md
super_editor/example/pubspec.lock
super_editor/example/pubspec.yaml
super_editor/pubspec.yaml
super_editor_markdown/CHANGELOG.md
super_editor_markdown/pubspec.yaml
super_text_layout/CHANGELOG.md
super_text_layout/example/pubspec.lock
super_text_layout/pubspec.yaml

Release new versions of super_editor, attributed_text, super_text_layout, and super_editor_markdown

Release new versions of super_editor, attributed_text, super_text_layout, and super_editor_markdown

---

attributed_text/CHANGELOG.md
attributed_text/pubspec.yaml
super_editor/CHANGELOG.md
super_editor/example/pubspec.lock
super_editor/example/pubspec.yaml
super_editor/pubspec.yaml
super_editor_markdown/CHANGELOG.md
super_editor_markdown/pubspec.yaml
super_text_layout/CHANGELOG.md
super_text_layout/example/pubspec.lock
super_text_layout/pubspec.yaml

Release new versions of super_editor, attributed_text, super_text_layout, and super_editor_markdown (#1137)

Release new versions of super_editor, attributed_text, super_text_layout, and super_editor_markdown (#1137)

---

super_editor/example/analysis_options.yaml
super_editor/lib/src/core/document.dart
super_editor/lib/src/default_editor/multi_node_editing.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/test/super_editor/infrastructure/editor_test.dart

Added reference to old DocumentNode within NodeRemovedEvent (Resolves #1181) (#1182)

Added reference to old DocumentNode within NodeRemovedEvent (Resolves #1181) (#1182)

---

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
super_editor/test/super_textfield/super_textfield_ime_test.dart

[SuperTextField][Android] Fix glitch with predictive text. Resolves #1113
On Android, some glitches are happening when "Predictive Text" is enabled on the Samsung keyboard. For example, in the SuperTextField Demo, after typing "you" at the end of the text, pressing backspace, typing "u" and pressing space, the word "you" is deleted.
I was able to reproduce this issue.
Currently, whenever we apply the list of deltas, we send our current text editing value to the OS and it seems that this is causing the issue. According to [this comment](https://github.com/flutter/flutter/issues/113253#issuecomment-1569238178), it seems we don't need to send the value to the OS if our editing value is the same as the OS thinks it is.
This PR changes `ImeAttributedTextEditingController` to store the IME …

[SuperTextField][Android] Fix glitch with predictive text (Resolves #1113)

---

super_editor/lib/src/default_editor/document_caret_overlay.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/infrastructure/content_layers.dart
super_editor/pubspec.yaml
super_editor/test/infrastructure/content_layers_test.dart
super_text_layout/example/pubspec.lock
super_text_layout/lib/src/infrastructure/blink_controller.dart
super_text_layout/lib/src/text_layout.dart
super_text_layout/pubspec.yaml

Re-use ContentLayers overlay and underlay Elements instead of always re-inflating (Resolves #1236)

Re-use ContentLayers overlay and underlay Elements instead of always re-inflating (Resolves #1236)

---

super_editor/lib/src/default_editor/document_caret_overlay.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/infrastructure/content_layers.dart
super_editor/pubspec.yaml
super_editor/test/infrastructure/content_layers_test.dart
super_text_layout/lib/src/infrastructure/blink_controller.dart
super_text_layout/lib/src/text_layout.dart
super_text_layout/pubspec.yaml

Re-use ContentLayers overlay and underlay Elements instead of always re-inflating (Resolves #1236) (#1239)

Re-use ContentLayers overlay and underlay Elements instead of always re-inflating (Resolves #1236) (#1239)

---

super_editor/pubspec.yaml
super_text_layout/CHANGELOG.md
super_text_layout/pubspec.yaml

Release Super Text Layout v0.1.7

Super Text Layout v0.1.7

---

super_editor/pubspec.yaml
super_text_layout/CHANGELOG.md
super_text_layout/pubspec.yaml

Cherry pick: Super Text Layout v0.1.7 (#1249)

Super Text Layout v0.1.7 (#1249)

---

super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart
super_editor/lib/src/default_editor/list_items.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
super_editor/pubspec.yaml
super_editor/test/super_editor/supereditor_text_layout_test.dart
super_editor/test/super_textfield/type_into_super_textfield_test.dart
super_editor/test_goldens/editor/supereditor_text_layout_test.dart
super_text_layout/example/pubspec.lock
super_text_layout/lib/src/super_text.dart
super_text_layout/lib/src/super_text_inspector.dart
super_text_layout/lib/src/super_text_layout_with_selection.dart
super_text_layout/lib/src/text_layout.dart
super_text_layout/test_goldens/super_text_test.dart

Replace textScaleFactor with textScaler (Resolves #1238)

Replace textScaleFactor with textScaler (Resolves #1238)

---

super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart

This PR cherry-picks "[SuperTextField][Android] Fix drag handle jumping when adding text at the end (Resolves #1114) (#1124)" to stable.

Cherry-pick "[SuperTextField][Android] Fix drag handle jumping when adding text at the end (Resolves #1114) (#1124)" to stable

---

super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart

This PR cherry-picks "[SuperEditor][SuperTextField] Fix emoji panel positioning (Resolves #1105) (#1107)" to stable.

Cherry-pick "[SuperEditor][SuperTextField] Fix emoji panel positioning (Resolves #1105) (#1107)" to stable

---

super_editor/test/src/default_editor/document_input_ime_test.dart

This PR cherry-picks "[SuperEditor] Add chinese input test (Resolves #1230) (#1270)" to stable.

Cherry-pick "[SuperEditor] Add chinese input test (Resolves #1230) (#1270)" to stable

---

super_editor/lib/src/default_editor/document_gestures_mouse.dart
super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/lib/src/default_editor/document_ime/document_ime_interaction_policies.dart
super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
super_editor/lib/src/default_editor/document_scrollable.dart
super_editor/lib/src/infrastructure/flutter/flutter_pipeline.dart
super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
super_editor/lib/src/infrastructure/scrolling_diagnostics/_scrolling_minimap.dart
super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart
super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_user_interaction.dart
super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_mouse_interactor.dart

Replaced widget post frame scheduling with a new extension method - also fixes SuperTextField hot reload bug (Resolves #1262)
We have a ridiculous number of post frame callbacks. At some point we should see if a change in approach could eliminate most of them.

Replaced widget post frame scheduling with a new extension method - also fixes SuperTextField hot reload bug (Resolves #1262)

---

super_editor/lib/src/default_editor/document_gestures_mouse.dart
super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/lib/src/default_editor/document_ime/document_ime_interaction_policies.dart
super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
super_editor/lib/src/default_editor/document_scrollable.dart
super_editor/lib/src/infrastructure/flutter/flutter_pipeline.dart
super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
super_editor/lib/src/infrastructure/scrolling_diagnostics/_scrolling_minimap.dart
super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart
super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart
super_editor/lib/src/infrastructure/super_textfield/ios/_user_interaction.dart
super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_mouse_interactor.dart

Cherry Pick: Replaced widget post frame scheduling with a new extension method - also fixes SuperTextField hot reload bug (Resolves #1262) (#1301)

Cherry Pick: Replaced widget post frame scheduling with a new extension method - also fixes SuperTextField hot reload bug (Resolves #1262) (#1301)

---

super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart
super_editor/test/super_textfield/attributed_text_editing_controller_test.dart

SuperTextField AttributedTextEditingController notify listeners when clear()ed (Resolves #1261)

SuperTextField AttributedTextEditingController notify listeners when clear()ed (Resolves #1261)

---

super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart
super_editor/test/super_textfield/attributed_text_editing_controller_test.dart

Cherry Pick: SuperTextField AttributedTextEditingController notify listeners when clear()ed (Resolves #1261)

Cherry Pick: SuperTextField AttributedTextEditingController notify listeners when clear()ed (Resolves #1261)

---

super_editor/lib/src/core/edit_context.dart
super_editor/lib/src/default_editor/document_scrollable.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/infrastructure/documents/document_scaffold.dart
super_editor/lib/src/infrastructure/documents/document_scroller.dart
super_editor/lib/src/super_reader/super_reader.dart
super_editor/lib/super_editor.dart
super_editor/test/src/_document_test_tools.dart
super_editor/test/src/default_editor/document_input_ime_test.dart
super_editor/test/src/default_editor/document_keyboard_actions_test.dart
super_editor/test/src/default_editor/list_items_test.dart
super_editor/test/src/default_editor/super_editor_test.dart
super_editor/test/src/default_editor/text_test.dart
super_editor/test/super_editor/components/horizontal_rule_test.dart
super_editor/test/super_editor/document_test_tools.dart
super_editor/test/super_editor/supereditor_attributions_test.dart
super_editor/test/super_editor/supereditor_content_insertion_test.dart
super_editor/test/super_editor/supereditor_gestures_test.dart
super_editor/test/super_editor/supereditor_keyboard_test.dart
super_editor/test/super_editor/supereditor_mobile_handles_test.dart
super_editor/test/super_editor/supereditor_popover_focus_test.dart
super_editor/test/super_editor/supereditor_scrolling_test.dart
super_editor/test/super_editor/supereditor_selection_test.dart
super_editor/test/super_editor/supereditor_smoke_test.dart
super_editor/test/super_editor/supereditor_software_keyboard_toolbar_test.dart
super_editor/test/super_editor/supereditor_style_test.dart
super_editor/test/super_editor/text_entry/keyboard_selection_and_deletion_test.dart
super_editor/test/super_editor/text_entry/paragraph_conversions_test.dart
super_editor/test/super_editor/text_entry/stable_tags_test.dart

Cherry Pick: Exposed scroll control through SuperEditorContext (Resolves #1288) (#1292)

Cherry Pick: Exposed scroll control through SuperEditorContext (Resolves #1288) (#1292)

---

super_editor/lib/src/default_editor/super_editor.dart
super_editor/test/super_editor/components/block_node_test.dart

This PR cherry-picks "[SuperEditor][web] Fix new line duplication (Resolves #1219) (#1336)" to stable.

Cherry-pick "[SuperEditor][web] Fix new line duplication (Resolves #1219) (#1336)" to stable

---

super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/test/super_editor/text_entry/super_editor_common_text_entry_test.dart
super_editor/test/test_tools.dart

Don't delete content when control keys are pressed with a selection (Resolves #1331)

Don't delete content when control keys are pressed with a selection (Resolves #1331)

---

super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/test/super_editor/text_entry/super_editor_common_text_entry_test.dart
super_editor/test/test_tools.dart

Don't delete content when control keys are pressed with a selection (Resolves #1331) (#1345)

Don't delete content when control keys are pressed with a selection (Resolves #1331) (#1345)

---

super_editor/example/lib/demos/in_the_lab/in_the_lab_scaffold.dart
super_editor/example/lib/demos/in_the_lab/selected_text_colors_demo.dart
super_editor/example/lib/main.dart
super_editor/lib/src/core/styles.dart
super_editor/lib/src/default_editor/attributions.dart
super_editor/lib/src/default_editor/blockquote.dart
super_editor/lib/src/default_editor/layout_single_column/_layout.dart
super_editor/lib/src/default_editor/layout_single_column/_styler_user_selection.dart
super_editor/lib/src/default_editor/list_items.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/default_editor/tasks.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/infrastructure/content_layers.dart
super_editor/lib/src/super_reader/super_reader.dart
super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart
super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart
super_editor/test/super_editor/supereditor_selection_test.dart

Cherry Pick: Selected text can now display itself in a different color from surrounding text (Resolves #1332) (#1364)

Cherry Pick: Selected text can now display itself in a different color from surrounding text (Resolves #1332) (#1364)

---

super_editor/pubspec.yaml
super_editor/test/super_reader/super_reader_keyboard_test.dart
super_editor/test/super_textfield/super_textfield_ime_test.dart

Cherry Pick: Upgrade test robots package version and adjust for some Flutter bugs (Resolves #1344) (#1377)

Cherry Pick: Upgrade test robots package version and adjust for some Flutter bugs (Resolves #1344) (#1377)

---

attributed_text/lib/src/attributed_text.dart
attributed_text/test/attributed_text_test.dart

Added substring and length APIs to AttributedText (Resolves #1200)

Added substring and length APIs to AttributedText (Resolves #1200)

---

attributed_text/lib/src/attributed_text.dart
attributed_text/test/attributed_text_test.dart

Cherry Pick: Added substring and length APIs to AttributedText (Resolves #1200) (#1374)

Cherry Pick: Added substring and length APIs to AttributedText (Resolves #1200) (#1374)

---

attributed_text/lib/src/attributed_spans.dart

Added a 'range' property to AttributionSpan (Resolves #1192)

Added a 'range' property to AttributionSpan (Resolves #1192)

---

attributed_text/lib/src/attributed_text.dart
attributed_text/test/attributed_text_test.dart

Add easier attribution span query methods (Resolves #1193)

Add easier attribution span query methods (Resolves #1193)

---

attributed_text/lib/src/attributed_text.dart
attributed_text/test/attributed_text_test.dart

Cherry Pick: Add easier attribution span query methods (Resolves #1193) (#1384)

Cherry Pick: Add easier attribution span query methods (Resolves #1193) (#1384)

---

super_editor/test/super_editor/supereditor_robot_test.dart

This PR cherry-picks "[SuperEditor] Add placeCaretInParagraph tests (Resolves #627) (#1363)" to stable.

Cherry-pick "[SuperEditor] Add placeCaretInParagraph tests (Resolves #627) (#1363)" to stable

---

super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/test/super_editor/supereditor_copy_and_paste_test.dart

This PR cherry-picks "[SuperEditor] Fix pasting multiple lines (Resolves #871) (#1391)" to stable.

Cherry-pick "[SuperEditor] Fix pasting multiple lines (Resolves #871) (#1391)" to stable

---

super_editor/example/pubspec.yaml
super_editor/pubspec.yaml

This PR cherry-picks "[SuperEditor] Bump linkify to v5.0.0 (Resolves #1383) (#1402)" to stable.

Cherry-pick "[SuperEditor] Bump linkify to v5.0.0 (Resolves #1383) (#1402)" to stable

---

super_editor/example/lib/demos/in_the_lab/feature_action_tags.dart
super_editor/example/lib/demos/in_the_lab/feature_pattern_tags.dart
super_editor/example/lib/demos/in_the_lab/feature_stable_tags.dart
super_editor/example/lib/demos/in_the_lab/popover_list.dart
super_editor/lib/src/core/edit_context.dart
super_editor/lib/src/default_editor/document_caret_overlay.dart
super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart
super_editor/lib/src/default_editor/document_ime/document_ime_interaction_policies.dart
super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
super_editor/lib/src/default_editor/document_layers/attributed_text_bounds_overlay.dart
super_editor/lib/src/default_editor/layout_single_column/_layout.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/infrastructure/attribution_layout_bounds.dart
super_editor/lib/src/infrastructure/content_layers.dart
super_editor/lib/src/infrastructure/documents/document_scaffold.dart
super_editor/lib/src/infrastructure/selection_leader_document_layer.dart
super_editor/lib/src/super_reader/super_reader.dart
super_editor/lib/super_editor.dart
super_editor/test/infrastructure/content_layers_test.dart
super_editor/test/super_editor/supereditor_selection_test.dart
super_editor/test/super_editor/text_entry/text_test.dart

Cherry Pick: Fixed tagging NPEs - includes new ContentLayers layer widgets, IME focus policy adjustment (Resolves #1397) (#1406)

Cherry Pick: Fixed tagging NPEs - includes new ContentLayers layer widgets, IME focus policy adjustment (Resolves #1397) (#1406)

---

super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/default_editor/text_tokenizing/action_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/pattern_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/stable_tags.dart

Added convenience APIs for document selections within a single TextNode (Resolves #1195)

Added convenience APIs for document selections within a single TextNode (Resolves #1195)

---

super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/default_editor/text_tokenizing/action_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/pattern_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/stable_tags.dart

Cherry Pick: Added convenience APIs for document selections within a single TextNode (Resolves #1195) (#1415)

Cherry Pick: Added convenience APIs for document selections within a single TextNode (Resolves #1195) (#1415)

---

super_editor/example/lib/demos/example_editor/_toolbar.dart
super_editor/lib/src/core/document.dart
super_editor/lib/src/core/document_selection.dart
super_editor/lib/src/core/editor.dart
super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/default_document_editor.dart
super_editor/lib/src/default_editor/default_document_editor_reactions.dart
super_editor/lib/src/default_editor/multi_node_editing.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/default_editor/text_tokenizing/action_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/pattern_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/stable_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/tags.dart
super_editor/lib/src/infrastructure/attribution_layout_bounds.dart
super_editor/test/super_editor/text_entry/text_test.dart

Replace selections with ranges in relevant requests and commands (Resolves #1194)

Replace selections with ranges in relevant requests and commands (Resolves #1194)

---

super_editor/example/lib/demos/example_editor/_toolbar.dart
super_editor/lib/src/core/document.dart
super_editor/lib/src/core/document_selection.dart
super_editor/lib/src/core/editor.dart
super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/default_document_editor.dart
super_editor/lib/src/default_editor/default_document_editor_reactions.dart
super_editor/lib/src/default_editor/multi_node_editing.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/default_editor/text_tokenizing/action_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/pattern_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/stable_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/tags.dart
super_editor/lib/src/infrastructure/attribution_layout_bounds.dart
super_editor/test/super_editor/text_entry/text_test.dart

Cherry Pick: Replace selections with ranges in relevant requests and commands (Resolves #1194) (#1419)

Cherry Pick: Replace selections with ranges in relevant requests and commands (Resolves #1194) (#1419)

---

super_editor/lib/src/infrastructure/platforms/ios/magnifier.dart

This PR cherry-picks "[SuperEditor][iOS] Fix magnifier (Resolves #1329) (#1422)" to stable

Cherry-pick "[SuperEditor][iOS] Fix magnifier (Resolves #1329) (#1422)" to stable

---

super_editor/lib/src/infrastructure/documents/document_scroller.dart
super_editor/lib/src/super_reader/read_only_document_keyboard_interactor.dart
super_editor/lib/src/super_reader/reader_context.dart
super_editor/lib/src/super_reader/super_reader.dart
super_editor/test/super_editor/supereditor_test_tools.dart
super_editor/test/super_reader/reader_test_tools.dart

This PR cherry-picks "[SuperReader] Migrate to DocumentScroller API (Resolves #1306) (#1423)" to stable

Cherry-pick "[SuperReader] Migrate to DocumentScroller API (Resolves #1306) (#1423)" to stable

---

super_editor/lib/src/infrastructure/content_layers.dart

This PR cherry-picks "[SuperEditor] Fix crash in release mode (Resolves #1424) (#1425)" to stable

Cherry-pick "[SuperEditor] Fix crash in release mode (Resolves #1424) (#1425)" to stable

---

attributed_text/lib/src/attributed_spans.dart
super_editor/test/super_editor/supereditor_gestures_test.dart
super_editor/test/super_editor/text_entry/links_test.dart

Cherry Pick: Tap to open multiple links in the same paragraph (Resolves #1426) (#1442)

Cherry Pick: Tap to open multiple links in the same paragraph (Resolves #1426) (#1442)

---

super_editor/example/lib/demos/example_editor/_toolbar.dart
super_editor/example/lib/demos/in_the_lab/popover_list.dart
super_editor/lib/src/core/edit_context.dart
super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/infrastructure/popovers.dart
super_editor/lib/super_editor.dart
super_editor/test/super_editor/text_entry/text_test.dart

This PR cherry-picks "[ExampleApp] Fix link popover (Resolves #1440) (#1443)" to stable.

Cherry-pick "[ExampleApp] Fix link popover (Resolves #1440) (#1443)" to stable

---

super_editor_markdown/lib/src/document_to_markdown_serializer.dart
super_editor_markdown/lib/src/markdown_to_document_parsing.dart
super_editor_markdown/test/super_editor_markdown_test.dart

This PR cherry-picks "[SuperEditorMarkdown] Add header alignments (Resolves #865) (#1350)" to stable.

Cherry-pick "[SuperEditorMarkdown] Add header alignments (Resolves #865) (#1350)" to stable

---

.github/workflows/cherry_pick_to_stable.yaml

Added GitHub action to automatically put up cherry pick PRs from main to stable (Resolves #1513)

Added GitHub action to automatically put up cherry pick PRs from main to stable (Resolves #1513)

---

super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/super_textfield/infrastructure/text_field_scroller.dart
super_editor/lib/src/super_textfield/super_textfield.dart
super_editor/lib/src/super_textfield/super_textfield_context.dart
super_editor/test/super_textfield/super_textfield_ime_test.dart

Created a SuperTextFieldContext with a BuildContext and a TextFieldScroller - passed it key handlers (Resolves #1487) (#1507)

Created a SuperTextFieldContext with a BuildContext and a TextFieldScroller - passed it key handlers (Resolves #1487) (#1507)

---

super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart
super_editor/pubspec.yaml
super_editor/test/super_textfield/super_textfield_ime_test.dart

This PR cherry-picks "[SuperTextField] Fix new line duplication (Resolves #1468) (#1469)" to stable.

Cherry-pick "[SuperTextField] Fix new line duplication (Resolves #1468) (#1469)" to stable

---

super_editor/lib/src/super_textfield/super_textfield.dart

Cherry Pick: SuperTextField: propagate blinkTimingMode to platform implementations (Resolves #1543) (#1544)

Cherry Pick: SuperTextField: propagate blinkTimingMode to platform implementations (Resolves #1543) (#1544)

---

README.md

Cherry Pick: README - Add dependency_overrides snippet (#1542)

Cherry Pick: README - Add dependency_overrides snippet (#1542)

---

super_editor/lib/src/default_editor/common_editor_operations.dart
super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart
super_editor/lib/src/default_editor/list_items.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/super_textfield/android/android_textfield.dart
super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/super_textfield/ios/ios_textfield.dart
super_editor/test/super_editor/supereditor_floating_cursor_test.dart
super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart
super_editor/test/super_editor/supereditor_text_layout_test.dart
super_editor/test/super_textfield/type_into_super_textfield_test.dart
super_editor/test_goldens/editor/supereditor_text_layout_test.dart
super_text_layout/example/pubspec.lock
super_text_layout/lib/src/super_text.dart
super_text_layout/lib/src/super_text_inspector.dart
super_text_layout/lib/src/super_text_layout_with_selection.dart
super_text_layout/lib/src/text_layout.dart
super_text_layout/test/super_text_test.dart
super_text_layout/test_goldens/super_text_test.dart

Updates for Flutter 3.16
As of Flutter 3.16, we have some failing tests on stable branch and also some analyzer errors.
This test is failing because, after Material3, the default primary color changed from blue to purple. We have a test for the floating cursor where we check the cursor color when it's far from the text and when it's close to the text. When it's close, the color defaults to the theme's primary color.
This PR changes the test to compare the value with the `ThemeData`'s primary color.
This test is related to the macOS selectors. In the previous Flutter stable version, `deleteBackwardByDecomposingPreviousCharacter` wasn't generated during tests, so we have a temporary code to generate the selector manually. Now that Flutter already reports this selector, we can safely remove …

Updates for Flutter 3.16

---

super_editor/lib/src/super_textfield/android/android_textfield.dart
super_editor/lib/src/super_textfield/ios/ios_textfield.dart
super_editor/test/super_editor/supereditor_content_insertion_test.dart
super_editor/test/super_editor/supereditor_gestures_test.dart
super_editor/test/super_textfield/super_textfield_test.dart
super_editor/test/super_textfield/super_textfield_theme_test.dart

This PR cherry-picks "[SuperTextField][mobile] Migrate popover toolbars to OverlayPortal (Resolves #1602) (#1604)" to stable

Cherry-pick "[SuperTextField][mobile] Migrate popover toolbars to OverlayPortal (Resolves #1602) (#1604)" to stable

---

super_editor/lib/src/infrastructure/flutter/text_input_configuration.dart
super_editor/lib/src/super_textfield/android/android_textfield.dart
super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart
super_editor/lib/src/super_textfield/input_method_engine/_ime_text_editing_controller.dart
super_editor/lib/src/super_textfield/ios/ios_textfield.dart
super_editor/test/super_textfield/super_textfield_ime_test.dart

This PR cherry-picks "[SuperTextField] Fix text capitalization configuration (Resolves #1617) (#1619)" to stable

Chery-pick "[SuperTextField] Fix text capitalization configuration (Resolves #1617) (#1619)" to stable

---

super_text_layout/CHANGELOG.md
super_text_layout/pubspec.yaml

Release super_text_layout v0.1.8

Release super_text_layout v0.1.8

---

super_editor/lib/src/default_editor/default_document_editor_reactions.dart
super_editor/lib/src/default_editor/list_items.dart
super_editor/lib/src/default_editor/tasks.dart
super_editor/test/super_editor/text_entry/links_test.dart

This PR cherry-picks "[SuperEditor] Linkify on Enter (Resolves #1600) (#1616)" to stable.

Cherry-pick "[SuperEditor] Linkify on Enter (Resolves #1600) (#1616)" to stable

---

super_editor/example/lib/demos/example_editor/_toolbar.dart

Cherry-pick "[DemoApp] Fix link visual styles when applying by the toolbar (Resolves #1632) (#1650)" to stable.

Cherry-pick "[DemoApp] Fix link visual styles when applying by the toolbar (Resolves #1632) (#1650)" to stable

---

super_editor/lib/src/default_editor/document_scrollable.dart
super_editor/lib/src/infrastructure/flutter/cupertino_scrollbar.dart
super_editor/lib/src/infrastructure/flutter/material_scrollbar.dart
super_editor/lib/src/infrastructure/flutter/scrollbar.dart
super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart
super_editor/test/super_editor/supereditor_gestures_test.dart
super_editor/test/super_reader/super_reader_gestures_test.dart
super_editor/test/super_textfield/super_textfield_gestures_test.dart

This PR cherry-picks "[SuperEditor][SuperTextField][Desktop] Fix trackpad and scrollbar scrolling (Resolves #1628) (#1649)" to stable

Cherry-pick "[SuperEditor][SuperTextField][Desktop] Fix trackpad and scrollbar scrolling (Resolves #1628) (#1649)" to stable

---

super_editor/README.md
super_editor/example/lib/demos/example_editor/example_editor.dart
super_editor/example/lib/demos/in_the_lab/in_the_lab_scaffold.dart
super_editor/example/lib/demos/in_the_lab/selected_text_colors_demo.dart
super_editor/example/lib/demos/interaction_spot_checks/spot_check_scaffold.dart
super_editor/example/lib/demos/styles/demo_doc_styles.dart
super_editor/example/lib/marketing_video/main_marketing_video.dart
super_editor/lib/src/core/styles.dart
super_editor/lib/src/default_editor/blockquote.dart
super_editor/lib/src/default_editor/layout_single_column/_presenter.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/default_editor/tasks.dart
super_editor/lib/src/default_editor/text.dart
super_editor/lib/src/super_reader/super_reader.dart
super_editor/test/super_editor/components/block_node_test.dart
super_editor/test/super_editor/components/blockquote_test.dart
super_editor/test/super_editor/components/list_items_test.dart
super_editor/test/super_editor/supereditor_component_selection_test.dart
super_editor/test/super_editor/supereditor_scrolling_test.dart
super_editor/test/super_editor/supereditor_style_test.dart
super_editor/test_goldens/editor/supereditor_text_layout_test.dart
super_editor/test_goldens/editor/text_entry/super_editor_composing_region_underline_test.dart
website/lib/homepage/featured_editor.dart

This PR cherry-picks "[SuperEditor] Add constants for style metadata (Resolves #825) (#1682)" to stable.

Cherry-pick "[SuperEditor] Add constants for style metadata (Resolves #825) (#1682)" to stable

---

super_editor/example/lib/demos/example_editor/_toolbar.dart
super_editor/example/lib/demos/infrastructure/super_editor_item_selector.dart
super_editor/example/pubspec.yaml
super_editor/lib/src/infrastructure/default_popovers.dart
super_editor/lib/src/infrastructure/popover_scaffold.dart
super_editor/lib/src/infrastructure/selectable_list.dart
super_editor/lib/super_editor.dart
super_editor/pubspec.yaml
super_editor/test/infrastructure/popover_test.dart
super_editor/test/infrastructure/selectable_list_test.dart

This PR cherry-picks "[Infrastructure] Implement custom dropdown widget (Resolves #1527, Resolves #731, Resolves #689) (#1538)" to stable.

Cherry-pick "[Infrastructure] Implement custom dropdown widget (Resolves #1527, Resolves #731, Resolves #689) (#1538)" to stable

---

super_editor/lib/src/default_editor/document_gestures_mouse.dart
super_editor/test/super_editor/supereditor_scrolling_test.dart
super_editor/test/super_editor/supereditor_selection_test.dart
super_editor/test/super_editor/supereditor_test_tools.dart

This PR cherry-picks "[SuperEditor][Desktop] Keep selection base while dragging (Resolves #1393) (#1713)" to stable.

Cherry-pick "[SuperEditor][Desktop] Keep selection base while dragging (Resolves #1393) (#1713)" to stable

---

super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart
super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
super_editor/lib/src/super_reader/super_reader.dart
super_editor/lib/src/test/super_reader_test/super_reader_robot.dart
super_editor/test/super_editor/mobile/super_editor_ios_selection_test.dart
super_editor/test/super_editor/supereditor_tapregion_test.dart
super_editor/test/super_editor/supereditor_test_tools.dart
super_editor/test/super_reader/reader_test_tools.dart
super_editor/test/super_reader/super_reader_tapregion_test.dart

This PR cherry-picks "[SuperEditor][SuperReader][Android] Add TapRegion groupId (Resolves #1692) (#1698)" to stable.

Cherry-pick "[SuperEditor][SuperReader][Android] Add TapRegion groupId (Resolves #1692) (#1698)" to stable

---

super_editor/example/lib/demos/example_editor/_toolbar.dart
super_editor/lib/src/default_editor/default_document_editor.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/test/super_editor/components/paragraph_test.dart
super_text_layout/lib/src/super_text.dart

Paragraph alignment now changes immediately - moved paragraph change from direct document manipulation to a request/command pair (Resolves #1587)
https://github.com/superlistapp/super_editor/assets/7259036/fb46e49a-6c91-4ba4-ad9e-11cf8619ec60

Paragraph alignment now changes immediately - moved paragraph change from direct document manipulation to a request/command pair (Resolves #1587)

---

super_editor/lib/src/default_editor/document_caret_overlay.dart
super_editor/lib/src/default_editor/document_gestures_touch_android.dart
super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart
super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart
super_editor/test/super_editor/supereditor_caret_test.dart
super_editor/test/super_editor/supereditor_initialization_test.dart
super_text_layout/lib/src/infrastructure/blink_controller.dart

This PR cherry-picks "[SuperEditor][Android] Fix caret not blinking with autofocus (Resolves #1723) (#1726)" to stable.

Cherry-pick "[SuperEditor][Android] Fix caret not blinking with autofocus (Resolves #1723) (#1726)" to stable

---

super_editor/lib/src/default_editor/default_document_editor.dart
super_editor/lib/src/default_editor/default_document_editor_reactions.dart
super_editor/lib/src/infrastructure/strings.dart
super_editor/lib/src/test/super_editor_test/supereditor_robot.dart
super_editor/test/super_editor/text_entry/dash_conversion_test.dart
super_editor/test/super_editor/text_entry/paragraph_conversions_test.dart
super_editor_markdown/lib/src/markdown_to_document_parsing.dart
super_editor_markdown/test/super_editor_markdown_test.dart

This PR cherry-picks "[SuperEditor] Add em-dash conversion reaction (Resolves #1177) (#1712)" to stable

Cherry-pick "[SuperEditor] Add em-dash conversion reaction (Resolves #1177) (#1712)" to stable

---

super_editor/example/lib/demos/example_editor/_example_document.dart

This PR cherry-picks "Fix demo app compilation error due to ExpectedSize (#1793)" to stable

Cherry-pick "Fix demo app compilation error due to ExpectedSize (#1793)" to stable

---

super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart

Cherry Pick: Original PR - #1853

Cherry Pick: Fix wrong key sequences (#1853)

---

super_editor/pubspec.yaml

See https://github.com/flutter/flutter/pull/143847#issuecomment-1967978767 for motivation.
cc @matthew-carroll for review

Use dependency_overrides for flutter_tests_robots

---

super_editor/pubspec.yaml

Updated Super Editor dependencies.

Updated Super Editor dependencies.

---

website/lib/homepage/editor_toolbar.dart
website/lib/homepage/featured_editor.dart
website/lib/homepage/inside_the_toolbox.dart
website/pubspec.lock

Fix demo website (Resolves #1874)
Refactoring changes related `super_text_layout` and `attributed_text` apis due to recent deps updates in `super_editor`: https://github.com/superlistapp/super_editor/commit/5f04941ef3771828c19fa4e720e8880e90fa90d5

Fix demo website (Resolves #1874)

---

super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart

Cherry Pick: Original PR - https://github.com/superlistapp/super_editor/pull/1877

Cherry Pick: Fix iOS cursor blinking when typing (Resolves #1876)

---

super_editor_markdown/lib/src/markdown_to_document_parsing.dart
super_editor_markdown/pubspec.yaml
super_editor_markdown/test/super_editor_markdown_test.dart
super_text_layout/lib/src/text_layout.dart

Reverted markdown package upgrade - downgraded from 6.0.0 back to 4.0.0 - due to test failures caused by 6.0.0

Reverted markdown package upgrade - downgraded from 6.0.0 back to 4.0.0 - due to test failures caused by 6.0.0

---

super_editor/example/pubspec.yaml
super_editor/pubspec.yaml

This PR cherry-picks "Upgrade uuid package to v4.0.0 (Resolves #1899) (#1917)" to stable

Cherry-pick "Upgrade uuid package to v4.0.0 (Resolves #1899) (#1917)" to stable

---

super_editor/example/pubspec.yaml
super_editor/example_perf/pubspec.lock
super_editor/lib/src/infrastructure/flutter/material_scrollbar.dart
super_text_layout/lib/src/text_layout.dart

Flutter 3.22 Updates
This PR cherry-picks commits that were present only on the main branch. It also fixes a nullability hint due to a Flutter change.

Flutter 3.22 Updates

---

doc/website/source/super-text-field-guides/quickstart.md

Update docs website with a quickstart guide for SuperTextField.
This PR adds a quickstart guid to `SuperTextField`

Update docs website with a quickstart guide for SuperTextField

---

super_editor/lib/src/default_editor/text_tokenizing/stable_tags.dart
super_editor/lib/src/default_editor/text_tokenizing/tags.dart
super_editor/test/super_editor/text_entry/tagging/stable_tags_test.dart

Allow emojis at beginning of paragraph with tagging enabled (Resolves #1882)
This PR is a copy of https://github.com/superlistapp/super_editor/pull/1891 - I'm taking the final steps to get it merged in.

Allow emojis at beginning of paragraph with tagging enabled (Resolves #1882)

---

golden_runner/lib/src/commands.dart

[golden_tester] Remove docker image after running the command. Resolves #2088
After running the golden tester commands, the container is removed but the image is kept. As a result, we end up with a bunch of dangling images.
This PR changes the tool to remove the image after running the commands. It also changes how we handle failures in the tests. Currently, we are throwing and exiting with an unhandled exception when tests fail. With these changes, we will gracefully exit the process after running the commands.

[golden_tester] Remove docker image after running the command (Resolves #2088)

---

super_editor/example/lib/demos/example_editor/_toolbar.dart
super_editor/example/lib/l10n/app_en.arb
super_editor/example_docs/lib/editor.dart
super_editor/lib/src/default_editor/attributions.dart
super_editor/lib/src/default_editor/default_document_editor.dart
super_editor/lib/src/default_editor/paragraph.dart
super_editor/lib/src/default_editor/super_editor.dart
super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart
super_editor/lib/src/test/super_reader_test/super_reader_inspector.dart
super_editor/test/super_editor/components/paragraph_test.dart
super_editor/test/super_editor/supereditor_multi_editor_test.dart

[SuperEditor][SuperReader] - Added font family attribution, superscript and subscript, and paragraph indentation (Resolves #2107)
These additions are intended to support baseline Quill Deltas support. These are expected behaviors.
https://github.com/superlistapp/super_editor/assets/7259036/e1ee8ed8-2256-42a3-b17e-c4868c394959
https://github.com/superlistapp/super_editor/assets/7259036/b9d9b1e2-9085-473a-b17e-860622b31c49

[SuperEditor][SuperReader] - Added font family attribution, superscript and subscript, and paragraph indentation (Resolves #2107)

---

.github/workflows/pr_validation.yaml
super_editor_quill/.gitignore
super_editor_quill/.metadata
super_editor_quill/CHANGELOG.md
super_editor_quill/LICENSE
super_editor_quill/README.md
super_editor_quill/analysis_options.yaml
super_editor_quill/lib/src/content/formatting.dart
super_editor_quill/lib/src/content/multimedia.dart
super_editor_quill/lib/src/parsing/block_formats.dart
super_editor_quill/lib/src/parsing/inline_formats.dart
super_editor_quill/lib/src/parsing/parser.dart
super_editor_quill/lib/super_editor_quill.dart
super_editor_quill/pubspec.yaml
super_editor_quill/test/parsing_test.dart

Cherry Pick: [SuperEditor][Quill] - Create super_editor_quill package - parse Quill Deltas into a MutableDocument (Resolves #2105) (#2108)

[SuperEditor][Quill] - Create super_editor_quill package - parse Quill Deltas into a MutableDocument (Resolves #2105) (#2108)

---

attributed_text/CHANGELOG.md
attributed_text/pubspec.yaml
super_editor/pubspec.yaml

Cherry Pick: Release attributed_text  v0.3.2, upgraded Super Editor to use it

Cherry Pick: Release attributed_text  v0.3.2, upgraded Super Editor to use it

---

super_editor_quill/CHANGELOG.md
super_editor_quill/lib/src/testing/quill_delta_comparison.dart
super_editor_quill/pubspec.yaml

Cherry Pick: super_editor_quill v0.1.0-dev.2 to stable

Cherry Pick: super_editor_quill v0.1.0-dev.2 to stable

---

super_editor/lib/src/test/super_editor_test/supereditor_robot.dart

[Infrastructure] Fix widget tester tapping on block component. Resolves #2197
Trying to tap on the downstream position of a block component is always resulting in an upstream selection.
The issue is that the computation to determine the offset to tap relies on `getRectForPosition`. For block components, this always return a rect of the entire component, as is documented in the method:
```dart
/// Returns a [Rect] that bounds this entire box component.
///
/// The behavior of this method is the same, regardless of whether the given
/// [nodePosition] is `upstream` or `downstream`.
@override
Rect getRectForPosition(NodePosition nodePosition) {
///
}
```
This PR changes the `tapAtDocumentPosition` to handle block components differently, by computing its edge position and returning a `Rect` …

[Infrastructure] Fix widget tester tapping on block component (Resolves #2197)

---

super_text_layout/example/lib/rainbow_builder.dart
super_text_layout/example/lib/rainbow_character_supertext.dart

Fix: Replace private state reference with generic State reference - somehow this change didn't make it from main

Fix: Replace private state reference with generic State reference - somehow this change didn't make it from main

---

super_editor/lib/src/default_editor/layout_single_column/_layout.dart
super_editor/lib/src/super_reader/super_reader.dart

This PR "Ignore unused_element_parameter for unused parameters (#2239)" to stable

Cherry-pick "Ignore unused_element_parameter for unused parameters (#2239)" to table

---

super_editor_quill/lib/src/parsing/inline_formats.dart
super_editor_quill/lib/src/parsing/parser.dart
super_editor_quill/lib/src/serializing/serializers.dart
super_editor_quill/test/parsing_test.dart
super_editor_quill/test/serializing_test.dart

[Quill] - Added parsing and serialization support for inline embeds (Resolves #2289)

[Quill] - Added parsing and serialization support for inline embeds (Resolves #2289)

---

super_editor_quill/lib/src/parsing/parser.dart

Parse deltas using a custom editor (Resolves #2293)

Parse deltas using a custom editor (Resolves #2293)

---

doc/website/bin/super_editor_docs.dart
doc/website/source/_data.yaml
doc/website/source/_includes/components/navbar.jinja
doc/website/source/super-editor/guides/_data.yaml
doc/website/source/super-editor/guides/add-a-mobile-keyboard-toolbar.md
doc/website/source/super-editor/guides/add-a-popover-toolbar.md
doc/website/source/super-editor/guides/add-new-type-of-content.md
doc/website/source/super-editor/guides/assemble-a-document.md
doc/website/source/super-editor/guides/dark-mode-and-light-mode.md
doc/website/source/super-editor/guides/document-from-markdown.md
doc/website/source/super-editor/guides/index.md
doc/website/source/super-editor/guides/markdown/parsing.md
doc/website/source/super-editor/guides/markdown/serializing.md
doc/website/source/super-editor/guides/quickstart.md
doc/website/source/super-editor/guides/quill/parsing.md
doc/website/source/super-editor/guides/quill/serializing.md
doc/website/source/super-editor/guides/style-a-document.md

Cherry-Pick: [Docs] - Added website guides for Markdown and Quill parsing and serialization. (#2297)

Cherry-Pick: [Docs] - Added website guides for Markdown and Quill parsing and serialization. (#2297)

---

doc/website/pubspec.lock

[Docs] - Upgrade deps for website

[Docs] - Upgrade deps for website

---

super_editor/pubspec.yaml
super_text_layout/CHANGELOG.md
super_text_layout/pubspec.yaml

Cherry Pick: super_text_layout release, super_editor pubspec dep revision

Cherry Pick: super_text_layout release, super_editor pubspec dep revision

---

super_editor/lib/src/default_editor/blockquote.dart

[SuperEditor][SuperReader] - Add indent support to blockquote (Resolves #2347)

[SuperEditor][SuperReader] - Add indent support to blockquote (Resolves #2347)

---

super_editor_markdown/lib/src/image_syntax.dart
super_editor_markdown/lib/src/markdown_to_document_parsing.dart
super_editor_markdown/pubspec.yaml
super_editor_markdown/test/custom_parsers/callout_block.dart
super_editor_markdown/test/super_editor_markdown_test.dart

This PR cherry-picks "Upgrade markdown package reference (#2364)" to stable.

Cherry-pick "Upgrade markdown package reference (#2364)" to stable

---

super_editor/example/lib/demos/mobile_chat/demo_mobile_chat.dart
super_editor/lib/src/infrastructure/sliver_hybrid_stack.dart
super_editor/test/super_editor/super_editor_shrinkwrap_test.dart

Fix layout exception with shrinkwrap

---

super_editor/lib/src/infrastructure/keyboard_panel_scaffold.dart

[Super Editor] - Prevent NaN and negative bottom insets in KeyboardScaffoldSafeArea (Resolves #2535)
See the issue ticket for an explanation of the problem.

[Super Editor] - Prevent NaN and negative bottom insets in KeyboardScaffoldSafeArea (Resolves #2535)

---

.github/workflows/pr_validation.yaml
super_editor_spellcheck/lib/src/super_editor/spelling_and_grammar_plugin.dart
super_editor_spellcheck/pubspec.yaml
super_editor_spellcheck/test/spellcheck_ignore_rules_test.dart
super_text_layout/pubspec.yaml

This PR cherry-picks "[Spellcheck] Add tests for ignore rules (Resolves #2573) (#2574)" to stable.

Cherry-pick "[Spellcheck] Add tests for ignore rules (Resolves #2573) (#2574)" to stable

---

.github/workflows/pr_validation.yaml

This PR cherry-picks "[Infrastructure] Update actions/upload-artifact to v4 (Resolves #2585) (#2587)" to stable.

Cherry-pick "[Infrastructure] Update actions/upload-artifact to v4 (Resolves #2585) (#2587)" to stable

---

super_editor/lib/src/infrastructure/keyboard_panel_scaffold.dart

[SuperEditor] - Keyboard safe area: Catch possible local to global exception.
Apparently, under some circumstances, when we try to run local-to-global within the keyboard safe area, it can happen when some number of ancestors have a dirty layout, which then throws an exception.
This PR catches that exception and returns zero.
It's unclear what specific situation is causing this. When I ran into this in a client app, I think the specific offending widget was a fractional translation box, or something similar. But it's not clear why it was in a dirty layout state.

[SuperEditor] - Keyboard safe area: Catch possible local to global exception

---

super_editor/lib/src/default_editor/list_items.dart

This PR cherry-picks "[SuperEditor] - Add inline widget builder support to list items" to stable.

Cherry-pick "[SuperEditor] - Add inline widget builder support to list items" to stable

---

super_editor/example/ios/Flutter/AppFrameworkInfo.plist
super_editor/example/ios/Podfile
super_editor/example/ios/Podfile.lock
super_editor/example/ios/Runner.xcodeproj/project.pbxproj
super_editor/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
super_editor/example/ios/Runner/AppDelegate.swift
super_editor/example/ios/Runner/Info.plist
super_editor/example_chat/android/settings.gradle
super_editor/example_chat/pubspec.lock

Added updated example and example_chat project build files and config files.
Updating files that keep changing on my machine so that they stop appearing as changed in git.

Added updated example and example_chat project build files and config files.

---

super_editor_quill/lib/src/serializing/serializers.dart
super_editor_quill/pubspec.yaml
super_editor_quill/test/serializing_test.dart

[Quill] - Serialize quill inline embeds for inline placeholders (Resolves #2590)

[Quill] - Serialize quill inline embeds for inline placeholders (Resolves #2590)
