example/lib/spikes/editable_text_document/_doc_components.dart, example/lib/spikes/editable_text_document/_doc_model.dart, example/lib/spikes/editable_text_document/_selection.dart, example/lib/spikes/editable_text_document/editable_text_document_spike.dart, example/macos/Runner/DebugProfile.entitlements
Spike: EditableText selection in doc.
In this spike I composed a number of `EditableText` widgets, along with other widgets, into a simple document.
I successfully implemented display of different widgets based on a naive document model, achieved scrolling with the mouse and while dragging, and re-implemented cursor selection across multiple `EditableText` widgets.
Unfortunately, because `EditableText` owns its own input connection, there is no obvious way for the overall editor to own an input connection. This prevents the editor from taking actions across document nodes, and may also prevent re-wiring of various shortcut key commands.
Conclusion: we need to build our own text widgets to accomplish editor composition.
=> Spike: EditableText selection in doc.

example/lib/spikes/custom_text_input/custom_text_input_spike.dart, example/lib/spikes/custom_text_widget/custom_text_widget.dart
This PR includes 2 spikes.
Spike 1: compare and contrast `TextInputClient` with `RawKeyboardListener`.
Spike 2: implement a single `RawKeyboardListener` editable text area.
For spike 2:
```
/// Spike:
/// Create a prototype of a custom text widget for reference purposes.
///
/// Features:
///  - displays I-beam cursor when hovering over text
///  - inserts caret where the user taps on text
///
///  - all latin characters, numbers, and special symbols can be entered into the field
///  - backspace key deletes the previous character when the selection is collapsed
///  - backspace key deletes all selected characters when the selection is not collapsed
///  - delete key deletes the previous character when the selection is collapsed
///  - delete key deletes all selected characters when the …
```
=> Spike custom text input

example/lib/demo_attributed_text.dart, example/lib/main.dart, lib/flutter_richtext.dart, lib/src/infrastructure/_logging.dart, lib/src/infrastructure/attributed_spans.dart, lib/src/infrastructure/attributed_text.dart, test/src/infrastructure/attributed_spans_test.dart, test/src/infrastructure/attributed_text_test.dart
`AttributedSpans` and `AttributedText` forms the basis for text styling within the editor. These concepts are conceivably applicable to all sorts of document rendering and editing, so they are placed within the `infrastructure` package.
A very simple logger implementation is added as well so that we can keep useful debug print statements without polluting clients' logs. I've kept this logger private to the package so that we can change it however we want moving forward.
I've included an interactive demo for `AttributedText`. Here is a screenshot:
Eventually, I'm envisioning a kind of interactive story where users can see how an editor is built up from a single `Text` widget. I think this interactive education would help developers adopt the package with a deep understanding of how it …
=> Add AttributedSpans and AttributedText to the package

lib/src/core/document.dart, lib/src/core/document_composer.dart, lib/src/core/document_editor.dart, lib/src/core/document_layout.dart, lib/src/core/document_selection.dart, lib/src/core/edit_context.dart, pubspec.lock, pubspec.yaml
Added core abstractions including `Document`, `DocumentSelection`, `DocumentEditor`, `DocumentLayout`, `DocumentComposer`, and `EditContext`.
I thought about adding tests, but most of this code is either abstract, or only makes sense with implementations like `ParagraphNode`. I think our time will be better spent writing tests for real documents.
Here's where I stand with the various abstractions:
`Document` and `DocumentSelection`: These abstractions represent purely logical document details. I'm pretty confident about these APIs.
`DocumentEditor`: Responsible for altering a logical document. This implementation (and probably API) definitely need work. The `DocumentEditor` API will be relevant for incremental document saving as well as undo/redo behavior. I put off this work because I …
=> Added core abstractions

example/lib/main.dart, example/lib/sliver_example_editor.dart
Fixes: https://github.com/superlistapp/rich_text_editor/issues/70
This PR adds a Sliver example of the Editor that has been created before with the following Slivers:
- SliverAppBar
- SliverToBoxAdapter
- SliverList
@matthew-carroll In the example, you can see the [focus problem](https://github.com/superlistapp/rich_text_editor/issues/72) by doing the following:
- Open the Sliver example from the drawer, tap on the paragraph (any point), the caret is correctly set but the keyboard actions are not working (user can not input any text even though the keyboard sound is there).
=> Add an example usage of slivers and rich text editor.

.github
I added a `.github` file to configure code owners.
For now, I've defined myself as the sole code owner so that I have to be added to all PRs and approve all PRs. I think this is important until we have a proven track record of PRs reviewed by other developers. Once we do, we can expand the set of code owners.
=> Added codeowners configuration in .github file

example/lib/demos/demo_document_loses_focus.dart, example/lib/demos/demo_switch_document_content.dart, example/lib/main.dart, lib/src/core/document_layout.dart, lib/src/default_editor/document_interaction.dart, lib/src/default_editor/editor.dart, lib/src/default_editor/layout.dart, lib/src/default_editor/list_items.dart, lib/src/default_editor/paragraph.dart
Fixed: switching from one document to another document when a content selection is present no longer results in an error UI.
Fixed: removing focus from the editor now makes the caret disappear.
=> Fix doc switching bug and caret focus bug

lib/src/default_editor/document_interaction.dart, lib/src/infrastructure/attributed_spans.dart, test/serialization/markdown_test.dart, test/src/infrastructure/attributed_text_test.dart
Fixes a couple bugs:
Bug #99 - when adding new list items or new lines that go offscreen, auto-scroll does not move the viewport down to show the extent.
Bug #100 - when typing individual characters with a style, the style of the new character does not combine with the matching style of the character before it.
=> Fix bugs: auto-scroll not working, styled text not combining spans

analysis_options.yaml, example/lib/spikes/editor_abstractions/default_editor/paragraph.dart, pubspec.yaml
Updates to use pedantic version 1.11.0 over 1.8.0. This will result in more analyzer warnings that will need to be fixed, but is worth considering as the package supports dart 2.12+.
=> Feature/Update to use pedantic 1.11

super_editor/.run/Example.run.xml, super_editor/lib/src/default_editor/text.dart, super_editor/test/src/default_editor/text_test.dart
Fix: bold/italics style toggling was adding an extra character to the styled text at the end. (#107)
=> Fix: bold/italics style toggling was adding an extra character to the styled text at the end. (#107)

super_editor/example/lib/demos/demo_paragraphs.dart, super_editor/example/lib/main.dart, super_editor/example/lib/spikes/editor_abstractions/default_editor/box_component.dart, super_editor/example/pubspec.lock, super_editor/lib/src/default_editor/box_component.dart, super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/infrastructure/selectable_text.dart
Fixes bug where selection rectangles leave gaps between lines. This problem comes from Flutter's text box calculations, so the solution for now is a hard-coded height adjustment.
Fixes bug where inserting an HR with "---" before some text would delete all following text.
Fixes bug where copying text within a single node would copy everything from the selected content to the end of the node.
Fixes bug where paragraphs that don't require full width will shrink their widget, resulting in incorrect layout for center and right aligned text that doesn't fill all available width.
=> Bug fixes for #115, #118, #123, #126

super_editor/lib/src/infrastructure/selectable_text.dart
Recomitting a fix for #123 because it was undone in a recent commit.
=> Recomitting a fix for #123 because it was undone in a recent commit.

super_editor/lib/src/default_editor/document_keyboard_actions.dart
Bugfix: Resolved a race condition with paste functionality. (#151)
The initial bug was very difficult to reproduce, however, adding a forced delay immediately after the clipboard query and before the insertion of the content was able to reproduce the error every time.
To fix the race condition, I update the document selection to its final location before attempting to paste any content. If paste took a very long time, this would result in seeing the content deleted, seeing the caret where the deleted text used to be, and then seeing the new content pasted into place. Paste should never take long enough to notice this series of events.
=> Bugfix: Resolved a race condition with paste functionality. (#151)

super_editor/README.md, super_editor/example/lib/demos/demo_attributed_text.dart, super_editor/example/lib/demos/demo_document_loses_focus.dart, super_editor/example/lib/demos/demo_markdown_serialization.dart, super_editor/example/lib/demos/demo_paragraphs.dart, super_editor/example/lib/demos/demo_switch_document_content.dart, super_editor/example/lib/demos/example_editor.dart, super_editor/example/lib/demos/example_editor/_example_document.dart, super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/demos/sliver_example_editor.dart, super_editor/example/lib/demos/supertextfield/_interactive_demo.dart, super_editor/example/lib/main.dart, super_editor/lib/src/core/document_composer.dart, super_editor/lib/src/default_editor/attributions.dart, super_editor/lib/src/default_editor/blockquote.dart, super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/lib/src/default_editor/editor.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/infrastructure/attributed_spans.dart, super_editor/lib/src/infrastructure/attributed_text.dart, super_editor/lib/src/serialization/markdown.dart, super_editor/lib/super_editor.dart, super_editor/test/serialization/markdown_test.dart, super_editor/test/src/default_editor/attributions_test.dart, super_editor/test/src/default_editor/text_test.dart, super_editor/test/src/infrastructure/attributed_spans_test.dart, super_editor/test/src/infrastructure/attributed_text_test.dart
This PR implements link attributions for the example editor.
To better facilitate link-style behavior, I changed the concept of text attributions from `dynamic` to a dedicated base class called `Attribution`. This required updating lots of codes and tests to use the new type.
I also added some new behavior to `AttributedSpans` based on the type of queries that we need to do in the example app when we select no link vs one link vs 2+ links.
=> Example editor toolbar links

super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/lib/src/infrastructure/_platform_detector_io.dart, super_editor/lib/src/infrastructure/_platform_detector_unsupported.dart, super_editor/lib/src/infrastructure/_platform_detector_web.dart, super_editor/lib/src/infrastructure/keyboard.dart, super_editor/lib/src/infrastructure/platform_detector.dart, super_editor/lib/src/infrastructure/super_textfield.dart, super_editor/test/src/default_editor/document_keyboard_actions_test.dart, super_editor/test/src/infrastructure/_platform_test_tools.dart, super_editor/test/src/infrastructure/super_textfield_test.dart
Use control key for shortcuts on Windows and Linux. (#172)
=> Use control key for shortcuts on Windows and Linux. (#172)

super_editor/lib/src/infrastructure/selectable_text.dart
Bugfix: jumping to start/end of lines was off by a line on web due to inaccurate position calculations in the text system. Added half a line height to the calculations to sit definitively within the current line. (#170)
=> Bugfix: jumping to start/end of lines was off by a line on web

super_editor/lib/src/infrastructure/super_textfield.dart, super_editor/test/src/infrastructure/super_textfield_test.dart
Cmd + backspace deletes the entire line before the caret. (#176)
=> Cmd + backspace deletes the entire line before the caret. (#176)

super_editor/lib/src/infrastructure/keyboard.dart
Ignore characters on web that are reported as 'Dead'. (#119)
On web, some keys report a `character` value of "Dead". This is a Flutter bug/incomplete feature issue. I don't think there is much we can do, so I've opted to ignore any character with that value.
=> Ignore characters on web that are reported as 'Dead'. (#119)

super_editor/lib/src/core/document.dart, super_editor/lib/src/core/document_composer.dart, super_editor/lib/src/core/document_editor.dart, super_editor/lib/src/core/document_layout.dart, super_editor/lib/src/core/edit_context.dart, super_editor/lib/src/default_editor/blockquote.dart, super_editor/lib/src/default_editor/box_component.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_interaction.dart, super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/lib/src/default_editor/editor.dart, super_editor/lib/src/default_editor/horizontal_rule.dart, super_editor/lib/src/default_editor/image.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/default_editor/text_tools.dart, super_editor/lib/src/infrastructure/attributed_spans.dart, super_editor/lib/src/infrastructure/attributed_text.dart, super_editor/test/editor_smoke_tests/editor_entry_smoke_test.dart, super_editor/test/src/_document_test_tools.dart, super_editor/test/src/default_editor/text_test.dart
The original implementation of keyboard handlers included the document and selection manipulation that corresponded to those actions. Combining the keyboard handlers and the behaviors makes it more difficult for developers to remap keys or automate document interaction, because developers have to replicate all the behavioral code.
This PR extracts all the document and selection manipulation from the keyboard handlers and puts its in a class called `CommonEditorOperations`. The name isn't very good, but `Editor` and `DocumentInteractor` were already taken. Maybe we can re-evaluate the naming scheme for v0.2.0.
@salihgueler given the volume of code that was moved and *hopefully* simplified, it's probably worth pulling down this branch and trying to break the editor.
PS - I think we should …
=> 197 make document interaction reusable

super_editor/README.md, super_editor/example/lib/demos/demo_attributed_text.dart, super_editor/example/lib/demos/demo_document_loses_focus.dart, super_editor/example/lib/demos/demo_markdown_serialization.dart, super_editor/example/lib/demos/demo_paragraphs.dart, super_editor/example/lib/demos/demo_selectable_text.dart, super_editor/example/lib/demos/demo_switch_document_content.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/demos/sliver_example_editor.dart, super_editor/example/lib/marketing_video/main_marketing_video.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/infrastructure/super_selectable_text.dart, super_editor/lib/src/infrastructure/super_textfield.dart, super_editor/lib/super_editor.dart, super_editor/test/editor_smoke_tests/editor_entry_smoke_test.dart, super_editor/test/src/infrastructure/super_textfield_test.dart
Renamed Editor to SuperEditor and SelectableText to SuperSelectableText to disambiguate with other widgets and classes.
=> Renamed Editor to SuperEditor and SelectableText to SuperSelectableText

super_editor/lib/src/core/document.dart, super_editor/lib/src/core/document_layout.dart, super_editor/lib/src/core/document_selection.dart, super_editor/lib/src/default_editor/box_component.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/lib/src/default_editor/horizontal_rule.dart, super_editor/lib/src/default_editor/image.dart, super_editor/lib/src/default_editor/layout.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/default_editor/text_tools.dart, super_editor/lib/src/infrastructure/composable_text.dart, super_editor/test/editor_smoke_tests/editor_entry_smoke_test.dart, super_editor/test/src/default_editor/document_keyboard_actions_test.dart, super_editor/test/src/default_editor/text_test.dart
Based on user feedback, I've replaced various `dynamic` references with `NodeSelection` and `NodePosition` marker interfaces.
For text-related behaviors `TextPosition` has been replaced by `TextNodePosition` and `TextSelection` has been replaced by `TextNodeSelection`. `TextNodePosition` extends `TextPosition` and `TextNodeSelection` extends `TextSelection` to minimize rework.
=> Introduced NodeSelection and NodePosition marker interfaces to avoid dynamic references. (#209)

super_editor/CHANGELOG.md, super_editor/README_RELEASING.md, super_editor/example/lib/demos/demo_attributed_text.dart, super_editor/example/lib/demos/demo_selectable_text.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/main.dart, super_editor/lib/src/core/document.dart, super_editor/lib/src/core/document_selection.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/horizontal_rule.dart, super_editor/lib/src/default_editor/image.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/infrastructure/super_selectable_text.dart, super_editor/pubspec.yaml
- Updated CHANGELOG.md with release notes for v0.1.0
- Fixed a bug where pressing delete in an empty paragraph below an image/HR would move the selection up but not delete the paragraph
- Fixed a bug where pressing left/right with an expanded selection would move the caret after collapsing, but the caret shouldn't move
- Fixed a bug where the format bar in the example app wasn't changing position with a changing selection
- Updated the demo of AttributedText to use the new Attribution definitions instead of Strings
=> Created README_RELEASING.md with instructions for releasing new versions of Super Editor

super_editor/lib/src/core/document_composer.dart
As I wanted to learn about and gain a deep understanding of the `super_editor` API in general, I explored the individual parts of the source code.  
In this process, I figured it would be very useful to add public member API docs accordingly and contribute them back to the project.
In this pull request in particular, I am only adding documentation to the `core/document_composer.dart` file, exclusively. This should hopefully make it easier to review the individual parts of my contribution.
Because we need to have a common standard for documentation in order to make the developer experience when researching about the API coherent, I **strictly followed** Effective Dart.  
In this case, the relevant articles are:
* [Effective Dart: Documentation](https://dart.dev/guides/language/effective-dar …
=> [docs] core/document_composer.dart

super_editor/example/lib/demos/demo_RTL.dart, super_editor/example/lib/main.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/default_editor/text_tools.dart, super_editor/lib/src/infrastructure/super_selectable_text.dart
- closes #124 
- Exposes textDirection property of `SelectableText`. 
- In `paragraphBuilder`, textDirection is set to `TextDirection.rtl` if the first non-whitespace character of a paragraph is from an RTL language. Everything else is `TextDirection.ltr`.
Result as seen in the added demo:
=> Set Textdirection based on input language

super_editor/lib/src/default_editor/common_editor_operations.dart
An exception was getting if the user keeps trying to delete (with backspace key) when all nodes are already deleted
=> fix(common_editor_operations): exception when deleting without existence of nodes has been solved

super_editor/lib/src/default_editor/common_editor_operations.dart
I was checking the code for a few days to understand why in web (and I think it happens on desktop too) the first letter(offset = 0) of each node/paragraph could not be forward deleted. I found the error and I made this little fix, but I want to keep helping you. it is a very nice project!
=> fix(common_editor_operatons): bug deleting TextPosition's offset = 0 of nodes solved

super_editor/lib/src/core/document_editor.dart, super_editor/lib/src/default_editor/blockquote.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/test/src/core/document_editor.dart
closes: #251 
I wasn't sure how to properly handle the case when the `oldNode` doesn't exist. I noticed some APIs do nothing, print to console or throw an exception. So I went with the latter.
=> Add `replaceNode` to `DocumentEditorTransaction`

super_editor/lib/src/core/document_editor.dart, super_editor/test/src/core/document_editor_test.dart
It was previously comparing `_nodes` with `nodes` but `nodes` is a getter that returns `_nodes` so they're identical and hence `const DeepCollectionEquality().equals(_nodes, nodes)` is always true.
This is my second PR related to misbehaving equality checks so would it be worth adding a few unit tests?
=> MutableDocument equality check compares nodes of other document

super_editor/lib/src/infrastructure/super_selectable_text.dart
Bugfix: Caret stays invisible while user is typing - it should become visible (Resolves #318)
=> Bugfix: Caret stays invisible while user is typing - it should become visible (Resolves #318)

super_editor/lib/src/core/document_layout.dart, super_editor/lib/src/default_editor/layout.dart
The ComponentContext is passed to each component builder so that the builder can make decisions about whether or not to return a component, and how to configure a component that is returned.
The ComponentContext already provides access to the Document, current DocumentNode, and current NodeSelection.
There are situations where the creation of an individual component requires knowledge about the document selection.
Example:
Consider the Medium editor with a title and subtitle at the top of the document. When the user selects any part of the title, both the title and subtitle show side-bar labels that read "Title" and "Subtitle". Therefore, the title component makes a decision based on selection in the subtitle and vis-a-versa.
=> Add current DocumentSelection to ComponentContext (Resolves #334)

super_editor/example/lib/demos/components/demo_text_with_hint.dart, super_editor/example/lib/main.dart, super_editor/lib/src/default_editor/text.dart
I investigated the issue where the caret doesn't match the height of the hint text. I found a few areas in the code that might contribute to the problem. To test the issue directly, I created a new component called `TextWithHintComponent` and then I painted a demo screen with multiple text hints at different sizes.
You can see in the attached video that the carets all match the hint text. Therefore, I'll need some further information to understand why this is a problem in Superlist.
https://user-images.githubusercontent.com/7259036/138003325-6ed2a6b3-2d42-47a1-a8c2-825a17a2e7aa.mov
Changes:
- Created a demo screen for text components with hint text
- Created ProxyDocumentComponent to easily wrap an existing DocumentComponent with decoration
- Created ProxyTextComposable to easily wrap an …
=> Caret size doesn't match hint text

super_editor/example/pubspec.lock, super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/test/src/default_editor/document_keyboard_actions_test.dart
Fix: pressing character during selection deletes selection and adds character (Resolves #290)
The problem was that the handler responsible for deleting the selection didn't look for a pressed character key, it just deleted the selection and returned.
Now, the handler also inserts a character if one is pressed.
=> Fix: pressing character during selection deletes selection and adds character (Resolves #290)

super_editor/lib/src/default_editor/paragraph.dart
It is possible to define a color for the caret using the selections styles extension, but in practice (for paragraphs only), this value is ignored. Instead, the text selection color (defined in the same extension) is used as the caret color.
As done for other node types (e.g. list items or block quote), use the value coming from the extension (if defined).
=> [Bugfix] Use caret color from selections styles extensions (if defined)

super_editor/lib/src/infrastructure/caret.dart
Temporary hack fix to avoid caret mis-placement in SuperTextField (Resolves #369)
See #369 for my investigation into the problem and how I arrived at this solution.
See #370 for a ticket to fix these issues in general.
=> Temporary hack fix to avoid caret mis-placement in SuperTextField (Resolves #369)

super_editor/lib/src/default_editor/common_editor_operations.dart
fixes #364 
I added a condition for `unindentListItem` to skip `shift + tab` if the node isn't a `ListItemNode`
=> fixes shift+tab exception for non ListItemNode

super_editor/lib/src/default_editor/paragraph.dart
Fixes #381:
When splitting a paragraph, create a new clone of metadata instead of sharing the same instance with the newly created paragraph nodes to prevent the behavior described in #381.
=> Clone metadata instead of sharing the same instance when splitting a paragraph

super_editor/lib/src/default_editor/common_editor_operations.dart
`_insertCharacterInTextComposable` takes as input `ignoreComposerAttributions`, but the caller (`insertCharacter`) never passes it.
This PR updates `insertCharacter` to pass the this value.
=> Pass ignoreComposerAttributions to insertCharacter

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/src/default_editor/list_items_test.dart
Convert paragraph to list item for "1." and "1)" but not "1 " (Resolves #339)
This is an adjustment and resubmission to a PR from @wilsonowilson.
CC @britannio
=> Convert paragraph to list item for "1." and "1)" but not "1 " (Resolves #339)

super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/lib/src/infrastructure/keyboard.dart, super_editor/test/src/default_editor/document_keyboard_actions_test.dart
On Windows the keyboard shortcuts don't work because `keyEvent.character` is null. This PR changes the code to match against `keyEvent.logcialKey`, which in my testing works on both Windows and MacOS. I also moved this matching logic into a public helper function to cut down on code duplication and make it easier to add custom keybindings.
=> Use LogicalKeyboardKey to detect shortcuts

super_editor/lib/src/default_editor/list_items.dart
Fixed alignment of number in ordered list (Resolves #402) - there wasn't enough horizontal space, now there is.
Adjusted vertical alignment of dot in unordered list (Resolves #338) - the vertical position was too high. I don't have a perfect solution to this, but I moved it down a little bit.
https://user-images.githubusercontent.com/7259036/152285948-f547ce0d-6aef-4f8d-9899-85c488e7aff3.mov
=> Fixed alignment of number in ordered list (Resolves #402), Adjusted vertical alignment of dot in unordered list (Resolves #338)

super_editor/lib/src/infrastructure/attributed_spans.dart, super_editor/test/src/infrastructure/attributed_spans_test.dart
The current implementation of `collapseSpans` operates by pre-generating the list of start and end points for the collapsed spans, then walking that list and repeatedly checking the list of `SpanMarker`s to determine which `Attribution`s should apply to each span. In cases with many spans this causes a large amount of duplicate work, especially in cases with overlapping spans. In my testing it takes the method almost 2 seconds to return with 1000 spans. For a less contrived example, it only needs about 50 overlapping spans to take over 16ms (time for a frame when running at 60fps).
This PR:
- Changes `collapseSpans` to run with a single linear pass of the `SpanMarker` list. It also eliminates the preprocessing step of generating the start and end locations for the collapsed spans, which …
=> Optimizing AttributedSpans.collapseSpans() to run in linear time

super_editor/example/android/app/build.gradle, super_editor/example/android/app/src/main/AndroidManifest.xml, super_editor/example/android/app/src/main/res/values-night/styles.xml, super_editor/example/android/app/src/main/res/values/styles.xml, super_editor/example/android/build.gradle, super_editor/example/windows/flutter/generated_plugin_registrant.cc, super_editor/example/windows/flutter/generated_plugin_registrant.h
Regenerated Android runner project after upgrading Flutter to 2.10
The latest stable version of Flutter looks like it came with new API constraints, and possibly other changes. I deleted the old Android example project and generated a new one.
=> Regenerated Android runner project after upgrading Flutter to 2.10

super_editor/lib/src/default_editor/document_input_keyboard.dart
Hopefully I'm not completely misreading the code, but it looks like the docstrings for `continueExecution` and `haltExecution` were swapped.
=> Fixing docstrings on ExecutionInstruction enum members

super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/test/editor_smoke_tests/bug_fix_test.dart
Bugfix: Deleting new upstream nodes throws exception (Resolves #429)
The problem was that the expected selection after the deletion was using the top node ID, rather than the base node ID.
=> Bugfix: Deleting new upstream nodes throws exception (Resolves #429)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/lib/src/default_editor/paragraph.dart
Title pretty much says it all: there's a typo in a named parameter. This PR fixes it.
=> Fixing typo: s/Metdata/Metadata/g

.github/workflows/pr_validation.yaml, super_editor/example/analysis_options.yaml, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/infrastructure/strings.dart, super_editor/test/src/infrastructure/strings_test.dart
Bugfix: caret no longer gets stuck in middle of emojis when moving left/right (Resolves #391)
#391 said errors were being thrown. I wasn't able to reproduce any errors by selecting emojis on desktop in the example app. However, the caret was getting stuck in the middle of emojis because we were moving by code point rather than by character. This PR adds machinery to all `String`s to move by character, and updates the keyboard handler to use the new behavior.
@miguelcmedeiros please let me know if you're still seeing any errors or related problems with emojis.
=> Bugfix: caret no longer gets stuck in middle of emojis when moving left/right (Resolves #391)

super_editor/lib/src/default_editor/document_gestures_touch.dart
Bugfix: mobile handles mis-aligned on desktop (Resolves #446)
The problem was that the document layer link was applied on the outside of a `Center` widget, which caused the layer link to wrap all available space, instead of just the document. I switched the order of the two widgets so that the layer link applies to the exact bounds of the document.
=> Bugfix: mobile handles mis-aligned on desktop (Resolves #446)

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/default_editor/layout.dart, super_editor/lib/src/default_editor/text.dart
Handle empty documents (Resolves #274, Resolves #410)
Fixes a bug in empty documents where a `clamp()` method was running with a min > max, which caused an illegal argument error.
Now resolves document taps by finding the "nearest" document position, rather than the "exact" document position. This means that tapping anywhere within `SuperEditor` will place the caret, which is convenient for empty documents.
=> Handle empty documents (Resolves #274, Resolves #410)

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/default_editor/super_editor.dart
Bugfix: desktop auto-scrolling wouldn't stop after starting (Resolves #441)
There was an adjustment in the calculation that I was applying on every scroll frame. I'm not entirely sure why it was working originally, and then started failing. I might be missing some use-cases, but I removed the adjustment that I was applying to the user's drag position and it seemed to fix the problem.
=> Bugfix: desktop auto-scrolling wouldn't stop after starting (Resolves #441)

super_editor/example/lib/demos/editor_configs/demo_mobile_editing_android.dart, super_editor/example/lib/demos/editor_configs/demo_mobile_editing_ios.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_keyboard_actions.dart, super_editor/lib/src/infrastructure/_listenable_builder.dart, super_editor/lib/super_editor.dart
Updated demo app to automatically adapt to the underlying platform (Resolves #436)
Also, I moved cut, copy, and paste from the keyboard handlers and put them into the `CommonEditorOperations`, and then I used those operations in the demo apps to perform those operations.
=> Updated demo app to automatically adapt to the underlying platform (Resolves #436)

super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart
Fixes #455 
`keyboardHandlers` is currently not used in `SuperTextField` when it should be passed to `SuperDesktopTextField`.
=> Pass SuperTextField.keyboardHandlers to SuperDesktopTextField.keyboardHandlers

super_editor/pubspec.yaml
I think `composable` should be the correct word.
=> Fix typo `composable` in `pubspec.yaml`

super_editor/lib/src/default_editor/layout_single_column/_styler_user_selection.dart
Use SelectionStyles.caretColor instead of SelectionStyles.selectionColor for the caret color of a horizontal ruler.
Fixes #482
=> Fix caret color for horizontal ruler

super_editor/lib/src/default_editor/document_input_ime.dart
H2's were not being applied properly due to an incorrect boolean check in the document IME toolbar.
=> Bugfix: header2 wasn't being applied on mobile

super_editor/example/pubspec.yaml, super_editor/lib/src/default_editor/box_component.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/infrastructure/platforms/ios/selection_handles.dart, super_editor/lib/src/infrastructure/super_textfield/android/_caret.dart, super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart, super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart, super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_caret.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_floating_cursor.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_user_interaction.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart, super_editor/lib/super_editor.dart, super_editor/test/src/infrastructure/super_textfield/desktop/super_desktop_textfield_keyboard_test.dart
Trying to fix mono repo path issues. My previous rename of `super_selectable_text` to `super_text` seemed to work locally before the PR, but now it's broken on my machine. Hopefully this fixes it.
=> Trying to fix mono repo path issues

super_editor/lib/src/infrastructure/strings.dart, super_editor/test/src/infrastructure/strings_test.dart
This PR updates the `CharacterMovement` extension on `String` to fix some bugs and more closely match the behavior of other text editors.
Bugs:
- Currently only space is considered when checking for word breaks, causing the cursor to skip over whitespace created with other Unicode characters. This is fixed by using a regex to match on any characters in the Unicode "Separator" category [^1].
- Currently moving upstream by word does not handle multiple spaces well: it will step through one space at a time until it hits a space immediately after a non-space character, then jump to the beginning of the previous word. This is fixed by changing how previous spaces are counted and when the loop is broken in `moveOffsetUpstreamByWord`.
Behavior changes:
- Most other editors jump to the end of …
=> Improve navigating by word

attributed_text/CHANGELOG.md, attributed_text/LICENSE, attributed_text/pubspec.yaml
Preparing `attributed_text` for release by adding LICENSE and CHANGELOG
=> [attributed_text] - added LICENSE and CHANGELOG

super_editor/example/pubspec.yaml, super_editor/pubspec.yaml, super_editor_markdown/pubspec.yaml, super_text/pubspec.yaml
Added local dependency overrides to all packages in the repo to allow for local dev.
The problem we're solving is this:
1. We split super_editor into multiple packages in a mono-repo: attributed_text, super_text, super_text_markdown.
2. Pub.dev won't let us specify local path dependencies. Instead, for example, super_editor must depend upon a public version of super_text.
3. We need to develop against multiple packages at the same time. For example, we make a change to super_text and then we need to demo that change in super_editor. But super_editor is using the published version of super_text, not the local one.
By adding dependency overrides with local paths, developers can run each package against the other local packages during development, while we continue to satisfy pub.dev's …
=> Added local dependency overrides to all packages in the repo to allow for local dev

attributed_text/CHANGELOG.md, attributed_text/pubspec.yaml, super_text/pubspec.yaml
Switched `super_text` dependency on attributed_text from GitHub to Pub.dev
Also, this PR includes release 0.1.1 for `attributed_text` because apparently it was using a version of `collection` that's incompatible with Flutter, so I downgraded that dependency within `attributed_text`.
=> Switched super_text dependency on attributed_text from GitHub to Pub.dev

super_editor/example/lib/demos/demo_markdown_serialization.dart, super_editor_markdown/lib/src/markdown.dart, super_editor_markdown/test/super_editor_markdown_test.dart
Resolves #489 
Adds basic link support to markdown serialization. As implemented, links can completely overlap with other attributes, but a partial intersection will break the link into two, such as the following:
`*test [link* text](https://link.com)` would instead be serialized as `*test *[*link*](https://link.com)[ text](https://link.com)` 
I decided to put the PR up anyway with this behaviour since it's consistent(ly broken) with the other markdown styles, which would require a much more significant change to resolve and seemed out of scope of the original issue.
=> Add link support to markdown serialization

super_editor/example/lib/demos/example_editor/example_editor.dart
Fix default toolbar location when there are multiple editors on one screen (Resolves #486 )
When there are multiple editors on one screen, the toolbar in `example_editor.dart` is not displayed correctly, as other editors except the first editor shows the toolbar based on the position of the first editor. This PR fixes the above issue, as displayed below.
This PR does not affect the `super_editor` components, but rather gives the user a better default implementation in the example file.
The PR is created thanks to hillelcoren. 
MacOS:
=> fix toolbar location when there are multiple editors in one screen

super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
Moved all AttributedTextEditingController extension methods into the class, also exposed the 'innerController' from ImeTextEditingController because Superlist token behavior needs access to the inner controller.
=>  Updates for Superlist tokenization work

super_editor/lib/src/default_editor/document_gestures_touch.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/test/src/_document_test_tools.dart, super_editor/test/src/default_editor/auto_scroll_test.dart
Fix auto-scroll when Editor is in a CustomScrollView (Resolves #521 ), and fix scrolling when using Editor in a CustomScrollView with `gestureMode: DocumentGestureMode.android`
I reimplemented the scrolling trigger, which checks for content (which is a handle in this case) that is not visible within the viewport and its boundary. The scrolling could trigger either when the content is above or below the desired viewport, and it jumps to the position based on its trigger position, added with the current scroll offset.
Along the way, I found that the `_ancestorScrollPosition` is not set in `document_gesture_touch_android.dart`, compared to `document_gesture_touch_ios.dart`, which leads to errors when using in CustomScrollView. So I made the change accordingly.
iOS:
Android:
=> Fix Auto-scroll in CustomScrollView, and Android Editor in CustomScrollView (resolve #521)

super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/test/src/infrastructure/super_textfield/attributed_text_editing_controller_test.dart
`AttributedTextEditingController` was always removing all composing attributions when calling `removeComposingAttributions`, regardless of the `attributions` passed as arguments
(Resolves #540)
=> Fix removeComposingAttributions on AttributedTextEditingController (Resolves #540)

attributed_text/pubspec.yaml, super_editor/pubspec.yaml, super_editor_markdown/pubspec.yaml, super_text/pubspec.yaml
A bunch of packages in this repo currently have `flutter_lints: ^1.0.0` in their `dependencies`. This breaks version solving for any downstream packages that want to update to the new version `2.0.0` of `flutter_lints`:
```
Because rich_clipboard_example depends on super_editor_markdown from git which depends on flutter_lints ^1.0.0, flutter_lints ^1.0.0 is required.
So, because rich_clipboard_example depends on flutter_lints ^2.0.0, version solving failed.
```
This PR fixes the issue by moving all the `flutter_lints` dependencies in this repo to the `dev_dependencies` section. I intentionally didn't update `flutter_lints` to `^2.0.0` while I was at it because doing so produces enough analyzer warnings that it should be handled in a dedicated PR.
=> Moving flutter_lints to dev_dependencies in all relevant packages

super_editor_markdown/lib/src/markdown.dart, super_editor_markdown/test/super_editor_markdown_test.dart
Updates the markdown deserialization visitor with a new case to handle links.
=> Add link support to markdown deserialization

super_editor/test/src/default_editor/auto_scroll_test.dart, super_text/lib/src/caret.dart
Fix auto-scroll tests after flutter 3 upgrade (Resolves #555  ) 
After the flutter 3 upgrade, for some reason, the caret size is changed, thus getting the top offset added with known text size is no longer the bottom offset of the caret. 
Wrapping the caret with the SizedBox should make its `RenderBox` reports the size. This also removes the existing TODO.
Migrate the `textScaleFactorTestValue` API because the old one was deprecated.
=> Fix auto-scroll tests after flutter 3 upgrade (Resolves #555 )

super_text/CHANGELOG.md, super_text/lib/src/super_text.dart
Updated CHANGELOG and removed references to SuperSelectableText
I'm going to merge this without review because it only has minor non-code changes meant for package release.
=> Updated CHANGELOG and removed references to SuperSelectableText

super_editor/example/pubspec.yaml, super_editor/pubspec.yaml, super_text_layout/pubspec.yaml
Updating super_text_layout deps to use the new Pub version.
Now, `super_editor` uses the Pub version of `super_text_layout` for release.
I also reverted `super_text_layout` to use a dependency override for `attributed_text`, now that the `super_text_layout` Pub release is done.
=> Updating super_text_layout deps to use the new Pub version

attributed_text/pubspec.yaml, super_editor/pubspec.yaml, super_editor_markdown/pubspec.yaml, super_text_layout/pubspec.yaml
Upgraded all lints from 1.0.0 to 2.0.1, except super_editor_markdown because it causes a build failure until we release super_editor v0.2.1
=> Upgraded all lints from 1.0.0 to 2.0.1

super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart
This file used to be exported and was also being used in client code. It was probably removed during recent refactoring (splitting `super_text_layout`, etc.).
=> Export again `super_textfield/style.dart`

super_editor/lib/src/infrastructure/super_textfield/_test_tools.dart
Added a hack fix to _test_tools.dart for finding the offset to tap in a text field. Flutter is reporting -0.2 in the 'dy' instead of 0.0, which results in a tap outside the field.
=> Added a hack fix to _test_tools.dart for finding the offset to tap in a text field

super_editor/lib/src/default_editor/document_input_ime.dart, super_editor/test/src/default_editor/document_input_ime_test.dart, super_editor/test/src/default_editor/test_documents.dart
Fixed compound-character IME crash (Resolves #586)
The root problem was that we conditionally include invisible prepending characters, e.g., ". ", when editing an empty paragraph with content above it. We do this so that the IME reports backspace button presses, and still auto-capitalizes the first character of the paragraph. I describe in #586 why this became a problem.
This PR resolves the composing region mismatch that caused the crash, and also adds a test to prevent a regression.
https://user-images.githubusercontent.com/7259036/170907332-053c0e46-547e-4376-9779-02051eaadc0d.mov
=> Fixed compound-character IME crash (Resolves #586)

attributed_text/lib/src/attributed_spans.dart, attributed_text/pubspec.yaml, attributed_text/test/attributed_text_test.dart
Fixed span merge bug in addAttribution() (Resolves #582)
The problem was the case when an existing span ends exactly where a new span begins. The specific behavior in the `addAttribution()` method requires this situation to be handled explicitly, by removing the existing end marker. This PR does that.
This PR also renames `_attributions` to `markers` for clarity. And `markers` is public for testing verification.
=> Fixed span merge bug in addAttribution() (Resolves #582)

website/lib/homepage/featured_editor.dart, website/lib/homepage/home_page.dart, website/lib/homepage/inside_the_toolbox.dart, website/pubspec.lock, website/pubspec.yaml
Fix scrolling bug on the demo website. Resolves https://github.com/superlistapp/super_editor/issues/462
On the demo website, adding content vertically was causing the editor's content to overflow the available space and be drawn outside its bounds.
I've wrapped `FeaturedEditor` with a `SingleChildScrollView` so `SuperEditor` can scroll its content.
I've also updated the demo to use `SuperTextWithSelection` instead of `SuperSelectableText` because the build was failing.
=> Fix scrolling bug on demo website (Resolves #462)

super_editor/lib/super_editor.dart
Added composable_text.dart to exported APIs in super_editor.
I added this while working on magic ink. I think we should have always exported `TextComposable`, but now we need it so that we can create a custom version of `TextComponent` that supports magic ink.
=> Added composable_text.dart to exported APIs in super_editor

super_editor/lib/super_editor.dart
Exported string extensions from super_editor.
I'm adding this export while working on magic ink. We need to create a custom `TextComponent`, which internally relies on private string extensions that we created. External developers should be able to create `TextComponent` the same way we did internally, so now we're exporting those string extensions.
=> Exported string extensions from super_editor

super_editor/pubspec.yaml, super_editor/test/super_textfield/super_desktop_textfield_keyboard_test.dart
Moved clipboard simulation to the flutter_test_robots package.
I asked a member of the Flutter team if they had any plans to create a test representation of clipboard behavior and he said probably not. So I moved the temporary simulated clipboard behavior into `flutter_test_robots` to make it permanent, and publicly available.
=> Moved clipboard simulation to the flutter_test_robots package

super_text_layout/lib/src/infrastructure/blink_controller.dart, super_text_layout/test/blink_controller_test.dart
`BlinkController` was not calling `notifyListeners` when `stopBlinking` was called. Resolves https://github.com/superlistapp/super_editor/issues/523
As `_CaretPainter` uses its blinkController as a repaint `Listenable`, it's necessary to call `notifyListeners` to cause `_CaretPainter` to repaint.
I added tests to ensure both `stopBlinking` and `startBlinking` cause the listeners to be notified
=> Fix BlinkController not notifying its listeners when it stops blinking (Resolves #523)

super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart, super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart, super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_caret.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart, super_editor/test/src/infrastructure/_platform_test_tools.dart, super_editor/test/super_textfield/super_desktop_textfield_keyboard_test.dart, super_editor/test/super_textfield/super_desktop_textfield_text_layout_test.dart, super_editor/test/super_textfield/super_textfield_robot.dart, super_editor/test/super_textfield/super_textfield_text_layout_test.dart, super_editor/test/test_tools.dart, super_editor_markdown/pubspec.yaml, super_text_layout/example/lib/rainbow_character_supertext.dart, super_text_layout/lib/src/text_layout.dart, super_text_layout/test_goldens/super_text_layers_test.dart
Fix `SuperDesktopTextField` exception when rendering text containing only emojis. Resolves https://github.com/superlistapp/super_editor/issues/459
Trying to move the selection using the keyboard when `SuperDesktopTextField` has text containing only emojis causes the exception `Bad state: No element`. The issue occurs in Windows and Web
After some investigation this is what I've found:
https://github.com/superlistapp/super_editor/blob/ca24005782b21a8640f20a0b0ed3b2a5dd206f01/super_text_layout/lib/src/caret_layer.dart#L76-L81
When the text contains only emojis the line `widget.textLayout.getHeightForCaret(widget.position!)` returns null and `widget.textLayout.getLineHeightAtPosition(widget.position!)` is called , calling `getCharacterBox` on `RenderParagraphProseTextLayout`.
At …
=> Fix SuperDesktopTextField exception when rendering text containing only emojis (Resolves #459)

super_editor/pubspec.yaml, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/document_test_tools_test.dart, super_editor_markdown/CHANGELOG.md, super_editor_markdown/lib/src/markdown.dart, super_editor_markdown/pubspec.yaml, super_editor_markdown/test/super_editor_markdown_test.dart
Added ability to configure and verify documents using markdown syntax (Resolves #635)
Configuring custom documents within individual tests is very verbose, and typically makes tests more difficult to read, rather than easier. Similarly, verifying document content, especially text attributions, is very verbose and difficult to read.
This PR adds an API to configure a custom document using Markdown syntax. It also adds a custom matcher that verifies a document's content against provided Markdown text.
**Despite the addition of this behavior, any test that should rely on a document that's shared with many other tests, should continue to use the pre-configured documents. For example:** `tester.createDocument().withSingleEmptyParagraph()`.
To get this Markdown matching behavior to work without …
=> Added ability to configure and verify documents using markdown syntax (Resolves #635)

super_editor/lib/src/core/document_editor.dart, super_editor/test/src/core/document_editor_test.dart
We want to have a way of moving a `DocumentNode` to an arbitrary index in the list of nodes with just one `notifyListeners()` call happening. 
The end result can be achieved with `document..deleteNode()..insertNode()` calls. But we only want to get a notification of the document after a `DocumentNode` has been moved, not a "partial state" where a node has been removed, and then the "final state" where the node exists on the right place of the document. This can't be achieved currently with the existing APIs.
Since there's no `moveNode()` method available, this PR introduces just that.
=> Add .moveNode() to MutableDocument & DocumentEditorTransaction

super_editor/test/super_textfield/super_textfield_caret_test.dart, super_text_layout/lib/src/caret_layer.dart, super_text_layout/lib/src/infrastructure/blink_controller.dart
Add test for caret blinking while typing in SuperTextField. Resolves https://github.com/superlistapp/super_editor/issues/460
This issue was already solved with the introduction of `BlinkController`, so I tried to add a test to verify this behavior.
This test alone might not be enough to ensure the caret is solid while typing, because it does not check if `CaretPainter`  is repainting itself using the opacity from `BlinkController`. However, `BlinkController` has tests to ensure it notifies its listeners when it changes its visibility, so `CaretPainter` should be repainting.
I was able to simulate a failing test commenting the body of `jumpToOpaque`:
https://github.com/superlistapp/super_editor/blob/f7b0b5997c49253d1453d487ed6c5d7cb7d21f74/super_text_layout/lib/src/infrastructure/blink_cont …
=> Add test for caret blinking while typing in SuperTextField (Resolves #460)

super_editor/lib/src/default_editor/document_input_ime.dart
Fix ENTER key not working on web. Resolves https://github.com/superlistapp/super_editor/issues/587
I modified `_DocumentImeInteractorState` to behave the same way for Android and web when pressing new lines.
This PR doesn't have tests because we can't override `kIsWeb`
One option would be to use a getter like this to determine if we are on web:
```dart
bool get isWeb => debugIsWebOverride ?? kIsWeb;
```
=> Fix ENTER key not working on web (Resolves #587)

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_textfield/super_desktop_texfield_mouse_interaction_test.dart
Change SuperDesktopTextField to always use text cursor style. Resolves https://github.com/superlistapp/super_editor/issues/383
I removed both `ValueNotifier` and `ListenableBuilder` because the cursor style won't be changing anymore.
Tests were added to ensure the cursor style is `SystemMouseCursors.text` when hovering the text, empty space and padding.
=> Change SuperDesktopTextField to always use text cursor style (Resolves #383)

super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart, super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/test/super_textfield/super_textfield_caret_test.dart, super_editor/test/super_textfield/super_textfield_test.dart, super_text_layout/lib/src/caret_layer.dart
SuperTextField caret is visible when there's no selection (Resolves #649)
I noticed on my webpage that all my text fields showed a blinking cursor. I think this bug came in with the recent `super_text_layout` refactor.
I adjusted the conditions under which a caret is displayed, and I added tests to make sure this doesn't happen again.
=> SuperTextField caret is visible when there's no selection (Resolves #649)

super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_user_interaction.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart, super_editor/test/super_textfield/super_textfield_touch_interaction_test.dart, super_editor/test/test_tools.dart
Change SuperTextField to place caret at the end of the text when tapping empty space. Resolves https://github.com/superlistapp/super_editor/issues/654
Tapping a part of the field without any text was changing selection only when `SuperTextField` had no valid selection. 
It was working when there was no selection because we are forcing a selection when `SuperAndroidTextField` is focused:
https://github.com/superlistapp/super_editor/blob/6602da8767efbd08707f18768bccb4c5bf070280/super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart#L264-L272
This is also true for `SuperIOSTextField`
=> Change SuperTextField to place caret at the end of the text when tapping empty space (Resolves #654)

super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_test.dart
Fix SuperTextField newline not working on mobile. Resolves https://github.com/superlistapp/super_editor/issues/653
There were two issues:
* We were not configuring `textInputAction`  to `TextInputAction.newline`  when the textfield was configured for multi-line
* We were not configuring `textInputType` to `TextInputType.multiline` when the textfield was configured for multi-line
I couldn't write an ideal test because we can't simulate the behavior on the tests (on Android and web, clicking the action button will generate an insertion delta of a new line)
=> Fix SuperTextField newline not working on mobile and web (Resolves #653)

super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart
Fix space and arrow keys on web. Resolves https://github.com/superlistapp/super_editor/issues/659
This was also an issue on Flutter `TextField` on web: https://github.com/flutter/flutter/issues/74191
Unfortunately, to be able to test this we need to avoid using `kIsWeb` and using some getter that we could override.
If we do that, then we could write a test adding `Actions` and `Shortcuts` widgets above `SuperTextField` and inspecting if the action callback was called.
=> [SuperTextField] Fix space and arrow keys on web (Resolves #659)

super_editor/test/super_editor/supereditor_robot_test.dart
Expanded SuperEditorRobot tests to run on all platforms. Previously, the tests were running with `testWidgets`.
=> Expanded SuperEditorRobot tests to run on all platforms

super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_input_actions_test.dart
Make SuperTextField handle DONE action. Resolves https://github.com/superlistapp/super_editor/issues/661
Here I'm not sure if we should unfocus even if the widget has a `onPerformActionPressed` defined. I could change this if needed. 
```dart
void _onPerformActionPressed(TextInputAction action) {
if (action == TextInputAction.done) {
_focusNode.unfocus();
}
widget.onPerformActionPressed?.call(action);
}
```
Maybe we should expose `onPerformActionPressed` on `SuperTextField`'s public API to write a test to ensure it's beeing called.
=> Make SuperTextField handle DONE action (Resolves #661)

super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_user_interaction.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart
Force `SuperTextField` to show keyboard on tap. Resolves https://github.com/superlistapp/super_editor/issues/673
After tapping the field and closing the keyboard, tapping at the field again was not opening the keyboard.
I modified it to call `show()` on `TextInputConnection` if it's already focused and attached to ime.
=> Force SuperTextField to show keyboard on tap (Resolves #673)

super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_caret_test.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart, super_editor/test/super_textfield/super_textfield_test.dart
Removed the need to specify a lineHeight for multiline SuperTextField's (Resolves #622)
Historically, we've required that any multi-line `SuperTextField` provide an explicit line height in pixels. This is because styled text can produce varying line heights, and text scrolling currently scrolls by line, not by pixel. So how tall should a `SuperTextField` be if, for example, we have a 5 line field with different font sizes inside of it? Our answer was to make the developer choose a line height and then `SuperTextField` would multiply that value by the number of lines.
This is an annoying requirement. Even with an explicit line height, the result can be poor. The eventual answer is to offer pixel-based scrolling, when desired. But for now, this PR removes the need to pass a line height to …
=> Removed the need to specify a lineHeight for multiline SuperTextField's (Resolves #622)

super_editor/example/lib/main.dart, super_editor/lib/src/default_editor/layout_single_column/_styler_per_component.dart, super_editor/lib/src/default_editor/layout_single_column/_styler_user_selection.dart, super_editor/lib/src/infrastructure/_logging.dart
Separate styling logs from layout logs. Resolves https://github.com/superlistapp/super_editor/issues/648
All document styling logs were going to the layout logger. Added a `editorStyleLog`  and updated styling logs to go to this logger.
I assume there is no need to tests for this PR.
=> [SuperEditor] Separate styling logs from layout logs (Resolves #648)

super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart
Fix backspace not working on Android. Resolves https://github.com/superlistapp/super_editor/issues/506
Some third party keyboards report `backspace` as a key press rather than a deletion delta, so we need to handle this in `onKey`.
I handled `backspace` directly in `_onKeyPressed` because I was not sure if we need to handle multiple keyboard actions like in `SuperDesktopField`
=> [SuperTextField] [Android] Fix backspace not working on Android (Resolves #506)

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
Fixed mobile handle dragging with ancestor Scrollables (Resolves #525)
The root problem seems to be that we were using a `PanGestureRecognizer` but `Scrollable` uses a `VerticalDragGestureRecognizer`. I thought maybe our `PanGestureRecognizer`was losing out in the gesture arena. So I changed our recognizer to also be a `VerticalDragGestureRecognizer` and it now seems to beat out the ancestor `Scrollable`.
This ancestor gesture behavior is unintuitive. I would consider this to be a bug in Flutter. Nonetheless, I'm now able to easy drag the iOS caret around in the sliver demo.
=> Fixed mobile handle dragging with ancestor Scrollables (Resolves #525)

super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/test/super_textfield/attributed_text_editing_controller_test.dart
[SuperTextField] - fix word jumping for expanded selection, and add tests (Resolves #560)
- Fixed a word-jumping bug when selection is expanded
- Decomposed horizontal caret movement method to improve readability
- Added tests for word-jumping under various conditions.
=> [SuperTextField] - fix word jumping for expanded selection, and add tests (Resolves #560)

super_editor/test/super_editor/supereditor_gestures_test.dart
Add test for tapping to select an empty document. Resolves https://github.com/superlistapp/super_editor/issues/646
Tapping anywhere in a document with a single empty paragraph should give focus to the document and place caret at the beginning of the document.
=> Add test for tapping to select an empty document (Resolves #646)

super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/main.dart, super_text_layout/lib/src/super_text_layout_with_selection.dart
Fix toolbar hiding the alignment menu. Resolves https://github.com/superlistapp/super_editor/issues/670
Currently we use an `Overlay` to display the toolbar. This is causing the dropdown items to be displayed behind the toolbar.
After some research I found that `DropdownButton` displays its items in another route and that the overlay is always displayed above this route. Based on https://github.com/flutter/flutter/issues/22917#issuecomment-431457670 it seems that this is the expected behaviour.
I changed the example editor to display the toolbar in the stack.
Checking this ticket I've found another issue:
Clicking to change the text alignment is not applying the new alignment until an attribution is toggled. The reason is that `_RebuildOptimizedSuperTextWithSelectionState` is not …
=> [Example App] Fix toolbar hiding the alignment menu (Resolves #670)

super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/metrics.dart, super_editor/test/super_textfield/super_textfield_auto_scroll_test.dart
Auto-scroll when field is focused. Resolves #663
Giving focus to a `SuperTextField` inside a `Scrollable` was not causing it to auto-scroll. Because of this, the text field could be hidden by the keyboard.
I used the same approach that `SuperEditor` uses to auto-scroll its contents.
=> [SuperTextField] Auto-scroll when field is focused (Resolves #663)

super_editor/lib/src/default_editor/layout_single_column/_layout.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_selection_test.dart
[SuperEditor]  Fix drag selection of non-selectable components. Resolves https://github.com/superlistapp/super_editor/issues/363
Dragging a selection that ends on a non-selectable component was causing the component to be selected.
I modified `getDocumentSelectionInRegion` to ignore components that are marked with `isVisuallySelectable` equal to `false`. That way, a non-selectable component can't be at the `base` or `extent` of a `DocumentSelection`.
However, we still can select the surrounding components, causing the non-selectable component to be present in the selected region.
I also added an option to configure the `componentBuilders` in the `TestDocumentConfigurator`.
=> [SuperEditor] Fix drag selection of non-selectable components (Resolves #363)

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/default_editor/document_gestures_touch.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/document_scrollable.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_ancestor_scrollable_test.dart
[SuperEditor] Fix scrolling issue when the editor is inside a horizontal `Scrollable`. Resolves #501
When adding the editor to a `TabBarView`, once the screen is filled with text, the `TabBarView` automatically changes to the next tab rather than scroll down in the editor.
A similar issue happens when adding the editor inside a horizontal `ListView`, where adding text causes the `ListView` to scroll.
The problem is that when `SuperEditor` has an ancestor `Scrollable`, it doesn't create its own `SingleChildScrollView` and scrolls the ancestor `Scrollable` instead. Because of that, widgets that use a horizontal `Scrollable` are affected.
I changed it to ignore the ancestor `Scrollable` if it has a horizontal `AxisDirection`.
I also added an option in `TestDocumentConfigurator` to configure …
=> [SuperEditor] Fix scrolling issue when the editor is inside a horizontal Scrollable (Resolves #501)

super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/ime_input_owner.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/pubspec.yaml, super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart
Added tests for text entry on mobile using an IME simulator in flutter_test_robots (Resolves #620)
=> Added tests for text entry on mobile using an IME simulator in flutter_test_robots (Resolves #620)

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_textfield/super_texfield_scroll_test.dart, super_editor/test/super_textfield/super_textfield_text_layout_test.dart
[SuperTextField] [Desktop] Fix text behaving scrollable when maxLines is null. Resolves #566 
We use an estimated line height to calculate the `SuperTextFieldScrollview` viewport height.  Because of this, when the true line height is bigger than the estimated line height, the text is bigger than the viewport, which causes the scrolling behavior.
The root cause of https://github.com/superlistapp/super_editor/issues/565 is the same: when the text is empty, the estimated line height differs from the true line height.
I changed to use the true line height when it's available. However, this might cause the text field to change its height when the user starts typing. If there's a better solution to this I will update the PR.
There's already an open issue to calculate true line height: …
=> [SuperTextField] [Desktop] Fix text behaving scrollable when maxLines is null (Resolves #566)

super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/main.dart, super_editor/lib/src/core/document_layout.dart, super_editor/lib/src/default_editor/box_component.dart, super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/default_editor/document_input_ime.dart, super_editor/lib/src/default_editor/text.dart, super_editor/test/super_editor/supereditor_components_test.dart, super_editor/test/super_editor/supereditor_robot.dart
Fix hint component and example app toolbar focus (Resolves #726)
The hint component's hint text was absorbing gesture interactions, preventing the placement of the caret. Now it ignores the pointer. The tests for this behavior required a modification to our test tools so that we can place the caret in a component that wraps a text component, instead of just a text component.
I also changed the cursor within the editor to always look like a text cursor, unless the cursor is over a selectable box, at which point it looks like a regular cursor again.
Lastly, I did my best to fix the popover toolbar focus issue. By adding a `FocusScope` above our custom `Overlay` in the example app, the user can tap toolbar buttons like "bold" and "italics" without issue. However, the dropdowns are still …
=> Fix hint component and example app toolbar focus (Resolves #726)

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_textfield/super_textfield_estimated_line_height_test.dart
[SuperTextField] [Desktop] Fix hint text cutting off. Resolves #565
SuperTextField calculates its viewport height based on an estimated line height. This estimation may differ from the true line height. This difference can cause the hint text to be cut off, because the text field may not have enough room to display it.
The line height is calculated using the text layout `getLineHeightAtPosition` when it's available, so when there is text the field should have the correct height.
This PR changes the line height estimation to be calculated by laying out a `Paragraph` with a single arbitrary character and inspecting its line metrics.
=> [SuperTextField] [Desktop] Fix hint text cutting off (Resolves #565)

super_editor/example/lib/main.dart
A missing import in `super_editor/example/lib/main.dart` is causing the example app to fail to compile. This PR just adds the import back in. It looks like the import was removed as part of [this commit][1].
[1]: https://github.com/superlistapp/super_editor/commit/574bc21770a50d41fb48788aa7ea2df995723d26#diff-87261c6ba97adf363861c4f7733e9ff6edbd7cf8732724357ec0e8a8dc22b1bfL21
=> Fixing super_editor/example compilation by adding missing import

super_editor/lib/src/default_editor/document_caret_overlay.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/document_selection_on_focus_mixin.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_selection_test.dart
[SuperEditor] Fix caret display on focus. Resolves #722 
Creating a `SuperEditor` with autofocus set to `true` and with an initial selection wasn't displaying the caret, even though the document has a selection.
This PR changes the caret overlay and touch interactors to call `_onSelectionChange`, so the caret position is updated. It also updates the selection tests to ensure the caret is being displayed.
During manual tests I've found a situation happening only on desktop: when the editor has autofocus, by the time we get to `initState`, the focus node already has focus, so the `DocumentSelectionOnFocusMixin` isn't placing the selection at the end of the document. This PR adds a fix to this case by calling `_onFocusChange` in the mixin if we were given a focus node which already has …
=> [SuperEditor] Fix caret display on focus (Resolves #722)

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_text_layout/lib/src/super_text.dart
[SuperTextField] [Desktop] Fix exception when hot reloading. Resolves #763
When there's a `SuperDesktopTexField ` being rendered and the developer hot reloads the app, an exception is thrown.
This was caused by https://github.com/superlistapp/super_editor/pull/707. 
That PR changed `SuperDesktopTexField` to measure the text using its `textLayout`. However, after hot reloading, the text layout might be null.
This PR changes how text layout is being accessed in `_getEstimatedLineHeight` to a way in which we can check for null.
=> [SuperTextField] [Desktop] Fix exception when hot reloading (Resolves #763)

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
[SuperTextField] [Desktop] Fix line height estimation on macOS.  Resolves #764 
In macOS, estimating the line height when the font height is different from 1.0 using `computeLineMetrics` returns a value that doesn't seem to include the `descent`. As a result, letters like `p` and `g` are cut on the hint text.
This PR changes the line height estimation to use the `paragraph` height as the estimated line height.
=> [SuperTextField] [Desktop] Fix line height estimation on macOS (Resolves #764)

attributed_text/lib/src/attributed_spans.dart, attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_spans_test.dart, attributed_text/test/attributed_text_test.dart
[AttributedText] Add method to get the attributed range for a set of attributions. Resolves https://github.com/superlistapp/super_editor/issues/590
This PR adds a method to return the span range that's attributed around an offset.
For example:
`He**ll~o Wor**ld~` 
Calling this method with the offset of "W" and the attributions `bold` and `strikethrough` will return the range of "o Wor".
I made `getStartingMarkerAtOrBefore` and `getEndingMarkerAtOrAfter` public to avoid duplicating the code.
=> [AttributedText] Add method to get the attributed range for a set of attributions. (Resolves #590)

super_editor_markdown/lib/src/markdown.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[super_editor_markdown] Fix serialization of text alignment, strikethrough, and underline. Resolves #717
Strikethrough 
---
Strikethrough is being ignored during deserialization. The markdown package used for deserialization already supports the strikethrough syntax, however, it isn't enabled by default.
This PR enables the strikethrough syntax for deserialization.
Underline
---
Underline is being ignored in both serialization and deserialization. The markdown spec doesn't have a syntax for underline text. Some parsers allow the usage of a `ins` tag to specify the underline, however, we'd like to avoid using HTML, so a custom notation is needed.
This PR introduces a custom notation for underline:
```
This is ¬underline¬.
```
The `¬` character could be changed if a more appropriate one is …
=> [super_editor_markdown] Fix serialization of text alignment, strikethrough and underline (Resolves #717)

super_editor/lib/src/default_editor/blockquote.dart
Fixes #769
I just started to dabble into Flutter and the gesture stuff is a little over my head, but I think if I understand correctly, to fix this issue we just need to ignore the pointer events here
=> Allow blockquote mouse gestures by ignoring pointer events on container

super_editor/example/lib/demos/example_editor/example_editor.dart
[SuperEditor] [DemoApp] Fix incorrect request focus. Resolves #775 
The demo app is always requesting focus to the editor when `_hideEditorToolbar` is called. This is done probably due to reasons explained in https://github.com/superlistapp/super_editor/issues/731
If another focusable widget is placed in the same widget tree, then the editor never releases focus. When taping another focusable widget the following happens:
1. Focus is removed from the editor, which closes the IME connection.
2. Closing the IME connection clears the selection.
3. Changing selection causes  `_hideEditorToolbar` to be called, which requests focus to the editor again.
c866122e52b22c995630d673c2af8258722e04ec changed `SuperEditor` to restore the selection when the editor receives focus, so we are in a loop of …
=> [SuperEditor] [DemoApp] Fix incorrect request focus (Resolves #775)

super_editor/test/super_editor/document_test_tools_test.dart, super_editor/test/super_editor/supereditor_component_selection_test.dart, super_editor_markdown/lib/src/markdown.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[SuperEditor] Fix serialization/deserialization of empty paragraphs. Resolves #710
The markdown spec doesn't describe how to represent empty paragraphs, so multiple blank lines between paragraphs are ignored. However, we don't want to delete empty paragraphs when serializing/deserializing.
This PR changes the deserialization logic so that when we get two consecutive blank lines, the second one is considered an empty paragraph.
Also, SuperEditor doesn't add blank lines after paragraphs. This causes problems when deserializing some blocks.  For example:
A document containing one paragraph and one horizontal rule is serialized as
```
Paragraph
---
```
When this markdown is deserialized, it's interpreted as a setext-style header and we lose the horizontal rule.
This PR changes the paragraph …
=> [SuperEditor] Fix serialization/deserialization of empty paragraphs (Resolves #710)

super_editor/lib/src/default_editor/document_caret_overlay.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/src/default_editor/list_items_test.dart
[SuperEditor] Fix caret misplaced when indenting a list item. Resolves #777
When indenting or unindenting a list item via keyboard (pressing tab/backspace) the node gets indented but the caret remains in the old position, as seen in the video: 
https://user-images.githubusercontent.com/31278849/189396028-a9233274-6be3-47a5-ad53-4bd587d3768e.mov
The issue happens because `CaretDocumentOverlay` isn't being notified that something changed, as it only listens for selection changes.
This PR changes `CaretDocumentOverlay` to update the caret on all document changes.
=> [SuperEditor] Fix caret misplaced when indenting a list item (Resolves #777)

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart
[SuperEditor] [Desktop] Fix trackpad scrolling. Partially resolves #771 
After Flutter 3.3, dragging with two fingers on a trackpad triggers a pan gesture with a `kind` of `PointerDeviceKind.trackpad`, as documented [in this design doc](https://flutter.dev/go/trackpad-gestures). 
This change causes the editor to expand the selection instead of scrolling the document with this gesture.
This PR changes `DocumentMouseInteractor` to scroll the document instead of expanding selection when the drag device is a `PointerDeviceKind.trackpad`.
This PR is based on https://github.com/superlistapp/super_editor/pull/772.
=> [SuperEditor] [Desktop] Fix trackpad scrolling (Resolves #771)

super_editor_markdown/lib/src/markdown.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[super_editor_markdown] Fix deserialization of empty markdown. Resolves #779
Parsing empty markdown results in a document with an empty list of nodes. For the user to be able to interact with the editor, at least one node is required. So, after parsing the empty markdown, the user can't tap the editor and start typing.
This PR changes the markdown parsing to return a document containing an empty paragraph if no nodes were parsed.
=> [super_editor_markdown] Fix deserialization of empty markdown (Resolves #779)

super_editor/lib/src/default_editor/document_input_ime.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart
[SuperEditor] [iOS] Fix list indentation using TAB key. Resolves #745 
Pressing the TAB button on the iOS software keyboard isn't indenting list items. The tabs are reported as an insertion delta of `\t` and being inserted as text.
This PR changes the IME handler to trigger the list indentation command when a `\t` is received.
I tested some android tablet simulators and none of them have the tab key, so this command is only triggered on iOS.
=> [SuperEditor] [iOS] Fix list indentation using TAB key (Resolves #745)

super_editor/lib/src/default_editor/layout_single_column/_layout.dart, super_editor/test/super_editor/supereditor_gestures_test.dart
[SuperEditor] Fix selection when tapping beyond end of content. Resolves #744
Tapping at the empty space after the content in `SuperEditor` is placing the caret at the horizontal position where the tap happened.
This PR changes `SuperEditor` to place the caret at the end of the document when a tap happens beyond the end of the content.
=> [SuperEditor] Fix selection when tapping beyond end of content (Resolves #744)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
[SuperEditor] Fix crash after changing the gesture mode. Resolves #742
When `SuperEditor` has focus, if we change the gesture mode and hot reload it crashes the app.
The crash is happening because, when we change the gesture mode and hot reload, the `initState` of the new gesture interactor is called while the app `Overlay` is being built, so we can't show the editing controls overlay in the same frame.
This PR changes the mobile interactors to show the editing controls overlay in a post frame callback.
Also, the iOS interactor is adding a listener to the scroll position during the `build` method. In the first build of the interactor after the gesture mode change, the `ScrollController` seems to be also attached to the old interactor, which also crashes the app.  I'm not sure why we are …
=> [SuperEditor] Fix crash after changing the gesture mode (Resolves #742)

super_editor/example/lib/demos/demo_document_loses_focus.dart, super_editor/example/lib/demos/editor_configs/demo_mobile_editing_android.dart, super_editor/example/lib/demos/editor_configs/demo_mobile_editing_ios.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/main.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_selection_on_focus_mixin.dart, super_editor/lib/src/default_editor/layout_single_column/_styler_per_component.dart, super_editor/lib/src/default_editor/layout_single_column/_styler_user_selection.dart, super_editor/test/super_editor/supereditor_selection_test.dart
I audited the example app looking for issues after upgrading to Flutter 3.3.x.
I found some scrolling issues that seem to be caused by Flutter 3.3.x and I filed an issue or two with Flutter. I don't think there's anything we can do until Flutter addresses those issues.
I found that https://github.com/flutter/flutter/issues/111425 seems to be impacting our I-beam text cursor throughout SuperEditor. That's also outside our control.
There didn't seem to be any Flutter changes in 3.3.x that caused problems in SuperEditor that we can fix, but I did find and fix some pre-existing issues. Those fixes are in this PR.
=> Fix issues found when auditing example app with Flutter 3.3.x

super_editor/lib/src/default_editor/list_items.dart, super_editor/test/src/default_editor/list_items_test.dart, super_editor/test/super_editor/document_test_tools.dart
[SuperEditor] Fix list item style when converting to paragraph and back again. Resolves #795 
Converting a list item to a paragraph and back again wasn't respecting the styles for a list item.
The cause is that only the `ListItemNode` named constructors are setting the `blockType` metadata to `listItem`, and `ConvertParagraphToListItemCommand` uses the unnamed constructor. 
As the `StyleRule` for the list items uses a `listItem` block selector, this rule isn't picked.
Deserializing from markdown might also be affected, as it also uses the unnamed constructor.
This PR changes `ListItemNode` unnamed constructor to set the `blockType` if it isn't set.
=> [SuperEditor] Fix list item style when converting to paragraph and back again (Resolves #795)

super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart, super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_user_interaction.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart, super_editor/test/super_textfield/super_textfield_test.dart
[SuperTextField] Expose padding property. Resolves #588 
Currently `SuperDesktopTextField` exposes a `padding` property, but `SuperTextField` don't.
This PR exposes the  `padding` property at `SuperTextField` public API and implements padding support in `SuperAndroidTextField` and `SuperIOSTextField`.
=> [SuperTextField] Expose padding property (Resolves #588)

super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart
[SuperEditor] Fix default input source. Resolves #740
SuperEditor is using `keyboard` as its default `inputSource`.
This PR removes the default `inputSource` and changes the editor to choose the input source based on the platform if the editor's `inputSource` isn't configured.
=> [SuperEditor] Fix default input source (Resolves #740)

super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart, super_editor/test/super_textfield/super_textfield_test.dart
[SuperTextField] [Mobile] Fix viewport height when text changes. Resolves #794 
On mobile, changing the text isn't causing the text field to recalculate its viewport height. 
For example:  when adding new lines in a multi-line text field with `maxLines != null`,  the text field maintains the same height calculated for its initial text.
This PR changes the `TextScrollView` used by the mobile text fields to recalculate its viewport height when text changes.
=> [SuperTextField] [Mobile] Fix viewport height when text changes (Resolves #794)

super_editor/pubspec.yaml
Upgrade super_editor's super_text_layout dependency to v0.1.4
I released `super_text_layout` v0.1.4, which includes a fix to a null pointer exception.
=> Upgrade super_editor's super_text_layout dependency to v0.1.4

super_editor/example/lib/main.dart
[ExampleApp] Fix AppBar gestures. Resolves #811
In the demo app, there is a transparent `AppBar` and the editor is displayed behind it. This blocks gestures at the `AppBar`'s area.  For example: double-clicking at the top of the image doesn't select it. Also when deleting all the content and typing a paragraph, it isn't possible to select the first line.
This PR removes the `AppBar` and adds the `IconButton` directly on a `Stack`.
Before:
https://user-images.githubusercontent.com/7597082/195227076-c1ff86a5-7f87-428f-afae-d7d602ce7870.mp4
After:
https://user-images.githubusercontent.com/7597082/195227132-d85aa30d-994e-4df1-8863-64d53507aa98.mp4
=> [ExampleApp] Fix AppBar gestures (Resolves #811)

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/default_editor/document_scrollable.dart
Flutter 3.3.3 broke desktop scrolling. The listener widget no longer includes scrolling momentum in the pointer signal. As a result, we now need to implement momentum, and cancel the momentum at the appropriate time.
This PR was guided by comments in https://github.com/flutter/flutter/issues/112880
=> Fixed desktop scroll momentum that was broken by Flutter 3.3.3 (Resolves #806)

super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_floating_cursor.dart
[SuperEditor] [SuperTextField] Change floating cursor color opacity. Resolves #753
Both `SuperEditor` and `SuperTextField` use `Colors.red` as the floating cursor color on iOS.
This PR changes them to use 75% opacity.
=> [SuperEditor] [SuperTextField] Change floating cursor color opacity (Resolves #753)

super_editor/lib/super_editor.dart
`super_editor` exports mobile handle widgets, but doesn't export the `HandleType`, which is required to use those handle widgets. This PR exports `HandleType`.
=> Export touch_controls.dart

super_editor/example/macos/Podfile.lock, super_editor/example/pubspec.lock, super_editor_markdown/lib/src/document_to_markdown_serializer.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/lib/src/super_editor_syntax.dart, super_editor_markdown/lib/super_editor_markdown.dart, super_editor_markdown/test/attributed_text_markdown_test.dart, super_editor_markdown/test/custom_block_parser_test.dart, super_editor_markdown/test/custom_block_serializer_test.dart, super_editor_markdown/test/custom_parsers/callout_block.dart, super_editor_markdown/test/custom_parsers/upsell_block.dart
Added support for custom Markdown block syntaxes (Resolves #829)
I also refactored the source code to accomplish a couple things:
- Separated serialization and deserialization because they're mostly independent, and it's easier to read them when separated
- Converted serialization to use a list of serializer objects, instead of hard-coding all the supported nodes in the global serializer
=> Added support for custom Markdown block syntaxes (Resolves #829)

super_editor/example/lib/demos/debugging/simple_deltas_input.dart, super_editor/example/lib/demos/flutter_features/textinputclient/barebones_ios_text_input_client.dart, super_editor/example/lib/demos/flutter_features/textinputclient/basic_text_input_client.dart, super_editor/lib/src/default_editor/document_input_ime.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
[SuperEditor] Change `TextInputClient` implementations to use it as a mixin. Resolves #840
`TextInputClient` was changed to be a mixin. That way, we can use it with the `with` keyword to inherit the default implementations and avoid breaking the build when new methods with default implementations are added.
This PR changes the places where we implemented `DeltaTextInputClient` and `TextInputClient` to use them with the `with` keyword.
=> [SuperEditor] Change TextInputClient implementations to use it as a mixin (Resolves #840)

super_editor/example/lib/demos/example_editor/_task.dart, super_editor/lib/src/core/document.dart, super_editor/lib/src/core/document_editor.dart, super_editor/lib/src/core/document_selection.dart, super_editor/lib/src/core/styles.dart, super_editor/lib/src/default_editor/blockquote.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_input_ime.dart, super_editor/lib/src/default_editor/layout_single_column/_layout.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/default_editor/text.dart, super_editor/test/src/default_editor/text_test.dart, super_editor/test/super_editor/mutable_document_test.dart, super_editor/test/super_editor/supereditor_style_test.dart, super_editor_markdown/lib/src/document_to_markdown_serializer.dart
[SuperEditor] Fix typing lag in large documents. Resolves #751
There is a lag when typing in a document with hundreds of nodes.
This PR is based on the investigation of @jmatth  and @Jei-sKappa.
Some analysis after testing with the Frankenstein document posted by @jmatth  (added as a gist [here](https://gist.github.com/angelosilvestre/cbec8875a67f1b916fcbe09dcbfb06d7)):
* `getNodeIndex` takes some hundred microseconds to complete. It basically walks the entire list of nodes doing a deep comparison. Typing a single letter causes `getNodeIndex` to be called more than 3000 times. This function is called by  `getNodeBefore` , `getNodeAfter` and others.
* `getNodeById` takes some microseconds, but far less than `getNodeIndex`.
* `ParagraphComponentViewModel.==` is broken. Checking …
=> [SuperEditor] Fix typing lag in large documents (Resolves #751)

attributed_text/lib/src/attributed_spans.dart
[SuperEditor] Fix bad state when pasting content. Resolves #841
In the example app, adding some new lines and then copying and pasting throws the exception: `Bad state: No element`
This was caused because in the `collapseSpans` we got a span end marker with an offset greater than the content length.
This is caused because when looking for links on the pasted text we are always checking the first line. I'm not sure why we are doing this.
https://github.com/superlistapp/super_editor/blob/47d2b4a492aca04b69274871a8880394821b18e8/super_editor/lib/src/default_editor/common_editor_operations.dart#L2349-L2357
=> [SuperEditor] Fix bad state when pasting content (Resolves #841)

super_editor/dart_test.yaml
=> Added dart_test.yaml to silence meaningless test warnings about golden tags (#854)

super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/test/super_textfield/super_textfield_test.dart
[SuperTextField] Fix selection and input when initializing with a focused FocusNode. Resolves #843
When `SuperTextField` replaces another widget using an already focused `FocusNode` it doesn't show the caret and connect to IME.
This PR adds a post-frame callback to update selection/IME connection.
We already have a test which gives a focused `FocusNode` to the textfield  but, apparently, the issue only happens if the `FocusNode` was previously used.
https://github.com/superlistapp/super_editor/blob/47d2b4a492aca04b69274871a8880394821b18e8/super_editor/test/super_textfield/super_textfield_test.dart#L172-L183
This PR is based on https://github.com/superlistapp/super_editor/pull/843
=> [SuperTextField] Fix selection and input when initializing with a focused FocusNode (Resolves #843)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_input_ime.dart, super_editor/lib/src/infrastructure/_listenable_builder.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_floating_cursor.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
In https://github.com/flutter/flutter/pull/116543, the Flutter team is planning to add a new `ListenableBuilder` widget that has an identical implementation to `AnimatedBuilder`. Unfortunately, this conflicts with SuperEditor's widget of the same name.
They're virtually identical, but SuperEditor's uses a `WidgetBuilder` callback instead of a `TransitionBuilder`, which has an additional nullable `child` widget argument for performance reasons.
This PR converts SuperEditor's `ListenableBuilder` to use a `TransitionBuilder`, and updates all of the call sites where it is used. In addition, to avoid lint warnings, I added a `hide ListenableBuilder` to the Flutter material library import in each of the files that use it.
Once the Flutter change lands, SuperEditor's `ListenableBuilder` can be …
=> Hide Flutter's ListenableBuilder temporarily

super_editor/pubspec.yaml, super_editor/test/test_tools.dart
[SuperEditor] Annotate custom test methods
In VS Code, test methods and test groups are decorated with Run/Debug buttons, so users can easily run or debug a single test. Currently, for our custom test methods (`testWidgetsOnDesktop`, `testWidgetsOnMobile`, and others), these buttons are not displayed.
This PR annotates the custom test methods with `@isTestGroup` and `@isTest`, so VS Code displays the buttons as expected.
=> [SuperEditor] Annotate custom test methods

super_editor/lib/src/default_editor/document_input_ime.dart, super_editor/pubspec.yaml, super_editor/test/super_editor/supereditor_selection_test.dart
[SuperEditor] Handle software keyboard gestures. Resolves #817
Some Android software keyboards, like GBoard, have some gestures:
* Swiping over the spacebar to change the selection.
* Swiping from right to left over the backspace key to delete a word.
The spacebar gesture generates a non-text delta and the backspace gesture generates a non-text delta to select the word followed by a deletion delta.
Currently, we don't perform any action when we receive a `TextEditingDeltaNonTextUpdate`, so these gestures don't work.
This PR changes the delta handling to change the document selection when we receive a `TextEditingDeltaNonTextUpdate`. This change use a pre-existing method to convert the selection from the delta to a `DocumentSelection`.
After the changes: …
=> [SuperEditor] Handle software keyboard gestures (Resolves #817)

super_text_layout/lib/src/super_text.dart
We need to get intrinsic size or dry layout for `SuperTextField` but it's not currently possible because of unimplemented methods in `RenderSuperTextLayout`.
=> Implement missing layout methods for RenderSuperTextLayout

super_editor/lib/src/default_editor/document_input_ime.dart, super_editor/pubspec.yaml, super_editor/test/super_editor/supereditor_selection_test.dart
This PR cherry-picks "[SuperEditor] Handle software keyboard gestures (Resolves #817) (#877)" to stable
=> Cherry-pick "[SuperEditor] Handle software keyboard gestures (Resolves #817) (#877)" to stable

super_text_layout/lib/src/super_text.dart
This PR cherry-picks "Implement missing layout methods for RenderSuperTextLayout ([#886](https://github.com/superlistapp/super_editor/pull/886))" to stable.
=> Cherry-pick "Implement missing layout methods for RenderSuperTextLayout (#886)] to stable

super_editor/example/lib/demos/supertextfield/android/demo_superandroidtextfield.dart, super_editor/example/lib/demos/supertextfield/ios/demo_superiostextfield.dart, super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_caret_test.dart
[SuperTextField] Expose `caretStyle` property. Resolves #884
Currently, the caret customization is different between platforms:
* On desktop, a `CaretStyle` property is exposed, which configures color, width and border radius.
* On mobile, a `caretColor` property is exposed. The width and the border radius are the defaults defined in `CaretStyle` and can't be changed.
In `SuperTextField`'s public API, we only expose a `controlsColor` property, which defines the color for the caret and for the drag handles.
This PR adds an optional `caretStyle` property to `SuperTextField`. `SuperAndroidTextField` and `SuperIOSTextField` were changed to also accept a `CaretStyle`. 
IMO, we should deprecate the `caretColor` property in `SuperAndroidTextField` and `SuperIOSTextField` in favor of the new …
=> [SuperTextField] Expose caretStyle property (Resolves #884)

super_editor/example/pubspec.lock, super_editor/example/pubspec.yaml
Part of https://github.com/flutter/flutter/issues/117163, an attempt to roll package:intl was blocked by the super_editor customer tests failing to resolve pub get. Widening the constraint to `any` will ensure that future rolls will not require an upstream PR to super_editor (to resolve dependencies, the super_editor example would be forced to use the exact pin from the Flutter SDK anyway).
=> widen intl constraint

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart
[SuperEditor] Avoid scrolling when dragging over an image (Resolves #812)
When dragging over an image, the editor scrolls to display the whole image.
This PR changes the mouse interactor to avoid scrolling when the selection extent is an `ImageNode`.
The downside is that when a user changes the selection manually, it won't scroll also.
We could also extract the `_FakeImageComponentBuilder` to a shared file where we could reuse it.
=> [SuperEditor] Avoid scrolling when dragging over an image (Resolves #812)

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart
This PR cherry-picks  "[SuperEditor] Avoid scrolling when dragging over an image (Resolves #812) (#866)" to stable.
=> Cherry-pick "[SuperEditor] Avoid scrolling when dragging over an image (Resolves #812) (#866)" to stable

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/super_textfield_test.dart
This PR cherry-picks "[SuperTextField] Add ability to specify the software keyboard appearance (Resolves #897) (#899)" to stable
=> Cherry-pick "[SuperTextField] Add ability to specify the software keyboard appearance (Resolves #897) (#899)" to stable

super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/lib/src/infrastructure/platforms/mobile_documents.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/lib/src/super_reader/super_reader.dart
[SuperEditor][DemoApp] Fix toolbar dismissal on copy. Resolves #818 
Currently, tapping on the copy button doesn't close the toolbar. Tapping on cut or paste closes it, but this is incidental, the toolbar is closed because the document changes and the touch interactors hide the toolbar when this happens. 
It isn't possible for a package user to control the visibility of the toolbar. The toolbar is controlled by `AndroidDocumentGestureEditingController` and `IosDocumentGestureEditingController`, which aren't exposed in the public API. These controllers are created inside the touch interactors and can't be created elsewhere, as they hold `LayerLink's` to position the toolbar.
Both `AndroidDocumentGestureEditingController` and `IosDocumentGestureEditingController` extends …
=> [SuperEditor][DemoApp] Fix toolbar dismissal on copy (Resolves #818)

super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/lib/src/infrastructure/platforms/mobile_documents.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/lib/src/super_reader/super_reader.dart
This PR cherry-picks "[SuperEditor][DemoApp] Fix toolbar dismissal on copy (Resolves #818) (#867)" to stable
=> Cherry-pick "[SuperEditor][DemoApp] Fix toolbar dismissal on copy (Resolves #818) (#867)" to stable

super_editor/lib/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart, super_editor/test/test_tools_ime.dart
Fixed SuperTextField selection glitch by never resending the previous TextEditingValue to the IME (Resolves #905)
=> Fixed SuperTextField selection glitch by never resending the previous TextEditingValue to the IME (Resolves #905)

super_editor/lib/src/default_editor/document_ime/ime_decoration.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/src/default_editor/document_input_ime_test.dart, super_editor/test/super_editor/document_test_tools.dart
Bring back performAction control to SuperEditor widget (Resolves #915)
In a recent PR I removed the `softwareKeyboardHandler` from `SuperEditor` because it conflicted with the new IME API, and I couldn't remember why it was needed.
That handler was used by clients that needed to intercept and respond to IME `performAction` calls.
This PR introduces the concept of an IME client override, which gets first priority to respond to IME calls.
To use the new override, do the following:
```dart
class MyImeOverride extends DeltaTextInputClientDecorator {
@override
void performAction(TextInputAction action) {
if (weCareAboutThis) {
doSomething();
} else {
super.performAction(action);
}
}
}
// Wherever you build SuperEditor:
Widget build(BuildContext context) {
return SuperEditor(
// normal params …
```
=> Bring back performAction control to SuperEditor widget (Resolves #915)

super_editor/lib/src/default_editor/document_ime/ime_decoration.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/src/default_editor/document_input_ime_test.dart, super_editor/test/super_editor/document_test_tools.dart
Cherry pick: Bring back performAction control to SuperEditor widget (Resolves #915) (#916)
=> Bring back performAction control to SuperEditor widget (Resolves #915) (#916)

super_editor/lib/src/default_editor/document_ime/document_serialization.dart, super_editor/test/src/default_editor/document_input_ime_test.dart
[SuperEditor][mac] Fix upstream selection using keyboard. Resolves #913 
Trying to expand the selection upstream using shift + up or shift + left arrow is causing the selection to be collapsed.
This was introduced in https://github.com/superlistapp/super_editor/pull/877 when non-text delta handling was implemented.
In macOS, after we send our text editing value, we always get back a non-text delta. When we convert a `DocumentSelection` to a `TextSelection` to be sent to IME, we are inverting the selection `base` and `extent`, if we have an upstream selection. We send it to the IME and we get back a non-text delta with a downstream selection. This causes the bug.
This PR changes the `DocumentImeSerializer` to always use the same `base`, `extent`, and `affinity` from the selection.
I tested …
=> [SuperEditor][mac] Fix upstream selection using keyboard (Resolves #913)

super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart, super_editor/test/super_textfield/super_textfield_test.dart
In order to modify the virtual keyboard action on Mobile, `TextInputAction` needs to be exposed and configurable.
At Superlist mobile we have a multiline SuperTextField, but pressing enter on the virtual keyboard should not add a line break but be done instead. This is not possible because TextInputAction currently depends only on maxLines.
=> [SuperTextField][Mobile] Expose TextInputAction

super_editor/lib/src/default_editor/document_ime/document_serialization.dart, super_editor/test/src/default_editor/document_input_ime_test.dart
This PR cherry-picks "[SuperEditor][mac] Fix upstream selection using keyboard (Resolves #913) (#918)" to stable
=> Cherry-pick "[SuperEditor][mac] Fix upstream selection using keyboard (Resolves #913) (#918)" to stable

super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart
This PR cherry-picks "[SuperTextField] Fix selection glitch when using IME (Resolves #905) #919" to stable
=> Cherry-pick "[SuperTextField] Fix selection glitch when using IME (Resolves #905) #919" to stable

super_editor/example/lib/demos/example_editor/_example_document.dart, super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/main.dart, super_editor/lib/src/core/document_layout.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/lib/src/test/super_editor_test/tasks_test_tools.dart, super_editor/lib/super_editor.dart, super_editor/test/super_editor/components/task_test.dart
Moved tasks into Super Editor and fixed bug that prevented creating new tasks after texisting tasks (Resolves #923)
At some point we lost the ability to press ENTER at the end of a task in the example app and create a new task. This PR fixes that. I'm not sure how it was ever working. We have code in the ENTER handler that rejects any text node that isn't a `ParagraphNode`. I added a new key handler that specifically handles this case.
This PR also moves tasks into Super Editor as a standard content type. I also added tests to ensure that `TaskNode`s and `TaskComponent`s do the right thing within a `SuperEditor`.
I tried adding tests for tapping the checkbox. Those tests work on desktop, but not on mobile. At least part of the problem on mobile is that the mobile gesture recognizer still …
=> Moved tasks into Super Editor and fixed bug that prevented creating new tasks after texisting tasks (Resolves #923)

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
Added newline key handler to IME SuperTextField to fix example app URL field issue (Resolves #925)
=> Added newline key handler to IME SuperTextField to fix example app URL field issue (Resolves #925)

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart
Cherry pick: Added newline key handler to IME SuperTextField to fix example app URL field issue (Resolves #925) (#931)
=> Added newline key handler to IME SuperTextField to fix example app URL field issue (Resolves #925) (#931)

super_editor/example/lib/demos/demo_document_loses_focus.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/lib/src/default_editor/debug_visualization.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/super_editor.dart
Added focus and IME debug visuals to Super Editor (Resolves #942)
Focus is visualized with a colored border. Green for primary, red for non-primary, and gray for no focus.
IME is visualized with a little billboard at the top center. Could be "ATTACHED TO IME", "DETACHED FROM IME", or "NO IME CONNECTION".
https://user-images.githubusercontent.com/7259036/212573356-45f3d0f2-aa1c-4e62-9b90-cff3e5b06a61.mov
=> Added focus and IME debug visuals to Super Editor (Resolves #942)

super_editor/lib/src/default_editor/document_ime/document_ime_interaction_policies.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
Re-connect IME client to the IME overrides in SuperEditorImeInteractor when connection re-opens (Resolves #946)
This PR also adds `hasPrimaryFocus` as a condition to the automatic IME connection when selection changes.
=> Re-connect IME client to the IME overrides in SuperEditorImeInteractor when connection re-opens (Resolves #946)

super_editor/lib/src/default_editor/document_ime/document_ime_interaction_policies.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
Cherry pick: Re-connect IME client to the IME overrides in SuperEditorImeInteractor when connection re-opens (Resolves #946) (#947)
=> Re-connect IME client to the IME overrides in SuperEditorImeInteractor when connection re-opens (Resolves #946) (#947)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/lib/src/default_editor/document_ime/document_serialization.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
Fixed fast-typing IME errors by re-combining responsibilities for both applying deltas and serializing the document for IME (Resolves #914)
In the recent refactor, I split up the responsibility of applying IME deltas to a document, and the responsibility of serializing a document and sending it to the IME. I made this split because there can many factors that alter a document: IME deltas, key presses, other users over the network, reactionary commands, etc. Therefore, I wanted to avoid a special relationship between the behavior that edits a document based on IME deltas, and behavior that updates the IME with the latest document structure.
Unfortunately, this split wasn't working out. Most of the problem was related to non-atomic changes with documents and selection. We should try this …
=> Fixed fast-typing IME errors by re-combining responsibilities for both applying deltas and serializing the document for IME (Resolves #914)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/lib/src/default_editor/document_ime/document_serialization.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart
Cherry Pick: Fixed fast-typing IME errors by re-combining responsibilities for both applying deltas and serializing the document for IME (Resolves #914) (#950)
=> Fixed fast-typing IME errors by re-combining responsibilities for both applying deltas and serializing the document for IME (Resolves #914) (#950)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/test/src/default_editor/document_input_ime_test.dart
Reset our cached IME TextEditingValues when the IME connection re-opens (Resolves #954)
In the `DocumentInputImeClient` we serialize the document and selection to send them to the IME. When we serialize that information, we cache the last value that we serialized, so that we don't keep sending the same value to the IME multiple times. If we did, the IME would keep responding back and we'd get stuck in an infinite loop with the IME.
However, when the IME connection closes and re-opens, or gets replaced with another IME connection, we weren't resetting our local IME value. As a result, whatever the order of IME connection and operations happens to be, we were serializing the document, THEN we'd open a connection to the IME, but we wouldn't send the serialized value through because we …
=> Reset our cached IME TextEditingValues when the IME connection re-opens (Resolves #954)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/test/src/default_editor/document_input_ime_test.dart
Cherry pick: Reset our cached IME TextEditingValues when the IME connection re-opens (Resolves #954) (#955)
=> Reset our cached IME TextEditingValues when the IME connection re-opens (Resolves #954) (#955)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart
Don't try to send doc to IME when not attached, and ensure _isSendingToIme is always reset (Resolves #960)
=> Don't try to send doc to IME when not attached, and ensure _isSendingToIme is always reset (Resolves #960)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart
Cherry pick: Don't try to send doc to IME when not attached, and ensure _isSendingToIme is always reset (Resolves #960) (#961)
=> Don't try to send doc to IME when not attached, and ensure _isSendingToIme is always reset (Resolves #960) (#961)

super_editor/lib/src/default_editor/document_focus_and_selection_policies.dart, super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_textfield/super_textfield_robot.dart
SuperTextField: Don't change selection with two-finger trackpad movement (Resolves #964)
Also includes a one-line fix for an unrelated mistake.
=> SuperTextField: Don't change selection with two-finger trackpad movement (Resolves #964)

super_editor/lib/src/default_editor/document_focus_and_selection_policies.dart, super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_textfield/super_textfield_robot.dart
Cherry Pick: SuperTextField: Don't change selection with two-finger trackpad movement (Resolves #964) (#966)
=> SuperTextField: Don't change selection with two-finger trackpad movement (Resolves #964) (#966)

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
[SuperTextField][macOS] Fix compound characters insertion. Resolves #981
Compound characters, like `ã` and `á` aren't working in `SuperTextField` on mac. The reason is that we aren't honoring the composing region we get on the insertion deltas.
This PR changes `SuperTextField` to honor the composing region we get from the insertion delta.
=> [SuperTextField][macOS] Fix compound characters insertion (Resolves #981)

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
This PR cherry-picks "[SuperTextField][macOS] Fix compound characters insertion (Resolves #981) (#983)" to stable
=> Cherry-pick "[SuperTextField][macOS] Fix compound characters insertion (Resolves #981) (#983)" to stable

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
[SuperEditor][SuperTextField] Avoid handling non-text deltas in the same frame we set the editing state. Resolves #930,  #971, #970.
In some platforms, like macOS, whenever we call `setEditingState`, the engine sends us back a `TextEditingDeltaNonTextUpdate` to sync its state. We are always handling `TextEditingDeltaNonTextUpdate`s to change our selection, so this behavior causes various problems related to the selection, including some infinite loops.
We have no way to know if the `TextEditingDeltaNonTextUpdate` means that the selection/composing region changed, or if it means that the engine is trying to sync its state. I filed https://github.com/flutter/flutter/issues/118759 to track this.
This PR changes the IME code of both SuperEditor and SuperTextField to avoid handling …
=> [SuperEditor][SuperTextField] Avoid handling non-text deltas in the same frame we set the editing state (Resolves #930, #971, #970)

super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
This PR cherry-picks "Insert new line SuperTextField when NUMPAD ENTER is pressed (#988)" to stable
=> Cherry-pick "Insert new line SuperTextField when NUMPAD ENTER is pressed (#988)" to stable

super_editor/lib/src/default_editor/paragraph.dart, super_editor/test/super_editor/supereditor_style_test.dart
[SuperEditor] Fix visual styles when combining a paragraph with an empty list item. Resolves #980 
When creating a document with an empty list item and a paragraph node, combining both nodes causes the list item to end up with an incorrect style.
The cause is that the `CombineParagraphsCommand`, when the first node is empty, overrides the node's metadata with the second node's metadata. Because of this, we end up with a `ListItemNode` which doesn't have the `listItem` `blocktype` metadata. This causes the editor to apply the paragraph style to the list item node.
This PR changes the `CombineParagraphsCommand` to avoid overriding the `metadata` if the node above isn't a `ParagraphNode`. I chose this approach because it's closer to what we have (we maintain the `ListItemNode`).  Another …
=> [SuperEditor] Fix visual styles when combining a paragraph with an empty list item (Resolves #980)

super_editor/lib/src/default_editor/paragraph.dart, super_editor/test/super_editor/supereditor_style_test.dart
This PR cherry-picks "[SuperEditor] Fix visual styles when combining a paragraph with an empty list item (Resolves #980) (#996)" to stable.
=> Cherry-pick "[SuperEditor] Fix visual styles when combining a paragraph with an empty list item (Resolves #980) (#996)" to stable

super_editor/lib/src/core/document_composer.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_attributions_test.dart
[SuperEditor] Fix text attributions after tapping at an attributed range. Resolves #982
Tapping at an offset that contains attributions and typing a character isn't applying the attributions to the inserted text. When selecting using the keyboard this is working.
This was introduced after the selection reason PR. We aren't calling `notifyListeners` if the selection is changed using the `selectionNotifier`, which is how the selection is changed when tapping the editor.
This PR changes the `DocumentComposer` to call `notifyListeners` when the selection is changed using the `selectionNotifier`.
Link attributions are currently being ignored and there are tests ensuring that link attributions don't expand when typing at the beginning or end of a link.
This PR changes the `DocumentComposer` to …
=> [SuperEditor] Fix text attributions after tapping at an attributed range (Resolves #982)

super_editor/lib/src/core/document_composer.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_attributions_test.dart
This PR cherry-picks "[SuperEditor] Fix text attributions after tapping at an attributed range (Resolves #982) (#989)" to stable
=> Cherry-pick "[SuperEditor] Fix text attributions after tapping at an attributed range (Resolves #982) (#989)" to stable

super_editor_markdown/lib/src/document_to_markdown_serializer.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/lib/src/super_editor_syntax.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[super_editor_markdown] Add justify alignment for markdown serialization. Resolves #879
Currently, SuperEditor supports left, right and center alignment when using `MarkdownSyntax.superEditor`.
This PR adds the `justify` alignment to super_editor_markdown. 
As there isn't a spec for a justify alignment token, this PR introduces the  `----` token.
=> [super_editor_markdown] Add justify alignment for markdown serialization (Resolves #879)

super_editor/lib/src/default_editor/document_ime/ime_decoration.dart
Change `DeltaTextInputClientDecorator` to mix in `DeltaTextInputClient`
Flutter added a new method to `TextInputClient`. As `DeltaTextInputClientDecorator` is implementing `DeltaTextInputClient`, the CI is failing to build using the Flutter master branch.
The `DocumentImeInputClient` already uses the `with` keyword.
The added method was:
```dart
/// Notify client about new content insertion from Android keyboard.
void insertContent(KeyboardInsertedContent content) {}
```
The `KeyboardInsertedContent` dart doc is:
```dart
/// A class representing rich content (such as a PNG image) inserted via the
/// system input method.
///
/// The following data is represented in this class:
///  - MIME Type
///  - Bytes
///  - URI
```
=> Change `DeltaTextInputClientDecorator` to mix in `DeltaTextInputClient`

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_textfield/super_textfield_test.dart, super_editor/test/test_tools.dart
[SuperTextField] Add ability to update keyboard appearance. Resolves #991
Currently, it isn't possible to update the keyboard appearance after the `ImeAttributedTextEditingController` creation.
This PR adds the ability of changing the `keyboardAppearance` in the `updateTextInputConfiguration` method. 
We could also change the  `updateTextInputConfiguration` parameters to be nullable and use the previous values for the parameters that were not passed.
This PR also introduces a proposed class to facilitate intercepting platform messages.
=> [SuperTextField] Add ability to update keyboard appearance (Resolves #991)

super_editor/example/pubspec.yaml, super_editor/lib/src/default_editor/document_focus_and_selection_policies.dart, super_editor/lib/src/default_editor/super_editor.dart
[SuperEditor] Fix selection when the editor has autofocus. Resolves #883
When the editor has `autofocus`, the selection isn't set and we get the following exception:
```
flutter: Initializing logger: ExampleApp
════════ Exception caught by foundation library ════════════════════════════════
The following NoSuchMethodError was thrown while dispatching notifications for FocusNode:
The method 'findLastSelectablePosition' was called on null.
Receiver: null
Tried calling: findLastSelectablePosition()
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      _EditorSelectionAndFocusPolicyState._onFocusChange
package:super_editor/…/default_editor/document_focus_and_selection_policies.dart:110
#2 …
```
=> [SuperEditor] Fix selection when the editor has autofocus (Resolves #883)

super_editor/example/pubspec.yaml, super_editor/lib/src/default_editor/document_focus_and_selection_policies.dart, super_editor/lib/src/default_editor/super_editor.dart
This PR cherry-picks "[SuperEditor] Fix selection when the editor has autofocus (Resolves #883) (#1013)" to stable.
=> Cherry-pick "[SuperEditor] Fix selection when the editor has autofocus (Resolves #883) (#1013)" to stable

super_editor/lib/src/default_editor/text.dart
This PR cherry-picks "[SuperEditor] Expose TextComponentState (Resolves #1025) #1026" to `main`
=> Cherry-pick "[SuperEditor] Expose TextComponentState"

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/test/src/default_editor/document_input_ime_test.dart
[SuperEditor] Fix `performAction` override for `TextInputAction.newline`. Resolves #1012
When `SuperEditor` is configured to use `TextInputAction.newline`,  pressing the action button doesn't call `performAction` in the given `imeOverrides`. 
The cause is that, on Android, pressing an action button configured as `TextInputAction.newline` generates an insertion delta of `\n` instead of calling `performAction`. `TextDeltasDocumentEditor` translates the insertion into a `performAction` call. However, the call is handled inside `TextDeltasDocumentEditor` as it doesn't know about the overrides.
This PR changes `TextDeltasDocumentEditor` to accept a new property to override `performAction`.
=> [SuperEditor] Fix performAction override for TextInputAction.newline (Resolves #1012)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/test/src/default_editor/document_input_ime_test.dart
This PR cherry-picks "[SuperEditor] Fix performAction override for TextInputAction.newline (Resolves #1012) (#1017)" to stable
=> Cherry-pick "[SuperEditor] Fix performAction override for TextInputAction.newline (Resolves #1012) (#1017)" to stable

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/super_editor/supereditor_content_insertion_test.dart
[SuperEditor] Fix image insertion at the middle of a paragraph. Resolves #1018 
When placing the caret at the middle of a paragraph and trying to insert an image, the following exception is thrown:
```
Exception: Expected nodePosition of type UpstreamDownstreamNodePosition but received: TextPosition(offset: 0, affinity: TextAffinity.downstream)
```
The cause is that, when inserting a block node, we are using the same node id as the selected paragraph.
This PR changes the insertion of images and horizontal rules to use a new node id.
During tests, I found other issues.
* The `_insertBlockLevelContent` dart doc has this sentence: 
```dart
/// If the selection extent sits in an empty paragraph, that paragraph
/// is converted into the given [blockNode] and a new empty paragraph
/// is …
```
=> [SuperEditor] Fix image insertion at the middle of a paragraph (Resolves #1018)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_editor/test_documents.dart
Don't change selection when the user taps to stop scrolling momentum on mobile (Resolves #1035)
On Android, tapping on a `SingleChildScrollView` seems to stop the scroll momentum automatically. We don't get any direct notification of this, and our tap handlers are executed even though the user's action stopped the momentum. This PR adds some careful accounting to prevent us from taking further action when the user taps to stop scrolling.
On iOS, at least in the simulator, tapping on a `SingleChildScrollView` doesn't automatically stop the scrolling momentum. But it should. This PR forces the `SingleChildScrollView` to go idle when the user taps down.
=> Don't change selection when the user taps to stop scrolling momentum on mobile (Resolves #1035)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/super_editor/supereditor_content_insertion_test.dart
The recent work on #1019 fixed image and horizontal rule insertion in the middle of a non-empty paragraph node. Both images and horizontal rules call `_insertBlockLevelContent`, which handles the following cases:
- Empty paragraph
- Selection at the end of a non-empty paragraph
- Selection in the middle of a non-empty paragraph
This PR adds the following case to the `_insertBlockLevelContent` function:
- Selection at the beginning of a non-empty paragraph
Before this PR, adding a horizontal rule or image when the selection is at the beginning of a non-empty paragraph would end up using the *Selection in the middle of a non-empty paragraph* case, which would end up adding an extra empty paragraph node above the original paragraph node. 
Now, the horizontal rule or image node is inserted …
=> Implemented beginning of paragraph case for _insertBlockLevelContent

super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example/lib/main.dart, super_editor/lib/src/core/document_composer.dart, super_editor/lib/src/default_editor/document_gestures_interaction_overrides.dart, super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart, super_editor/lib/src/default_editor/document_hardware_keyboard/document_physical_keyboard.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/infrastructure/links.dart, super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/lib/super_editor.dart, super_editor/pubspec.yaml, super_editor/test/src/_text_entry_test_tools.dart, super_editor/test/src/default_editor/document_keyboard_actions_test.dart, super_editor/test/src/default_editor/list_items_test.dart, super_editor/test/src/default_editor/text_test.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_gestures_test.dart, super_editor/test/super_editor/test_documents.dart, super_editor/test/test_tools.dart
Make links tappable when in "interaction mode" (Resolves #1024)
This PR introduces the concept of an "interaction mode", which is a special mode that results in different user interaction behaviors compared to normal.
The interaction mode concept is added to the `DocumentComposer`, because the `DocumentComposer` represents transient UI modes.
The mouse gesture interactor adds the concept of a content delegate, which can express a desired mouse cursor when hovering over a piece of content, and also take action on single, double, or triple taps, instead of the mouse gesture interactor changing the document selection.
The mouse gesture content delegate is set to a link click delegate, by default.
The mouse gesture interactor needed to be updated to report key up events, so that we can turn …
=> [SuperEditor] Make links tappable when in "interaction mode" (Resolves #1024)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/super_editor/supereditor_content_insertion_test.dart
This PR cherry-picks "Implemented beginning of paragraph case for _insertBlockLevelContent (#1041)" to stable
=> Cherry-pick "Implemented beginning of paragraph case for _insertBlockLevelContent (#1041)" to stable

super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_attributions_test.dart
[SuperEditor] Fix toggling attributions on first insertion. Resolves #1007
After placing the caret at the end of a paragraph for the first time and toggling an attribution, the attribution isn't preserved when the user types:
https://user-images.githubusercontent.com/20045287/214872670-374060f6-7c00-4c4b-8059-f34ed046ea35.mov
The cause is that, upon the first insertion, the IME is sending us a `TextEditingDeltaNonTextUpdate` changing only the selection affinity. As the selection changed, we clear the current attributions.
This PR changes the `_updateComposerPreferencesAtSelection`  method to avoid updating the attributions when the selection is at the same node and the same offset as the previous selection.
=> [SuperEditor] Fix toggling attributions on first insertion (Resolves #1007)

super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_attributions_test.dart
This PR cherry-picks "[SuperEditor] Fix toggling attributions on first insertion (Resolves #1007) (#1043)" to stable
=> Cherry-pick "[SuperEditor] Fix toggling attributions on first insertion (Resolves #1007) (#1043)" to stable

super_editor/example/lib/demos/demo_animated_task_height.dart, super_editor/example/lib/main.dart
This new demo has a custom task component that shows/hides content under the task title with a size animation, depending on whether the task has selection or not. 
In this demo it is a custom implementation of `TaskComponent`, but it could be other types of nodes, like an image nodes that animates from a placeholder to the actual image once it's fully loaded.
As described in #1022, the animation of the height of components will not trigger the caret offset to be recalculated, since it currently only reacts to changes to the selections or to the document content (i.e. nodes). Same applies for any other overlay builder that attempts to render something above the document.
=> Add a demo where the height of the content (e.g. task) can animate

flutter_test_registry/flutter_test_repo_test.bat, flutter_test_registry/flutter_test_repo_test.sh
This package does not have a dependency on `flutter_test` and so there is no guarantee that the version of `test_api` from the pub solve is compatible with the `flutter test` command.
See https://github.com/flutter/flutter/issues/91107
=> Use dart test for attributed_text

super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/test/super_editor/supereditor_floating_cursor_test.dart
[SuperEditor][iOS] Fix caret display when floating cursor is visible. Resolves #992
When the iOS floating cursor is visible, we always display the "normal" caret, and the caret color isn't changed to grey, as can be seen in the video:
https://user-images.githubusercontent.com/31278849/214280623-8f5d2455-6508-4a03-aebd-da78ec3d6fc9.MP4
We already have some code to change the caret color to grey, but it isn't working.
This PR changes the iOS interactor to avoid displaying the caret when the floating cursor is over text or less than 30 pixels away from the text.
This PR also fixes the code to change the caret color to grey when the floating cursor is visible.
I had to use the `textLayout` property from `TextComponentState`, which is marked as `@visibleForTesting`, to check if the floating …
=> [SuperEditor][iOS] Fix caret display when floating cursor is visible (Resolves #992)

super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/test/super_editor/supereditor_floating_cursor_test.dart
This PR cherry-picks "[SuperEditor][iOS] Fix caret display when floating cursor is visible (Resolves #992) (#1030)" to stable.
=> Cherry-pick "[SuperEditor][iOS] Fix caret display when floating cursor is visible (Resolves #992) (#1030)" to stable

super_editor/test/super_editor/supereditor_text_layout_test.dart, super_text_layout/CHANGELOG.md, super_text_layout/lib/super_text_layout.dart, super_text_layout/lib/super_text_layout_inspector.dart, super_text_layout/pubspec.yaml
Make super_text_layout releasable again (Resolves #1083)
I added `flutter_test` to the regular package deps. I'd prefer not to, but we ship an "inspector", which uses test inspection APIs.
I also released v0.1.5 of `super_text_layout` with the code from this PR.
=> Make super_text_layout releasable again (Resolves #1083)

super_editor/lib/src/core/editor.dart
Add new 'Editor' class and edit pipeline without breaking anything (Related to #748)(Resolves #1087)
This is the first PR that moves us towards atomic commands, content reactions, and undo/redo.
This PR adds all the core concepts for the edit pipeline without changing any existing behavior. The purpose of this PR is to put the core API in front of other developers and see if there are any objections.
This API was created in a separate branch where I've implemented a handful of content reactions, including linkafication, image replacement, and user tagging.
I have a test suite for this `Editor` class, but I can't integrate that test until we're ready to break `Document` and `DocumentComposer`.
You can read a wiki article about how the edit pipeline concepts are meant to work: …
=> Add new 'Editor' class and edit pipeline without breaking anything (Related to #748)(Resolves #1087)

super_editor/lib/src/default_editor/document_focus_and_selection_policies.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_selection_test.dart
[SuperEditor] Avoid restoring selection upon re-focus when selected nodes were deleted. Resolves #1074
`EditorSelectionAndFocusPolicy` restores the previous selection when the editor re-gains focus. If the node at the selection base or extent was removed while the editor didn't have focus, restoring the selection causes the editor to crash, because we are applying a selection with an inexistent node.
This PR changes `EditorSelectionAndFocusPolicy` to check if the nodes at base and offset are still present before restoring the selection.
=> [SuperEditor] Avoid restoring selection upon re-focus when selected nodes were deleted (Resolves #1074)

super_editor/lib/src/default_editor/document_focus_and_selection_policies.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_selection_test.dart
This PR cherry-picks "[SuperEditor] Avoid restoring selection upon re-focus when selected nodes were deleted (Resolves #1074) (#1103)" to stable
=> Cherry-pick "[SuperEditor] Avoid restoring selection upon re-focus when selected nodes were deleted (Resolves #1074) (#1103)" to stable

super_editor/CHANGELOG.md, super_editor/README_RELEASING.md, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/pubspec.yaml
Prepare for stable release.
This PR cherry picks the v0.2.4-dev.1 release commit from `main` and adjusts it for `stable`, where we'll release v0.2.4.
=> Prepare for stable release

super_editor_markdown/CHANGELOG.md, super_editor_markdown/pubspec.yaml
Prepare super_editor_markdown for v0.1.4+2 release
This PR copies some changes that I think we only have on `stable`. This is probably because the last release was cut directly from `stable`, so we let `main` fall behind.
After bringing `main` up to date with `stable`, I updated the version number and added to the CHANGELOG.
=> Prepare super_editor_markdown for v0.1.4+2 release

super_editor/example/pubspec.yaml, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_ime/mobile_toolbar.dart, super_editor/lib/src/infrastructure/_listenable_builder.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart, super_editor/lib/src/infrastructure/super_textfield/ios/_floating_cursor.dart, super_editor/lib/src/infrastructure/super_textfield/ios/ios_textfield.dart
Migrate to Dart 3 and Flutter 3.10 (Resolves #1131)
This change is going to directly to `stable` because we've had these changes on `main` for a while.
=> Migrate to Dart 3 and Flutter 3.10 (Resolves #1131)

super_editor/CHANGELOG.md, super_editor/example/lib/demos/super_document/example_document.dart, super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/document_gestures_interaction_overrides.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_keyboard_interactor.dart, super_editor/lib/src/super_reader/read_only_document_mouse_interactor.dart, super_editor/lib/src/super_reader/reader_context.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/super_editor.dart, super_editor/test/super_reader/reader_test_tools.dart
Added link launching on tap for SuperReader (Resolves #1151)
This `SuperReader` implementation was essentially a one-for-one copy from `SuperEditor`.
=> Added link launching on tap for SuperReader (Resolves #1151)

super_editor/lib/src/default_editor/paragraph.dart, super_editor/test/super_editor/text_entry/keyboard_selection_and_deletion_test.dart, super_editor/test/test_tools.dart
[SuperEditor] Fix deletion of first character of a header with backspace (Resolves #1176)
When the caret is after the first character of a header, pressing deleting is causing the header to be converted to a paragraph.
The cause is that, after deleting the character, we are handling the backspace KeyUpEvent in `backspaceToClearParagraphBlockType`. As the first character was already removed when `backspaceToClearParagraphBlockType` the selection sits at the beginning of the text and thus the header metadata is cleared.
This PR changes `backspaceToClearParagraphBlockType` to ignore events other than `RawKeyDownEvent`.
=> [SuperEditor] Fix deletion of first character of a header with backspace (Resolves #1176)

super_editor/lib/src/default_editor/paragraph.dart, super_editor/test/super_editor/text_entry/keyboard_selection_and_deletion_test.dart, super_editor/test/test_tools.dart
This PR cherry-picks "[SuperEditor] Fix deletion of first character of a header with backspace (Resolves #1176) (#1179)" to stable
=> Cherry-pick "[SuperEditor] Fix deletion of first character of a header with backspace (Resolves #1176) (#1179)" to stable

super_editor/example/analysis_options.yaml, super_editor/lib/src/core/document.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/test/super_editor/infrastructure/editor_test.dart
Added reference to old DocumentNode within NodeRemovedEvent (Resolves #1181)
This change was made so that editor reactions can base their decisions on content in a removed node.
This addition isn't ideal because we're passing a reference to a now-deleted, mutable `DocumentNode`, but it's unclear what else we should do. We'll probably revisit issues like this later.
=> Added reference to old DocumentNode within NodeRemovedEvent (Resolves #1181)

super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/test/super_editor/text_entry/links_test.dart
[SuperEditor] Linkify URLs without www (Resolves #1178).
By default, the package used to extract URLs from the text doesn't recognize URLs without www.
This PR enables the option to allow "loose" URLs.
=> [SuperEditor] Linkify URLs without www (Resolves #1178)

super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/test/super_editor/text_entry/links_test.dart
This PR cherry-picks "[SuperEditor] Linkify URLs without www (Resolves #1178) (#1183)" to stable
=> Cherry-pick "[SuperEditor] Linkify URLs without www (Resolves #1178) (#1183)" to stable

attributed_text/CHANGELOG.md, attributed_text/lib/src/attributed_spans.dart, attributed_text/lib/src/attributed_text.dart, attributed_text/lib/src/test_tools.dart, attributed_text/test/attributed_text_test.dart
Let the user add attributions without auto-merging with nearby attributions (Resolves #1198)
This change supports use-cases like hash tags where sometimes we want the attribution to expand, and other times we don't.
Example:
```
// We want to expand
#jo
#joh
// We don't want to expand
#john
#john#
```
=> Let the user add attributions without auto-merging with nearby attributions (Resolves #1198)

super_editor/test/super_editor/supereditor_floating_cursor_test.dart
Prepare for the change to the default value of ThemeData.useMaterial3 coming in https://github.com/flutter/flutter/issues/127064. Currently the 'shows grey caret when far from text' test depends on the UI being configured for Material2. Changed the test so that it checks the theme's primary color; the cursor's default color. This works for M2 and M3.
=> Update one floating cursor test for the M3 default transition

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/super_textfield_test.dart
[SuperTextField] Allow changing keyboard appearance while detached from IME. Resolves #1205 
When detached from the IME, trying to update the keyboard appearance has no effect.
We were already caching the given `keyboardAppearance` in `updateTextInputConfiguration` and reusing it if we detach and reattach, but we weren't caching it if `updateTextInputConfiguration` is called while detached from the IME.
This PR changes `updateTextInputConfiguration` to always cache the given `keyboardAppearance`.
=> [SuperTextField] Allow changing keyboard appearance while detached from IME (Resolves #1205)

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/super_textfield_test.dart
This PR cherry-picks "[SuperTextField] Allow changing keyboard appearance while detached from IME (Resolves #1205) (#1207)" to stable
=> Cherry-pick "[SuperTextField] Allow changing keyboard appearance while detached from IME (Resolves #1205) (#1207)" to stable

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
This PR cherry-picks "[SuperTextField][Android] Fix glitch with predictive text (Resolves #1113) (#1156)" to stable
=> Cherry-pick "[SuperTextField][Android] Fix glitch with predictive text (Resolves #1113) (#1156)" to stable

super_editor/pubspec.yaml
* Updates minimum version of `golden_toolkit` to remove reference to deprecated `addTime` method.
Resolves #1210
=> Fixes `flutter_test` deprecations

super_editor_markdown/pubspec.yaml, super_text_layout/pubspec.yaml
* Updates minimum version of `golden_toolkit` to remove reference to `addTime` method for other packages as well
Resolves #1210 
Followup for #1211, updating the `golden_toolkit` for all packages, not just `super_editor`.
=> Fixes `flutter_test` deprecations (2)

super_editor/pubspec.yaml
`http` package has finally reached stable version.
There is no compatiblity issue between version `0.13.1` and `1.0.0`.
=> chore: Relax http dependency constraint by including v1.x.x

super_editor/pubspec.yaml
This PR cherry-picks "Relax http dependency constraint by including v1.x.x (#1206)" to stable.
=> Cherry-pick "Relax http dependency constraint by including v1.x.x (#1206)" to stable

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart
[SuperTextField] Fix ImeAttributedTextEditingController not removing inner controller listener. Resolves #1227 
In `ImeAttributedTextEditingController` we are adding a listener to the inner controller, but we aren't removing it upon disposal. This causes a crash if the inner controller is reused in a new `ImeAttributedTextEditingController`.
This PR changes `ImeAttributedTextEditingController` to remove the listener when `dispose` is called.
I'm not sure if we need a test for this, but I added anyway.
=> [SuperTextField] Fix ImeAttributedTextEditingController not removing inner controller listener (Resolves #1227)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/test/src/default_editor/document_input_ime_test.dart
[SuperEditor][Android] Fix IME mappings on text replacements. Resolves #1217
There are different issues in the ticket:
1. On Android, accepting keyboard text suggestions sometimes causes the editor to crash due to an IME mapping failure. Most of the examples listed in the ticket seem to be caused by the same problem.
This seems to happen when the IME sends a replacement text bigger than the replaced text and an insertion in the same list. This is causing us to fail to map the position for the insertion. I noticed that this happens only when using the Samsung keyboard. When using GBoard, the IME generates a deletion followed by an insertion instead of a replacement.
This PR changes our replacement handling to reset `_serializedDoc` the same way we do when handling insertions.
2. Pressing …
=> [SuperEditor][Android] Fix IME mappings on text replacements (Resolves #1217)

super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart
This PR cherry-picks "[SuperTextField] Fix ImeAttributedTextEditingController not removing inner controller listener (Resolves #1227) (#1228)" to stable.
=> Cherry-pick "[SuperTextField] Fix ImeAttributedTextEditingController not removing inner controller listener (Resolves #1227) (#1228)" to stable

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/test/src/default_editor/document_input_ime_test.dart
This PR cherry-picks "[SuperEditor][Android] Fix IME mappings on text replacements (Resolves #1217) (#1225)" to stable.
=> Cherry-pick "[SuperEditor][Android] Fix IME mappings on text replacements (Resolves #1217) (#1225)" to stable

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/test/src/default_editor/list_items_test.dart, super_editor/test/super_editor/components/task_test.dart
[SuperEditor][Mobile] Fix task and list item splitting on ENTER. Resolves #1157 
On mobile, pressing ENTER on a task doesn't split the task. The cause is that we weren't handling the `TaskNode` in `insertBlockLevelNewline` and `_insertNewlineInDeltas`.
After the fix, I found the same issue reported in https://github.com/superlistapp/super_editor/issues/1081, so I applied the same solution.
During the tests, I noticed that the list item splitting wasn't working on Android. I also fixed that.
There are 3 ways that the ENTER key is reported:
- On Desktop we receive key presses.
- On Android we receive an insertion delta of `\n`.
- On iOS we receive a `newline` input action.
Because of that I added 3 tests for each case. Maybe we could add another `pressEnter` method that generates different …
=> [SuperEditor][Mobile] Fix task and list item splitting on ENTER (Resolves #1157)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/test/super_editor/components/horizontal_rule_test.dart
[SuperEditor] Fix text insertion when the caret sits at a horizontal rule. Resolves #1187
Typing text when a horizontal rule node has selection, introduces empty text nodes in the document. The issue is that we are inserting a new paragraph but not updating the insertion position before trying to insert the text.
This PR changes `_insertPlainText` to consider the end position of the new node to insert the text.
https://github.com/superlistapp/super_editor/assets/7597082/df5f983a-5e18-427c-861d-c22713b9a7ee
=> [SuperEditor] Fix text insertion when the caret sits at a horizontal rule (Resolves #1187)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/test/src/default_editor/list_items_test.dart, super_editor/test/super_editor/components/task_test.dart
This PR cherry-picks "[SuperEditor][Mobile] Fix task and list item splitting on ENTER (Resolves #1157) (#1184)" to stable.
=> Cherry-pick "[SuperEditor][Mobile] Fix task and list item splitting on ENTER (Resolves #1157) (#1184)" to stable

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/test/super_editor/components/horizontal_rule_test.dart
This PR cherry-picks "[SuperEditor] Fix text insertion when the caret sits at a horizontal rule (Resolves #1187) (#1196)" to stable.
=> Cherry-pick "[SuperEditor] Fix text insertion when the caret sits at a horizontal rule (Resolves #1187) (#1196)" to stable

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
[SuperEditor][SuperTextField] Remove workaround code. Resolves #1235
We have some temporary code added because of https://github.com/flutter/flutter/issues/118759. As this was already fixed by https://github.com/flutter/engine/pull/42091, we can safely remove this code.
This PR removes the temporary code.
=> [SuperEditor][SuperTextField] Remove workaround code (Resolves #1235)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/lib/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart
This PR cherry-picks "[SuperEditor][SuperTextField] Remove workaround code (Resolves #1235) (#1245)" to stable.
=> Cherry-pick "[SuperEditor][SuperTextField] Remove workaround code (Resolves #1235) (#1245)" to stable

super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart
[SuperTextField][Android] Fix drag handle jumping when adding text at the end. Resolves #1114
When the text field is center-aligned, typing at the end of the text field causes the drag handle to "flash" at the center of the text field before being displayed at the correct position:
https://github.com/superlistapp/super_editor/assets/7597082/7ffae77a-f018-44fe-b8a1-e5ee0380a20d
The cause seems to be a timing issue. We are computing the drag handle offset during build and it seems we are requesting the caret offset while the text layout isn't updated with the new text.
This PR changes the `AndroidEditingOverlayControls` to compute and cache the caret offset in a post-frame callback after the text/selection changes.
After the changes: …
=> [SuperTextField][Android] Fix drag handle jumping when adding text at the end (Resolves #1114)

super_editor/example/lib/demos/demo_empty_document.dart, super_editor/example/lib/main.dart, super_editor/lib/src/core/document_layout.dart, super_editor/lib/src/core/editor.dart, super_editor/lib/src/default_editor/box_component.dart, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/document_ime/document_serialization.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/_logging.dart, super_editor/test/src/default_editor/document_input_ime_test.dart, super_editor/test/super_editor/text_entry/paragraph_conversions_test.dart
Moved IME upstream deletion in at the beginning of nodes to Editor requests instead of direct implementation, for the purpose of extensability (Resolves #1259)
=> Moved IME upstream deletion in empty nodes to Editor requests instead of direct implementation, for the purpose of extensability (Resolves #1259)

super_text_layout/test/super_text_test.dart
A long-standing rounding hack in `TextPainter` will soon be removed (https://github.com/flutter/flutter/issues/31707). As a result the horizontal width of some text reported by `TextPainter` will be slightly smaller as it's no longer rounded up.
=> Flutter migration: Remove rounding hack from TextPainter

attributed_text/CHANGELOG.md, attributed_text/lib/src/attributed_spans.dart, attributed_text/lib/src/attributed_text.dart, attributed_text/lib/src/test_tools.dart, attributed_text/test/attributed_text_test.dart
Let the user add attributions without auto-merging with nearby attributions (Resolves #1198) (#1199)
I must have missed this cherry-pick, originally. This is a couple months old. Cherry picking now because we need this for tagging.
=> Let the user add attributions without auto-merging with nearby attributions (Resolves #1198) (#1199)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/test/super_editor/supereditor_content_insertion_test.dart
[SuperEditor] Fix image insertion bugs. Partially resolves #1209
We have some issues related to images:
-  Inserting a paragraph when the caret sits after an image doesn't change the selection:
https://github.com/superlistapp/super_editor/assets/6467808/0c3cb5f3-dfb1-4dd6-add8-5e8ce7b6d0d5
The root cause is that we aren't executing a `ChangeSelectionRequest` after inserting the image.
This PR changes the image insertion to execute a `ChangeSelectionRequest`.
- Inserting an image when the caret sits at the end of a paragraph (with upstream affinity) throws an exception:
https://github.com/superlistapp/super_editor/assets/6467808/9965ccb2-d20c-4995-8755-defb9657af07
We are comparing the text positions as `paragraphPosition == endOfParagraph`, which returns `false` if the affinity is …
=> [SuperEditor] Fix image insertion bugs (Partially resolves #1209)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/test/super_editor/supereditor_content_insertion_test.dart
This PR cherry-picks "[SuperEditor] Fix image insertion bugs (Partially resolves #1209) (#1251)" to stable.
=> Cherry-pick "[SuperEditor] Fix image insertion bugs (Partially resolves #1209) (#1251)" to stable

super_editor/test/src/default_editor/document_input_ime_test.dart
[SuperEditor] Add chinese input test. Resolves #1230
Before #1245 was merged, when the user uses a chinese keyboard, typing a characterd after accepting a suggestion causes the whole text to be replaced by the last character typed.
Looking at the logs, the following is happening:
1. We receive the replacement delta
2. We send [0,3) as the composing region back to the IME.
3. We receive [-1,-1] as the new composing region (in the same frame)
It seems that, after step 3, the IME changes the composing region to the value we sent in step 2. As we had code to ignore non-text deltas in the same frame as we send the editing value to the IME, we don't clear the composing region after step 3.
Because of that, the whole text becomes part of the composing region, which is why the whole text is …
=> [SuperEditor] Add chinese input test (Resolves #1230)

super_editor/lib/src/default_editor/box_component.dart, super_editor/test/src/default_editor/upstream_downstream_selection_test.dart
Resolves #1247
**Description:**
The current implementation of the `selectDownstreamPosition` on the `BlockNode` returns the wrong `UpstreamDownstreamNodePosition` which results in a bug where the caret moves to upstream on the selected block when right arrow key is pressed, as seen in the video below
https://github.com/superlistapp/super_editor/assets/65209850/c084456d-6992-4e13-9c8c-b496322123bf
This affected the Nodes based on `BlockNode`, `ImageNode` and `HorizontalRuleNode`.
**Solution:**
Correct behaviour is to move the caret position on the downstream on the block. This PR resolves this by returning the `UpstreamDownstreamNodePosition` with appropriate `TextAffinity`, which moves the caret position on the downstream when right arrow key is pressed with the block selected. …
=> [SuperEditor] Moves caret on downstream when right arrow's pressed while block is selected (Resolves #1247)

super_editor/lib/src/default_editor/box_component.dart, super_editor/test/src/default_editor/upstream_downstream_selection_test.dart
Cherry-pick: [SuperEditor] Moves caret on downstream when right arrow's pressed while block is selected (Resolves #1247) (#1258)
=> Cherry-pick: [SuperEditor] Moves caret on downstream when right arrow's pressed while block is selected (Resolves #1247) (#1258)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/test/super_editor/text_entry/links_test.dart
Don't extend links to new, empty paragraphs (Resolves #1276)
The problem: When the user places the caret at the end of a link, at the end of a paragraph, and the user presses ENTER, the newly created paragraph initially contains the same link attribution. This attribution is immediately removed when the user starts typing, but the attribution should not exist at all in the new empty paragraph.
The longer term solution is probably to move attribution expansion to `EditReaction`s: https://github.com/superlistapp/super_editor/issues/1296
As a temporary solution, I've added an attribution filter to the paragraph split request, which decides which attributions can extend from the end of one paragraph to the beginning of a new paragraph.
=> Don't extend links to new, empty paragraphs (Resolves #1276)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/test/super_editor/text_entry/links_test.dart
Cherry Pick: Don't extend links to new, empty paragraphs (Resolves #1276) (#1297)
=> Cherry Pick: Don't extend links to new, empty paragraphs (Resolves #1276) (#1297)

super_editor/lib/src/core/edit_context.dart, super_editor/lib/src/default_editor/document_scrollable.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/documents/document_scaffold.dart, super_editor/lib/src/infrastructure/documents/document_scroller.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/super_editor.dart, super_editor/test/src/_document_test_tools.dart, super_editor/test/src/default_editor/document_input_ime_test.dart, super_editor/test/src/default_editor/document_keyboard_actions_test.dart, super_editor/test/src/default_editor/list_items_test.dart, super_editor/test/src/default_editor/super_editor_test.dart, super_editor/test/src/default_editor/text_test.dart, super_editor/test/super_editor/components/horizontal_rule_test.dart, super_editor/test/super_editor/document_test_tools.dart, super_editor/test/super_editor/supereditor_attributions_test.dart, super_editor/test/super_editor/supereditor_content_insertion_test.dart, super_editor/test/super_editor/supereditor_gestures_test.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart, super_editor/test/super_editor/supereditor_mobile_handles_test.dart, super_editor/test/super_editor/supereditor_popover_focus_test.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_editor/supereditor_selection_test.dart, super_editor/test/super_editor/supereditor_smoke_test.dart, super_editor/test/super_editor/supereditor_software_keyboard_toolbar_test.dart, super_editor/test/super_editor/supereditor_style_test.dart, super_editor/test/super_editor/text_entry/keyboard_selection_and_deletion_test.dart, super_editor/test/super_editor/text_entry/paragraph_conversions_test.dart, super_editor/test/super_editor/text_entry/stable_tags_test.dart
Exposed scroll control through SuperEditorContext (Resolves #1288)
This PR exposes some chosen scrolling controls through `SuperEditorContext`, which can then be used by keyboard handlers and other similar actors.
I had to refactor a lot of test references because we now have a difference between the objects passed into a `SuperEditor` vs objects revealed by a `SuperEditor`. That said, none of the test changes were behavioral changes. It's just re-organization.
=> Exposed scroll control through SuperEditorContext (Resolves #1288)

super_editor/example/lib/demos/supertextfield/_emojis_demo.dart, super_editor/example/lib/demos/supertextfield/_expanding_multi_line_demo.dart, super_editor/example/lib/demos/supertextfield/_interactive_demo.dart, super_editor/example/lib/demos/supertextfield/_mobile_textfield_demo.dart, super_editor/example/lib/demos/supertextfield/_single_line_demo.dart, super_editor/example/lib/demos/supertextfield/_static_multi_line_demo.dart, super_editor/example/lib/demos/supertextfield/android/demo_superandroidtextfield.dart, super_editor/example/lib/demos/supertextfield/demo_text_styles.dart, super_editor/example/lib/demos/supertextfield/ios/demo_superiostextfield.dart, super_editor/lib/src/super_textfield/android/_editing_controls.dart, super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/ios/_editing_controls.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart
Use TapRegions in SuperTextField to support unfocusing when tapping or dragging outside (Resolves #1263)
This PR adds support for passing a `TapRegion` "group ID" to all widgets associated with a `SuperTextField`. This includes the area of the text field, itself, as well as handles and toolbars.
Out of the box, this change has no impact. However, by providing a group ID, developers can surround a `SuperTextField` with their own `TapRegion` and implement "tap outside to unfocus". I updated one of our example app demos to show this. We should probably rework all the `SuperTextField` demos to be more consistent and appealing, but I'll leave that for another ticket.
=> Use TapRegions in SuperTextField to support unfocusing when tapping or dragging outside (Resolves #1263)

super_editor/example/lib/demos/supertextfield/_emojis_demo.dart, super_editor/example/lib/demos/supertextfield/_expanding_multi_line_demo.dart, super_editor/example/lib/demos/supertextfield/_interactive_demo.dart, super_editor/example/lib/demos/supertextfield/_mobile_textfield_demo.dart, super_editor/example/lib/demos/supertextfield/_single_line_demo.dart, super_editor/example/lib/demos/supertextfield/_static_multi_line_demo.dart, super_editor/example/lib/demos/supertextfield/android/demo_superandroidtextfield.dart, super_editor/example/lib/demos/supertextfield/demo_text_styles.dart, super_editor/example/lib/demos/supertextfield/ios/demo_superiostextfield.dart, super_editor/lib/src/super_textfield/android/_editing_controls.dart, super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/ios/_editing_controls.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart
Cherry Pick: Use TapRegions in SuperTextField to support unfocusing when tapping or dragging outside (Resolves #1263) (#1310)
=> Cherry Pick: Use TapRegions in SuperTextField to support unfocusing when tapping or dragging outside (Resolves #1263) (#1310)

super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/components/block_node_test.dart
[SuperEditor][web] Fix new line duplication. Resolves #1219.
In the Sliver Editor Demo in the Demo App, pressing ENTER is still causing the editor to duplicate the new lines.
The cause is that, if the `inputSource` isn't passed in the constructor, the editor uses IME as the input source, but still uses the keyboard handlers for the desktop input source.
This PR inverts the condition, as a `null` `inputSource` in the constructor will default to IME.
We could also write it as the following: 
```dart
keyboardActions = keyboardActions ??
(inputSource == null || inputSource == TextInputSource.ime
? defaultImeKeyboardActions
: defaultKeyboardActions),
```
or also
```dart
((inputSource ?? TextInputSource.ime) == TextInputSource.ime
? defaultImeKeyboardActions
: defaultKeyboardActions),
```
I'm …
=> [SuperEditor][web] Fix new line duplication (Resolves #1219)

super_editor/lib/src/super_textfield/infrastructure/text_scrollview.dart, super_editor/test/super_textfield/super_textfield_rendering_test.dart
[SuperTextField][Mobile] Always compute the viewport height in the first frame. Resolves #939
Currently, there are cases where we compute the textfield size after the first frame. This causes some flickering when using it inside a scrollable.
This PR moves the existing viewport height computation to a new widget, which performs the computation during layout. With this change, we always size the viewport since the first frame.
The downside is that we perform layout twice. The first one is needed so the text layout is performed so we can access the text layout information and the second one uses the information retrieved from the first layout to size the viewport. We probably could introduce some caching to avoid performing two layouts in some situations.
=> [SuperTextField][Mobile] Always compute the viewport height in the first frame (Resolves #939)

super_editor/lib/src/super_textfield/infrastructure/text_scrollview.dart, super_editor/test/super_textfield/super_textfield_rendering_test.dart
This PR cherry-picks "[SuperTextField][Mobile] Always compute the viewport height in the first frame (Resolves #939) (#1319)" to stable.
=> Cherry-pick "[SuperTextField][Mobile] Always compute the viewport height in the first frame (Resolves #939) (#1319)" to stable

super_editor/lib/src/super_textfield/infrastructure/text_scrollview.dart, super_editor/test/super_textfield/super_textfield_rendering_test.dart
[SuperTextField][mobile] Avoid calling `getMinIntrinsicHeight` in `TextScrollview. Resolves #939.
This PR fixes an issue pointed out by @knopp, where calling `getMinIntrinsicHeight` causes an exception in `RenderFlex` if it has a baseline `crossAxisAlignment`.
I was able to write a failing test with the previous implementation.
This PR removes the `getMinIntrinsicHeight` and instead, lays out the child with infinity height constraints.
=> [SuperTextField][mobile] Avoid calling `getMinIntrinsicHeight` in `TextScrollview` (Resolves #939)

super_editor/lib/src/super_textfield/infrastructure/text_scrollview.dart, super_editor/test/super_textfield/super_textfield_rendering_test.dart
This PR cherry-picks "[SuperTextField][mobile] Avoid calling `getMinIntrinsicHeight` in `TextScrollview` (Resolves #939) (#1340)" to stable.
=> Cherry-pick "[SuperTextField][mobile] Avoid calling `getMinIntrinsicHeight` in `TextScrollview` (Resolves #939) (#1340)" to stable

super_editor/pubspec.yaml, super_editor_markdown/pubspec.yaml, super_text_layout/pubspec.yaml
Needed for: https://github.com/flutter/flutter/pull/133176 and https://github.com/flutter/flutter/pull/133178
The deprecation period for the following `TestWindow` members has elapsed:
* `textScaleFactorTestValue`
* `clearTextScaleFactorTestValue`
* `platformBrightnessTestValue`
* `clearPlatformBrightnessTestValue`
Links to crashing tests: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20customer_testing/61658/overview and https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20customer_testing/61656/overview
These members are being removed from the framework so this PR helps update some dependencies that were using the deprecated members.
I have confirmed that customer tests now pass locally as the `golden_toolkit v 0.15.0` has updated their implementations to use …
=> Fixes `flutter_test` `TestWindow` deprecations

super_editor/pubspec.yaml, super_editor_markdown/pubspec.yaml, super_text_layout/pubspec.yaml
This PR cherry-picks "Flutter Team: Upgrades golden_toolkit for `flutter_test` `TestWindow` deprecations (#1343)" to stable.
=> Cherry-pick "Flutter Team: Upgrades golden_toolkit for `flutter_test` `TestWindow` deprecations (#1343)" to stable

super_editor/lib/src/infrastructure/content_layers.dart, super_editor/test/infrastructure/content_layers_test.dart
Fix null pointer exception in document overlays due to setState() timing (Resolves #1330)
This problem is a continuation of nuanced widget build ordering and timing within Flutter. This problem is described in an existing Flutter ticket: https://github.com/flutter/flutter/issues/123305
The problem in this ticket is that a number of editor interactions were generating null pointer exceptions when the selection leader overlay would lookup offsets and sizes in the document layout.
After a lot of digging, I was eventually able to write a test that recreated the exception. The situation that seemed to trigger this error is one in which an overlay calls `setState()` on itself, but also the `State` object that contains the whole `SuperEditor` also calls `setState()` in the same frame.
When I …
=> Fix null pointer exception in document overlays due to setState() timing (Resolves #1330)

super_editor/lib/src/infrastructure/content_layers.dart, super_editor/test/infrastructure/content_layers_test.dart
Cherry Pick: Fix null pointer exception in document overlays due to setState() timing (Resolves #1330) (#1354)
=> Cherry Pick: Fix null pointer exception in document overlays due to setState() timing (Resolves #1330) (#1354)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart
[SuperEditor] Fix composer preferences after text replacement. Resolves #1167 
Accepting keyboard suggestions can cause the text to lose the style, as can be seen in the following video:
https://github.com/superlistapp/super_editor/assets/37604230/ec610720-acb2-49e9-beae-c0f19b436934
When we receive the replacement delta generated by the IME, we first delete the old text and then insert the new one. Deleting the old text might clear the composer current attributions. This is what is causing the issue.
This PR changes `insertPlainText`, so when we are replacing text, we store the current attributions. After deleting the old text we insert the new one with the stored attributions.
=> [SuperEditor] Fix composer preferences after text replacement (Resolves #1167)

super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/lib/src/default_editor/text_tokenizing/pattern_tags.dart, super_editor/lib/src/default_editor/text_tokenizing/stable_tags.dart, super_editor/test/super_editor/text_entry/tagging/action_tags_test.dart, super_editor/test/super_editor/text_entry/tagging/pattern_tags_test.dart, super_editor/test/super_editor/text_entry/tagging/stable_tags_test.dart
Adjusted tag indices to only notify listeners when tags actually change (Resolves #1355)
Previously the pattern tag and stable tag indices were sending notifications during every reaction. Now they only send notifications when a tag is added, removed, or changed.
=> Adjusted tag indices to only notify listeners when tags actually change (Resolves #1355)

super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/lib/src/default_editor/text_tokenizing/pattern_tags.dart, super_editor/lib/src/default_editor/text_tokenizing/stable_tags.dart, super_editor/test/super_editor/text_entry/tagging/action_tags_test.dart, super_editor/test/super_editor/text_entry/tagging/pattern_tags_test.dart, super_editor/test/super_editor/text_entry/tagging/stable_tags_test.dart
Cherry Pick: Adjusted tag indices to only notify listeners when tags actually change (Resolves #1355) (#1357)
=> Cherry Pick: Adjusted tag indices to only notify listeners when tags actually change (Resolves #1355) (#1357)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart
This PR cherry-picks "[SuperEditor] Fix composer preferences after text replacement (Resolves #1167) (#1351)" to stable.
=> Cherry pick "[SuperEditor] Fix composer preferences after text replacement (Resolves #1167) (#1351)" to stable

super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart
[SuperEditor] Apply theme brightness to the software keyboard. Resolves #1003
Currently, SuperEditor doesn't look at the theme to determine the keyboard appearance. The ticket mentioned that the keyboard is always dark, but it seems to be the contrary. Even when the the brightness is `dark`, the keyboard stays in `light` mode.
It's already possible to customize the keyboard appearance by passing a `SuperEditorImeConfiguration` to the editor. When a configuration isn't given, the editor uses a default `SuperEditorImeConfiguration`, which always use light keyboard appearance.
This PR makes `imeConfiguration` optional, and resolves the default configuration during build.
=> [SuperEditor] Apply theme brightness to the software keyboard (Resolves #1003)

super_editor/example/lib/demos/demo_markdown_serialization.dart, super_editor_markdown/lib/src/document_to_markdown_serializer.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[super_editor_markdown] Add support for task syntax. Resolves #1294 
SuperEditor now includes support for tasks by default, but it doesn't support serializing/deserializing them.
This PR implements markdown serialization/deserialization for tasks using the github style syntax:
```
```
Tasks can also be multiline, for example:
```
with multiple lines
```
The previous input renders:
with multiple lines
=> [super_editor_markdown] Add support for task syntax (Resolves #1294)

super_editor/pubspec.yaml, super_editor/test/super_reader/super_reader_keyboard_test.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
Upgrade test robots package version and adjust for some Flutter bugs (Resolves #1344)
In case this is needed for future reference: We had to release a few revisions of the robots package, and even alter some tests in `super_editor`, because a new robots feature uncovered a number of bugs related to how Flutter handles the simulated `platform` in key presses.
=> Upgrade test robots package version and adjust for some Flutter bugs (Resolves #1344)

attributed_text/lib/src/attributed_spans.dart, attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_text_test.dart
Cherry Pick: Added collapsed span visitation in AttributedText, added tests for both versions of attribution visitors (Resolves #1215) (#1375)
=> Cherry Pick: Added collapsed span visitation in AttributedText, added tests for both versions of attribution visitors (Resolves #1215) (#1375)

attributed_text/lib/src/attributed_spans.dart
Cherry Pick: Added a 'range' property to AttributionSpan (Resolves #1192) (#1376)
=> Cherry Pick: Added a 'range' property to AttributionSpan (Resolves #1192) (#1376)

super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart
This PR cherry-picks "[SuperEditor] Apply theme brightness to the software keyboard (Resolves #1003) (#1359)" to stable.
=> Cherry-pick "[SuperEditor] Apply theme brightness to the software keyboard (Resolves #1003) (#1359)" to stable

super_editor/example/lib/demos/demo_markdown_serialization.dart, super_editor_markdown/lib/src/document_to_markdown_serializer.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/test/super_editor_markdown_test.dart
This PR cherry-picks "[super_editor_markdown] Add support for task syntax (Resolves #1294) (#1360)" to stable.
=> Cherry-pick "[super_editor_markdown] Add support for task syntax (Resolves #1294) (#1360)" to stable

super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
[SuperTextField] Expose IME configuration. Resolves #1109 
Currently, we can configure the textfield's `textInputAction` but we can't configure other IME aspects, like keyboard type and autocorrection.
This PR  introduces a `SuperTextFieldImeConfiguration`, which users can use to configure the IME. As both `SuperTextFieldImeConfiguration` and `textInputAction` configures the input action, the `textInputAction` is being deprecated.
I added an `attachToImeWithConfig` method in `ImeAttributedTextEditingController` instead of changing the existing method to avoid a breaking change. If we should just change `attachToIme` then I can make this change.
=> [SuperTextField] Expose IME configuration (Resolves #1109) 

super_editor/test/super_editor/supereditor_robot_test.dart
[SuperEditor] Add placeCaretInParagraph tests. Resolves #627
The tickets mentioned that calling `placeCaretInParagraph` was not working. A failing test was provided:
```dart
testWidgets("enters text with hardware keyboard", (tester) async {
// Configure and render a document.
await tester //
.createDocument()
.withSingleEmptyParagraph()
.forDesktop()
.autoFocus(true)
.pump();
// Tap to place the caret in the first paragraph.
await tester.placeCaretInParagraph("1", 0);
// await tester.placeCaretInParagraph("1", 0);
// Type some text by simulating hardware keyboard key presses.
await tester.typeKeyboardText("Hello, world!");
await tester.placeCaretInParagraph("1", 13);
await tester.typeKeyboardText("ABC");
// Verify that SuperEditor displays the text we typed. …
```
=> [SuperEditor] Add placeCaretInParagraph tests (Resolves #627)

attributed_text/lib/src/attributed_spans.dart
Cherry Pick: Remove attribution merge check when finding markers (Resolves #561) (#1388)
=> Cherry Pick: Remove attribution merge check when finding markers (Resolves #561) (#1388)

super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
This PR cherry-picks "[SuperTextField] Expose IME configuration (Resolves #1109)  (#1369)" to stable.
=> Cherry-pick "[SuperTextField] Expose IME configuration (Resolves #1109)  (#1369)" to stable

super_editor/example/pubspec.yaml, super_editor/pubspec.yaml
[SuperEditor] Bump linkify to v5.0.0. Resolves #1383
This PR bumps linkify dependency from 4.0.0 to 5.0.0
Although it is a major release there isn't any changes needed in our code.
=> [SuperEditor] Bump linkify to v5.0.0 (Resolves #1383)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/super_editor/supereditor_copy_and_paste_test.dart
[SuperEditor] Fix pasting multiple lines. Resolves #871.
When pasting multiple lines, the editor is creating a single paragraph containing all the lines. We are requiring two line breaks to create a new paragraph.
This PR changes the paste behavior to split the paragraphs by a single line break.
This test is running on mac only because we use the mac shortcut to paste: `await tester.pressCmdV()`. We could also add methods in the robot to simulate common shortcuts depending on the platform. For example: `await tester.pressPasteCombo()`.
=> [SuperEditor] Fix pasting multiple lines (Resolves #871)

attributed_text/lib/src/attributed_spans.dart, attributed_text/test/attributed_spans_test.dart
[attributed_text] Fix exception in hasAttributionsWithin. Resolves #1201.
This PR is built on top of https://github.com/superlistapp/super_editor/pull/1202
`hasAttributionsWithin` incorrectly removes attributions while iterating over a `Set`. This causes an exception when looking for multiple attributions at the same time.
This PR changes the method to only remove the attributions after iterating.
=> [attributed_text] Fix exception in hasAttributionsWithin (Resolves #1201)

attributed_text/lib/src/attributed_spans.dart, attributed_text/test/attributed_spans_test.dart
This PR cherry-picks "[attributed_text] Fix exception in hasAttributionsWithin (Resolves #1201) (#1401)" to stable.
=> Cherry-pick "[attributed_text] Fix exception in hasAttributionsWithin (Resolves #1201) (#1401)" to stable

super_editor/example/lib/demos/in_the_lab/feature_action_tags.dart, super_editor/example/lib/demos/in_the_lab/feature_pattern_tags.dart, super_editor/example/lib/demos/in_the_lab/feature_stable_tags.dart, super_editor/example/lib/demos/in_the_lab/popover_list.dart, super_editor/example/lib/main.dart, super_editor/lib/src/core/edit_context.dart, super_editor/lib/src/default_editor/document_caret_overlay.dart, super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart, super_editor/lib/src/default_editor/document_ime/document_ime_interaction_policies.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/lib/src/default_editor/document_layers/attributed_text_bounds_overlay.dart, super_editor/lib/src/default_editor/layout_single_column/_layout.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/attribution_layout_bounds.dart, super_editor/lib/src/infrastructure/content_layers.dart, super_editor/lib/src/infrastructure/documents/document_scaffold.dart, super_editor/lib/src/infrastructure/selection_leader_document_layer.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/super_editor.dart, super_editor/test/infrastructure/content_layers_test.dart, super_editor/test/super_editor/supereditor_selection_test.dart, super_editor/test/super_editor/text_entry/text_test.dart
Fixed tagging NPEs - includes new ContentLayers layer widgets, IME focus policy adjustment (Resolves #1397)
The tangible goal of this PR is to fix issues found with the tagging system in the Example app. Before this PR, the tagging examples were producing NPEs on every character the user entered.
To fix the tagging experience, a few changes were made:
Despite my best attempts to hack the Flutter build order, every time the user inserted a new character into a tag, it would trigger a build timing problem where the caret overlay would try to inspect the document layout before the document layout was run.
I was unable to further hack the Flutter build order to resolve this. At this point, I had to bring some level of new responsibility to the widgets that are displayed as layers.
As of this …
=> Fixed tagging NPEs - includes new ContentLayers layer widgets, IME focus policy adjustment (Resolves #1397)

attributed_text/test/attributed_text_test.dart
Adjusted attributed_text tests to avoid false negatives (Resolves #1392)
=> Adjusted attributed_text tests to avoid false negatives (Resolves #1392)

attributed_text/test/attributed_text_test.dart
Cherry Pick: Adjusted attributed_text tests to avoid false negatives (Resolves #1392) (#1413)
=> Cherry Pick: Adjusted attributed_text tests to avoid false negatives (Resolves #1392) (#1413)

super_editor/lib/src/infrastructure/documents/document_scroller.dart, super_editor/lib/src/super_reader/read_only_document_keyboard_interactor.dart, super_editor/lib/src/super_reader/reader_context.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/test/super_editor/supereditor_test_tools.dart, super_editor/test/super_reader/reader_test_tools.dart
[SuperReader] Migrate to DocumentScroller API. Resolves #1306
https://github.com/superlistapp/super_editor/issues/1288 introduced the `DocumentScroller` API, but it wasn't fully migrated within `SuperReader`.
`SuperReader` already uses a `DocumentScaffold`, which uses `DocumentScrollable` to attach/detach from the scroller.
The only things I found still left to do is to migrate `SuperReaderContext` to take a `DocumentScroller` instead of an `AutoScrollController` and adjust key up/down handlers.
=> [SuperReader] Migrate to DocumentScroller API (Resolves #1306)

super_editor/lib/super_editor.dart
This PR cherry-picks "Export content_layers.dart (#1434)" to stable
=> Cherry-pick "Export content_layers.dart (#1434)" to stable

super_editor/lib/src/infrastructure/content_layers.dart
[SuperEditor] Fix crash in release mode. Resolves #1424.
Running on release mode causes the editor to display only a grey box:
The console shows the following exception:
```console
flutter: LateInitializationError: Local 'result' has not been initialized.
flutter: #0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:197)
flutter: #1      RenderObject.debugNeedsLayout (package:flutter/src/rendering/object.dart:2156)
flutter: #2      ContentLayerState.build (package:super_editor/src/infrastructure/content_layers.dart:845)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5572)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5460)
flutter: #5      StatefulElement.performRebuild …
```
=> [SuperEditor] Fix crash in release mode (Resolves #1424)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/test/super_editor/supereditor_switching_test.dart
[SuperEditor] Remove scroll listener when disposing. Resolves #1117
When switching a `SuperEditor` with a `SuperEditor` (or vice-versa), scrolling  causes the following exception to be displayed at the console: 
```console
════════ Exception caught by foundation library ════════════════════════════════
The following _TypeError was thrown while dispatching notifications for ScrollPositionWithSingleContext:
type 'Null' is not a subtype of type 'DocumentLayout' in type cast
#0      SuperReaderState._createReaderContext.<anonymous closure> (package:super_editor/src/super_reader/super_reader.dart:267:59)
#1      SuperReaderContext.documentLayout (package:super_editor/src/super_reader/reader_context.dart:30:58)
#2 …
```
=> [SuperEditor][SuperReader] Remove scroll listener when disposing (Resolves #1117)

super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/test/super_editor/supereditor_floating_cursor_test.dart
[SuperEditor][iOS] Fix floating cursor crash with expanded selections. Resolves #1174
1. Double tap to select a word
2. Press and hold the spacebar
The editor shows the floating cursor and an exception is displayed in the console.
```console
════════ Exception caught by foundation library ════════════════════════════════
The following _TypeError was thrown while dispatching notifications for FloatingCursorController:
Null check operator used on a null value
#0      _IosDocumentTouchEditingControlsState._onFloatingCursorChange (package:super_editor/src/infrastructure/platforms/ios/ios_document_controls.dart:233:42)
#1      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
#2 …
```
=> [SuperEditor][iOS] Fix floating cursor crash with expanded selections (Resolves #1174)

super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
[SuperTextField][Mac] Allow selector handlers configuration. Resolves #1439
Currently, we allow apps to provide custom selector handlers to `SuperEditor` but not for `SuperTextField`.
This PR exposes `selectorHandlers` in `SuperTextField`'s public API.
=> [SuperTextField][Mac] Allow selector handlers configuration (Resolves #1439)

attributed_text/lib/src/attributed_spans.dart, super_editor/lib/src/default_editor/attributions.dart, super_editor/test/super_editor/supereditor_gestures_test.dart, super_editor/test/super_editor/text_entry/links_test.dart
Tap to open multiple links in the same paragraph (Resolves #1426)
The root problem is that when looking up attributions in `AttributionSpans` at a specific location, we weren't differentiating between different URLs in link attributions. This is because the attribution differentiation was based only on the attribution `id`, which is always `link` for a link attribution.
I changed the attribution comparison to compare the overall attribution instead of just the attribution ID. This might break some other styling behaviors, but all the tests pass, so we'll have to handle those situations when they come up.
=> Tap to open multiple links in the same paragraph (Resolves #1426)

super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/test/super_editor/supereditor_floating_cursor_test.dart
This PR cherry-picks "[SuperEditor][iOS] Fix floating cursor crash with expanded selections (Resolves #1174) (#1450)" to stable
=> Cherry-pick "[SuperEditor][iOS] Fix floating cursor crash with expanded selections (Resolves #1174) (#1450)" to stable

super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
This PR cherry-picks "[SuperTextField][Mac] Allow selector handlers configuration (Resolves #1439) (#1444)" to stable
=> Cherry-pick "[SuperTextField][Mac] Allow selector handlers configuration (Resolves #1439) (#1444)" to stable

super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example/lib/demos/in_the_lab/popover_list.dart, super_editor/lib/src/core/edit_context.dart, super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/popovers.dart, super_editor/lib/super_editor.dart, super_editor/test/super_editor/text_entry/text_test.dart
[ExampleApp] Fix link popover. Resolves #1440
The implementation of `performSelectors` broke the tag popover demos. The fix for that ended up breaking the  url popover in the example app.
For selectors work, we need to prevent default Flutter shortcuts that perform focus traversal. We currently do that by using an `Actions` widget in `SuperEditor` and `SuperTextField`. However, when the editor doesn't have primary focus, which is the case when a popover is displayed, `SuperEditor` actions are ignored.
To fix that, the popovers also need to prevent these shortcuts. To make it easier for app, this PR introduces a `SuperEditorPopover` widget, which adds an `Actions` widget in the tree with the intents that need to be blocked.
Another issue is that pressing ENTER on mac generates a …
=> [ExampleApp] Fix link popover (Resolves #1440)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/test/super_editor/supereditor_floating_cursor_test.dart
[SuperEditor][iOS] Fix exception when moving floating cursor between paragraphs. Resolves #1449
Moving the floating cursor between paragraphs causes an exception when the selection sits at an offset bigger than the newly selected paragraph length.
The cause is that the IME generates non-text deltas while the floating cursor is moving. After the selection already changed to the other paragraph, we receive a non-text delta for the previously selected paragraph. This causes an IME mapping error.
This PR changes `DocumentImeInputClient` to ignore deltas while the floating cursor is being displayed.
Related flutter ticket: https://github.com/flutter/flutter/issues/134989
=> [SuperEditor][iOS] Fix exception when moving floating cursor between paragraphs (Resolves #1449)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/test/super_editor/supereditor_floating_cursor_test.dart
This PR cherry-picks "[SuperEditor][iOS] Fix exception when moving floating cursor between paragraphs (Resolves #1449) (#1471)" to stable.
=> Cherry-pick "[SuperEditor][iOS] Fix exception when moving floating cursor between paragraphs (Resolves #1449) (#1471)" to stable

super_editor/lib/src/default_editor/document_scrollable.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart
Lock scrolling when content fits within available space (Resolves #1409)
=> Cherry-Pick: [SuperEditor][SuperReader] - Lock scrolling when content fits within available space (Resolves #1409) (#1421)

golden_runner/lib/src/commands.dart
[golden_runner] Await on addStream. Resolves #1479
Trying to use the golden_runner is throwing the following exception: 
```console
Unhandled exception:
Bad state: StreamSink is already bound to a stream
#0      _StreamSinkImpl.addStream (dart:io/io_sink.dart:166:7)
#1      _StdSink.addStream (dart:io/stdio.dart:361:55)
#2      _runProcess (package:golden_runner/src/commands.dart:322:10)
<asynchronous suspension>
#3      GoldenTestCommand.run (package:golden_runner/src/commands.dart:98:5)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      main (file:///Users/rutviktak/flutter_projects/mc/super_editor/golden_runner/bin/goldens.dart:13:5)
<asynchronous suspension>
```
It seems that the example on the dart …
=> [golden_runner] Await on addStream (Resolves #1479)

golden_runner/lib/src/commands.dart
This PR cherry-picks "[golden_runner] Await on addStream (Resolves #1479) (#1482)" to stable.
=> Cherry-pick "[golden_runner] Await on addStream (Resolves #1479) (#1482)" to stable

super_editor/example/lib/demos/supertextfield/_mobile_textfield_demo.dart, super_editor/lib/src/infrastructure/flutter/text_selection.dart, super_editor/lib/src/super_textfield/android/_user_interaction.dart, super_editor/lib/src/super_textfield/ios/_user_interaction.dart, super_editor/test/super_textfield/android/super_textfield_android_selection_test.dart, super_editor/test/super_textfield/ios/super_textfield_ios_selection_test.dart
Add iOS tap in empty space to show toolbar, Android long-press in empty space to show toolbar. (Resolves #1472)
=> Add iOS tap in empty space to show toolbar, Android long-press in empty space to show toolbar. (Resolves #1472)

super_editor/example/lib/demos/supertextfield/_mobile_textfield_demo.dart, super_editor/lib/src/infrastructure/flutter/text_selection.dart, super_editor/lib/src/super_textfield/android/_user_interaction.dart, super_editor/lib/src/super_textfield/ios/_user_interaction.dart, super_editor/test/super_textfield/android/super_textfield_android_selection_test.dart, super_editor/test/super_textfield/ios/super_textfield_ios_selection_test.dart
Cherry Pick: Add iOS tap in empty space to show toolbar, Android long-press in empty space to show toolbar. (Resolves #1472) (#1476)
=> Cherry Pick: Add iOS tap in empty space to show toolbar, Android long-press in empty space to show toolbar. (Resolves #1472) (#1476)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
[SuperEditor][web] Defer to browser toolbar and magnifier. Resolves #1390
On web, both our toolbar and the browser text selection toolbar are displayed.
This PR changes `SuperEditor` to avoid rendering the toolbar and drag handles on web on both Android and iOS:
https://github.com/superlistapp/super_editor/assets/7597082/b3c32b5e-7149-4979-a963-49b01652fdd8
However, the Android drag handles aren't positioned exactly at the correct position.
https://github.com/superlistapp/super_editor/assets/7597082/358422a4-1114-4293-a9c3-8a299f9d9915
=> [SuperEditor][web] Defer to browser toolbar and magnifier (Resolves #1390)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
This PR cherry-picks "[SuperEditor][web] Defer to browser toolbar and magnifier (Resolves #1390) (#1483)" to stable.
=> Cherry-pick "[SuperEditor][web] Defer to browser toolbar and magnifier (Resolves #1390) (#1483)" to stable

.github/workflows/cherry_pick_to_stable.yaml
Cherry Pick: a couple GitHub action commits, working on auto-cherry-picking
=> Cherry Pick: a couple GitHub action commits, working on auto-cherry-picking

super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/infrastructure/text_field_scroller.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/lib/src/super_textfield/super_textfield_context.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
Created a SuperTextFieldContext with a BuildContext and a TextFieldScroller - passed it key handlers (Resolves #1487)
=> Created a SuperTextFieldContext with a BuildContext and a TextFieldScroller - passed it key handlers (Resolves #1487)

.github/workflows/cherry_pick_to_stable.yaml
The cherry pick GitHub Action wasn't working as intended. I couldn't seem to get the cherry pick action's variables to interpolate.
I ran about a million different attempts over at https://github.com/matthew-carroll/experiment_ci_cherry_pick_pr
Eventually I decided the only way to interpolate the names we want for things like the branch, title, body, etc, was to define our own environment variables, where we pull the desired information out of the GitHub payload. That's what this PR does.
=> Fix cherry_pick_to_stable.yaml workflow (Resolves #1513)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart
[SuperEditor][SuperReader][Android] Fix scrolling with an ancestor Scrollable. Resolves #1535.
When the editor or reader is inside a `CustomScrollview`, trying to drag is opening the software keyboard and changing the selection.
The root cause is the long press to select handling. When the user taps down we start a timer to track a long press. Dragging after the tap down starts a pan gesture and we cancel the timer. However,  if we have an ancestor `Scrollable`, dragging starts a pan gesture on the `Scrollable`, not in the editor/reader. Because of that, the timer still fires after the timeout.
This PR adds a guard clause to avoid doing a long press if we are scrolling.
=> [SuperEditor][SuperReader][Android] Fix scrolling with an ancestor Scrollable (Resolves #1535)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart
This PR cherry-picks "[SuperEditor][SuperReader][Android] Fix scrolling with an ancestor Scrollable (Resolves #1535) (#1536)" to stable.
=> Cherry-pick "[SuperEditor][SuperReader][Android] Fix scrolling with an ancestor Scrollable (Resolves #1535) (#1536)" to stable

super_editor/lib/src/super_textfield/super_textfield.dart
Fixes https://github.com/superlistapp/super_editor/issues/1543
=> SuperTextField: propagate blinkTimingMode to platform implementations

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart
[SuperEditor][SuperReader][Android] Fix long-press firing after scrolling and releasing the pointer. Resolves #1535
When the editor or reader is inside a CustomScrollview, trying to drag is opening the software keyboard and changing the selection. This was partially solved in https://github.com/superlistapp/super_editor/pull/1536. However one issue remained:
Starting a scroll gestures and the releasing the pointer is still causing the issue. The cause is that, when the timer fires, we aren't scrolling anymore.
To fix that, this PR cancels the long-press timer as soon as the user starts the scrolling gesture.
I kept the existing test, which simulates the user dragging and holding down the pointer, and added another one simulating the user starting a drag gesture and then releasing the …
=> [SuperEditor][SuperReader][Android] Fix long-press firing after scrolling and releasing the pointer (Resolves #1535)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart
Cherry Pick: [SuperEditor][SuperReader][Android] Fix long-press firing after scrolling and releasing the pointer (Resolves #1535) (#1540)
=> Cherry Pick: [SuperEditor][SuperReader][Android] Fix long-press firing after scrolling and releasing the pointer (Resolves #1535) (#1540)

super_editor/example/pubspec.yaml, super_editor/pubspec.yaml
Fix Linux golden test dirty paint failures by upgrading follow_the_leader (Resolves #1490)
Tests are still failing, but these are legitimate failures related to mobile handles, toolbar, etc. They'll be fixed in other work coming up immediately.
=> Fix Linux golden test dirty paint failures by upgrading follow_the_leader (Resolves #1490)

README.md
Add dependency_overrides snippet
Sometimes we make changes breaking changes in packages like super_text_layout or attributed_text. When it happens, depending on super_editor from pub causes compilation errors.
This PR adds a snippet to the README explaining how to fix the compilation errors by overriding the dependencies.
=> Add dependency_overrides snippet

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart
Fix: Caret not blinking on iOS after dragging to scroll (Resolves #1549)
The root cause was that we were disabling blinking on touch down, and on pan start, but we weren't re-enabling blinking on pan end in the case that the user was scrolling.
There wasn't any great way to add tests for this fix because we purposefully prevent caret blinking during tests so that `pumpAndSettle()` doesn't throw an exception.
=> Fix: Caret not blinking on iOS after dragging to scroll (Resolves #1549)

super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/test_goldens/editor/mobile/mobile_selection_test.dart
Use the right platform test runner for golden selection tests (Resolves #1561)
Our golden tests for text selection allowed for platform customization, but that platform selection wasn't being honored by the choice of test runner. The tests were always running on Android. This PR selects different test runners based on the desired gesture mode.
=> Use the right platform test runner for golden selection tests (Resolves #1561)

super_editor/example/lib/main_super_editor.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/test/super_editor/mobile/super_editor_ios_overlay_controls_test.dart
Fix: iOS and magnifier not appearing when expected (Resolves #1550)
There were a couple places where we weren't triggering the hiding and showing of the iOS floating toolbar and magnifier appropriately. This PR fixes that.
This PR also adds tests for their appearance under various conditions.
This PR also adds a barebones `SuperEditor` demo so that we can verify default `SuperEditor` behavior in addition to the customized behavior in the Example app.
=> Fix: iOS and magnifier not appearing when expected (Resolves #1550)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/infrastructure/platforms/mobile_documents.dart, super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart, super_editor/test/super_editor/mobile/super_editor_ios_selection_test.dart
Added temporary hack to disable long-press for Superlist (Relates to #1547)
=> Added temporary hack to disable long-press for Superlist (Relates to #1547)

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/test/super_editor/mobile/super_editor_ios_overlay_controls_test.dart
Fixed tap to show toolbar on iOS when tapping on caret a second time (Resolves #1567)
There were a few things that lead to this issue:
- The toolbar focal point layer was explicitly ignoring collapsed selections, now it places a leader when the selection is collapsed, too.
- The check for tapping on the same selection was giving false negatives due to differences in text affinity based on where the user taps. Now we use a different comparison method to avoid those mismatches.
- We didn't have a test for this, as far as I could tell, so I added one. However, this new test was passing even before I made the other changes in this PR. Therefore, this test is probably useless, but I can't figure out why.
=> Fixed tap to show toolbar on iOS when tapping on caret a second time (Resolves #1567)

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/lib/src/default_editor/super_editor.dart
Fix: reporting IME geometry crashes when  is true in SuperEditor, caret doesn't blink when placed by 'autofocus' in SuperEditor (Resolves #1566)
One of the bugs is that with `autofocus` `true`, we apparently attempt to report IME geometry before the associated widget has run layout. I'm not sure why this is coming up now. Perhaps we never tried using `autofocus` since we implemented reporting IME geometry. I added a check to only report geometry if we have a layout size.
Also, when using `autofocus`, the caret appears immediately, but doesn't blink. To solve that, I changed the initial caret blinking `bool` in the controller from `false` to `true`. That might have unintended consequences, but I wasn't sure. It solved the blink problem without causing any obvious other problems. We should …
=> Fix: reporting IME geometry crashes when  is true in SuperEditor, caret doesn't blink when placed by 'autofocus' in SuperEditor (Resolves #1566)

super_editor/.run/Super Text Field (debug).run.xml, super_editor/example/lib/main_super_text_field.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/infrastructure/text_field_border.dart, super_editor/lib/src/super_textfield/super_textfield_context.dart, super_editor/lib/super_editor.dart, super_editor/lib/super_text_field.dart, super_editor/test/super_textfield/mac/super_textfield_mac_selectors_test.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
By default, `SuperTextField` on Mac now blocks all key events and sends them directly to the OS, in case they need to be turned into selectors. Apps can alter this behavior by placing higher priority key handlers above that one, or completely replacing the key handlers in the text field.
By forcibly bypassing all Flutter focus nodes, key events like ESC will go directly to the OS, generate a selector, like "cancel operation", which will be sent to the IME and received by the text field.
`SuperTextField` has a map of default selector behaviors. **If the defaults should be changed, please let me know.**
Apps can customize selector actions by providing their own entries in the selector action map. They can add to the default actions, or completely replace the default actions.
=> Added SuperTextField entrypoint, includes Mac OS selectors and Actions example

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart, super_editor/test/super_reader/reader_test_tools.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart, super_editor/test/test_tools.dart
[SuperEditor][SuperReader][Android] Fix scroll physics. Resolves #1539
On Android, we are noticing underscroll/overscroll with the editor being pinned at the position where the drag ended:
https://github.com/superlistapp/super_editor/assets/6467808/1f16b98d-4c38-4c32-9d30-108f664220a3
Android uses `ClampingScrollPhysics`, so it shouldn't even allow for underscroll/overscroll. It seems that the way we handle scrolling doesn't honor the scroll physics correctly. 
I replaced the call to `jumpTo` with a call to `pointerScroll` and the issue seems to be solved: 
[android.webm](https://github.com/superlistapp/super_editor/assets/7597082/57b339f5-a84c-466d-bcdd-bd013e58c94a)
The difference between `jumpTo` and `pointerScroll` is that `pointerScroll` calls `forcePixels` clamping the jump offset …
=> [SuperEditor][SuperReader][Android] Fix scroll physics (Resolves #1539)

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
[SuperEditor][SuperReader][iOS] Fix horizontal text selection inside a CustomScrollView. Resolves #1610
Performing a horizontal drag isn't changing the selection when the editor is inside a `CustomScrollView`.
The reason seems to be that the `VerticalDragGestureRecognizer` is losing in the gesture arena when inside an ancestor scrollable. Adding a `HorizontalDragGestureRecognizer` to the `RawGestureDetector` seems to fix the issue.
This PR doesn't add tests because so far I wasn't able to write a failing test with the current implementation. I'll file a ticket to write tests for this.
https://github.com/superlistapp/super_editor/assets/7597082/7bda2411-6374-4631-a5cf-81c23cde0879
=> [SuperEditor][SuperReader][iOS] Fix horizontal text selection inside a CustomScrollView (Resolves #1610)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart, super_editor/test/super_reader/reader_test_tools.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart, super_editor/test/test_tools.dart
This PR cherry-picks "[SuperEditor][SuperReader][Android] Fix scroll physics (Resolves #1539) (#1541)" to stable.
=> Cherry-pick "[SuperEditor][SuperReader][Android] Fix scroll physics (Resolves #1539) (#1541)" to stable

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart
This PR cherry-picks "[SuperEditor][SuperReader][iOS] Fix horizontal text selection inside a CustomScrollView (Resolves #1610) (#1611)" to stable.
=> Cherry-pick "[SuperEditor][SuperReader][iOS] Fix horizontal text selection inside a CustomScrollView (Resolves #1610) (#1611)" to stable

super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/test/super_editor/supereditor_content_insertion_test.dart, super_editor/test/super_editor/supereditor_gestures_test.dart, super_editor/test/super_textfield/super_textfield_test.dart, super_editor/test/super_textfield/super_textfield_theme_test.dart
[SuperTextField][mobile] Migrate popover toolbar to OverlayPortal (Resolves #1602)
Currently, the mobile toolbars are displayed in the app `Overlay`. Because of that, it doesn't have access to  `InheritedWidgets` placed below `MaterialApp`. 
As a result, if an app adds a `Theme` widget above `SuperTextField`, the `SuperTextField` uses this `Theme`, but the popover toolbar uses the `MaterialApp`'s theme.
This PR changes the popover toolbars to be displayed in an `OverlayPortal` instead of an `Overlay`. By doing so, the popovers "see" the same `InheritedWidgets` that the `SuperTextField` sees.
In the tests, I had to use the platform textfields directly, as `SuperTextField` doesn't expose the `popoverToolbarBuilder` in its public API.
I also noticed that the iOS textfield is always using the …
=> [SuperTextField][mobile] Migrate popover toolbars to OverlayPortal (Resolves #1602)

super_editor/test/infrastructure/content_layers_test.dart
This removes unused parameters from some private classes in `content_layers_test.dart`, since there is currently a bug in `dart fix --apply` where it will remove the parameters that are unused, but not the associated members.
- https://github.com/dart-lang/sdk/issues/54190
- https://github.com/flutter/tests/pull/316
=> Remove unused parameters on private classes

super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/lib/src/test/super_reader_test/super_reader_robot.dart, super_editor/test/super_editor/mobile/super_editor_ios_selection_test.dart, super_editor/test/super_reader/mobile/super_reader_ios_selection_test.dart, super_editor/test/test_tools.dart
[SuperEditor][iOS] Add tests for drag to select. Resolves #1613
It was reported in https://github.com/superlistapp/super_editor/issues/1610 that performing a horizontal drag isn't changing the selection. https://github.com/superlistapp/super_editor/pull/1611 fixed the bug, but didn't include any tests.
This PR adds test for horizontal dragging inside a `CustomScrollView`. During the tests I got some failures because dragging can cause an `upstream` selection affinity.  I added a custom `Matcher` to compare the selections, ignoring the affinity. We have something similar to this in `NodePosition.isEquivalentTo`. 
Initially, these tests weren't failing, even without the fix. The reason is that `dragSelectDocumentFromPositionByOffset` always uses `PointerDeviceKind.mouse` as the device kind …
=> [SuperEditor][iOS] Add tests for drag to select (Resolves #1613)

super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/test/super_editor/text_entry/links_test.dart
[SuperEditor] Linkify on Enter. Resolves #1600 
Currently, we only linkify an URL if the user types a space after it. So, typing an URL and pressing ENTER isn't linkifying the URL.
This PR changes the `LinkifyReaction` to look for `SubmitParagraphIntention` and `SplitParagraphIntention`, so it can linkify the URL on ENTER.  As both `SubmitParagraphIntention` and `SplitParagraphIntention` don't have the node id, I had to look at the next change in the change list. We could also modify those objects to store the node id.
To also make it work for list items and tasks,  this PR adds the `SplitListItemIntention` and `SplitTaskIntention` to follow the same pattern.
https://github.com/superlistapp/super_editor/assets/7597082/b8b95da8-8595-4728-9bc2-ac4abc5778e5
We have some duplication on the …
=> [SuperEditor] Linkify on Enter (Resolves #1600)

super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/lib/src/test/super_reader_test/super_reader_robot.dart, super_editor/test/super_editor/mobile/super_editor_ios_selection_test.dart, super_editor/test/super_reader/mobile/super_reader_ios_selection_test.dart, super_editor/test/test_tools.dart
This PR cherry-picks "[SuperEditor][iOS] Add tests for drag to select (Resolves #1613) (#1627)" to stable.
=> Cherry-pick "[SuperEditor][iOS] Add tests for drag to select (Resolves #1613) (#1627)" to stable

super_editor/example/lib/demos/example_editor/_toolbar.dart
[DemoApp] Fix link visual styles when applying by the toolbar. Resolves #1632
Applying a link to a text using the editor toolbar isn't updating the layout immediately.
https://github.com/superlistapp/super_editor/assets/7597082/ec2eb472-e447-4c88-8d64-5444acdb40eb
The issue is on the demo app itself, which is directly applying the link attribution instead of using the request/command pipeline.
This PR changes the demo app to apply the links by executing a `AddTextAttributionsRequest`.
=> [DemoApp] Fix link visual styles when applying by the toolbar (Resolves #1632)

super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/src/super_textfield/styles.dart, super_editor/lib/src/test/super_reader_test/super_reader_inspector.dart, super_editor/test/super_editor/supereditor_attributions_test.dart, super_editor/test/super_editor/test_documents.dart, super_editor/test/super_reader/superreader_attributions_test.dart, super_editor/test/super_textfield/super_textfield_attributions_test.dart, super_editor/test/super_textfield/super_textfield_inspector.dart
[SuperReader][SuperTextField] Applies color attribution on textstyle created through default style builder (Resolves #1579)
Colored attributions set on text passed to `SuperReader` and `SuperTextField` aren't applied to the final rendered text within the document. 
With following attributed text passed to both `SuperReader` and `SuperTextField`, 
```
AttributedText(
'My text colored in orange',
AttributedSpans(
attributions: const [
SpanMarker(
attribution: ColorAttribution(
Colors.orange,
),
offset: 0,
markerType: SpanMarkerType.start,
),
SpanMarker(
attribution: ColorAttribution(
Colors.orange,
),
offset: 24,
markerType: SpanMarkerType.end,
),
],
),
),
```
<br>
`SuperReader` output:
<br>
<br>
`SuperTextField` output(on Desktop):
<br>
<br>
Turns out that the `readOnlyDefaultStyleBuilder` …
=> [SuperReader][SuperTextField] Applies color attribution on textstyle created through default style builder (Resolves #1579)

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/infrastructure/multi_tap_gesture.dart, super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/test/super_editor/desktop/super_editor_desktop_selection_test.dart
Fixed double-tap and drag by word upstream (Resolves #1480)
The root issue is that our double tap selection behavior was always treating the start of a word as the base of a selection. That works when dragging downstream. However, when dragging upstream, the base of the selection should be the end of the word, not the beginning.
This PR also adds a test tool to simulate a double tap and drag. Creating this test tool uncovered some kind of issue within our multi-tap gesture recognizer. I made a change that avoids the crash, but I don't have any idea why it's needed. The problem is tied to Flutter's gesture arena protocol, which I still don't understand.
=> Fixed double-tap and drag by word upstream (Resolves #1480)

.github/workflows/pr_validation.yaml
[Infrastructure] Store golden test failures as workflow artifacts. Resolves #1658
Currently, if a golden test fails only on CI, we have no way to inspect the failure because we cannot access the generated images.
This PR adds a step to the `test_goldens_super_editor` and `test_super_editor_markdown` jobs to store the failures as as artifacts in the test workflow.
If a golden test fails, a `golden-failures.zip` will be generated containing all images that are inside all "failures" directories.
It's possible to configure a retention period. If not set, it uses the retention limit set by the repository, organization, or enterprise
=> [Infrastructure] Store golden test failures as workflow artifacts (Resolves #1658)

super_editor/lib/src/default_editor/document_scrollable.dart, super_editor/lib/src/infrastructure/flutter/cupertino_scrollbar.dart, super_editor/lib/src/infrastructure/flutter/material_scrollbar.dart, super_editor/lib/src/infrastructure/flutter/scrollbar.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_editor/supereditor_gestures_test.dart, super_editor/test/super_reader/super_reader_gestures_test.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart
[SuperEditor][SuperTextField][Desktop] Fix trackpad and scrollbar scrolling. Resolves #1628
There are two scrolling issues:
1. Dragging with two fingers doesn't cause the content to scroll.
We had a similar issue with `SuperEditor` in the past, which was resolved in https://github.com/superlistapp/super_editor/pull/780.  This PR applies the same solution applied to `SuperTextField`.
2. Dragging a scrollbar doesn't cause the content to scroll.
This is also an issue on `SuperEditor`. Flutter's `Scrollbar` uses the `ScrollPosition`'s scroll physics to determine whether or not the user gesture will scroll the content. As we are using `NeverScrollableScrollPhysics`, the user is prevented from dragging the scrollbar. We can't configure the scroll physics of a `Scrollbar`.
The only solution I …
=> [SuperEditor][SuperTextField][Desktop] Fix trackpad and scrollbar scrolling (Resolves #1628)

super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/test/super_textfield/super_textfield_caret_test.dart
Fix caret visible during expanded selection in SuperTextField for iOS and Android (Resolves #1671)
=> Fix caret visible during expanded selection in SuperTextField for iOS and Android (Resolves #1671)

super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/test/super_editor_markdown_test.dart
Make Markdown deserialization HTML symbol encoding optional (Resolves 1591)
=> Make Markdown deserialization HTML symbol encoding optional (Resolves 1591)

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/keyboard.dart, super_editor/lib/src/infrastructure/platforms/platform.dart, super_editor/lib/src/infrastructure/text_input.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_keyboard_interactor.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_editor/supereditor_copy_and_paste_test.dart, super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart, super_editor/test/super_reader/super_reader_keyboard_test.dart, super_editor/test/test_runners.dart
[SuperEditor] Enable Mac shortcuts for iOS. Resolves #1609
Mac shortcuts, like cmd + c, don't execute for iOS. The reason is that the `isPrimaryShortcutKeyPressed` getter only checks if the current platform is mac.
This PR changes `isPrimaryShortcutKeyPressed` to consider iOS and also enable other shortcuts that are running for mac only.
=> [SuperEditor] Enable Mac shortcuts for iOS (Resolves #1609)

super_editor/lib/src/default_editor/document_hardware_keyboard/document_physical_keyboard.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart, super_editor/test/test_runners.dart
[SuperEditor] Don't execute keyboard handlers without primary focus. Resolves #183
In the demo app, pressing ENTER on the toolbar's URL field causes a new line to be inserted, instead of applying the link attribution.
The cause is that the editor keyboard handlers (`enterToInsertBlockNewline` in this case) are running even if the editor doesn't have primary focus. This prevents the key event to bubble up to the OS to generate an `onPerformAction` call.
This PR changes the shortcut system to avoid calling any keyboard handler if the editor doesn't have primary focus.
=> [SuperEditor] Don't execute keyboard handlers without primary focus (Resolves #183)

super_editor/lib/src/default_editor/document_hardware_keyboard/document_physical_keyboard.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart, super_editor/test/test_runners.dart
This PR cherry-picks "[SuperEditor] Don't execute keyboard handlers without primary focus (Resolves #183) (#1679)" to stable.
=> Cherry-pick "[SuperEditor] Don't execute keyboard handlers without primary focus (Resolves #183) (#1679)" to stable

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/keyboard.dart, super_editor/lib/src/infrastructure/platforms/platform.dart, super_editor/lib/src/infrastructure/text_input.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_keyboard_interactor.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_editor/supereditor_copy_and_paste_test.dart, super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart, super_editor/test/super_reader/super_reader_keyboard_test.dart, super_editor/test/test_runners.dart
This PR cherry-picks "[SuperEditor] Enable Mac shortcuts for iOS (Resolves #1609) (#1678)" to stable while still using `RawKeyEvent`.
=> [SuperEditor] Enable Mac shortcuts for iOS (Resolves #1609) (#1678) (stable)

super_editor/README.md, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/demos/in_the_lab/in_the_lab_scaffold.dart, super_editor/example/lib/demos/in_the_lab/selected_text_colors_demo.dart, super_editor/example/lib/demos/interaction_spot_checks/spot_check_scaffold.dart, super_editor/example/lib/demos/styles/demo_doc_styles.dart, super_editor/example/lib/marketing_video/main_marketing_video.dart, super_editor/lib/src/core/styles.dart, super_editor/lib/src/default_editor/blockquote.dart, super_editor/lib/src/default_editor/layout_single_column/_presenter.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/test/super_editor/components/block_node_test.dart, super_editor/test/super_editor/components/blockquote_test.dart, super_editor/test/super_editor/components/list_items_test.dart, super_editor/test/super_editor/supereditor_component_selection_test.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_editor/supereditor_style_test.dart, super_editor/test_goldens/editor/supereditor_text_layout_test.dart, super_editor/test_goldens/editor/text_entry/super_editor_composing_region_underline_test.dart, website/lib/homepage/featured_editor.dart
[SuperEditor] Add constants for style metadata. Resolves #825
Currently, we use hardcoded strings for the stylesheet properties.
This PR adds constants to the available properties, so developers can use intelisense to discover them.
We could also add constants for node's metadata.
=> [SuperEditor] Add constants for style metadata (Resolves #825)

super_editor/test/super_textfield/attributed_text_editing_controller_test.dart, super_text_layout/lib/src/text_layout.dart, super_text_layout/lib/src/text_underline_layer.dart
[SuperEditor] Make composing region underline continuous. Resolves #1684
Steps To Reproduce
1. Go to SuperEditor demo
2. Use Japanese-Romanji keyboad layout
3. Place the selection in the text (not specific position needed)
4. In the physical English keyboard, type "as"
With these steps the underlines aren't aligned:
We use `getBoxesForSelection` to determine the position of the underline, which internally calls a `RenderParagraph` method of the same name. This method takes a `boxHeightStyle` parameter, which the default value (`BoxHeightStyle.tight`) has the following doc:
```dart
/// Provide tight bounding boxes that fit heights per run. This style may result
/// in uneven bounding boxes that do not nicely connect with adjacent boxes.
```
This is how it's rendered with the other styles: …
=> [SuperEditor] Make composing region underline continuous (Resolves #1684)

super_editor/test/super_textfield/attributed_text_editing_controller_test.dart, super_text_layout/lib/src/text_layout.dart, super_text_layout/lib/src/text_underline_layer.dart
This PR cherry-picks "[SuperEditor] Make composing region underline continuous (Resolves #1684) (#1688)" to stable.
=> Cherry-pick "[SuperEditor] Make composing region underline continuous (Resolves #1684) (#1688)" to stable

super_editor/example/lib/main.dart, super_editor/lib/src/super_textfield/android/_editing_controls.dart, super_editor/lib/src/super_textfield/android/_user_interaction.dart, super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/infrastructure/text_scrollview.dart, super_editor/lib/src/super_textfield/ios/_user_interaction.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/super_textfield/super_text_field_keys.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/test/super_textfield/android/super_textfield_android_scrolling_test.dart, super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart, super_editor/test/super_textfield/ios/super_textfield_ios_selection_test.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart, super_editor/test/super_textfield/super_textfield_inspector.dart, super_editor/test/super_textfield/super_textfield_robot.dart, super_text_layout/lib/src/caret_layer.dart
Fixed SuperTextField single-line auto-scroll and scrolling bugs on iOS and Android (Resolves #1673)
There were a number of problems with iOS and Android single-line `SuperTextField`s:
- When dragging to the edge to auto-scroll, when the user let go, the selection would jump somewhere else.
- On Android, auto-scrolling to the right would almost immediately jump to the end of the text.
- Pressing and dragging anywhere would place and drag the caret - the caret should only drag when the user presses near it.
To test these behaviors, I added a number of test tools for `SuperTextField`.
The root issue was mostly about the timing of certain behaviors. Adjusting when certain things happen was able to resolve these glitches. There were also a few logical errors in the code - for example, when we …
=> Fixed SuperTextField single-line auto-scroll and scrolling bugs on iOS and Android (Resolves #1673)

super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/test/infrastructure/popover_test.dart
This PR addresses the following comments from #1538 
> Can you clarify "to the bottom" of what? screen? boundary? button?
https://github.com/superlistapp/super_editor/pull/1538#discussion_r1437425389
> In addition to earlier comments, I checked out this branch so I could work on paragraph alignment. I discovered that we're displaying too many alignment options in the drop down. This is because we're looping through all TextAlign values which means we're showing both left and start, and right and end. So we're essentially repeating equivalent options.
https://github.com/superlistapp/super_editor/pull/1538#issuecomment-1871473867
=> Updates for #1538

super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/test/infrastructure/popover_test.dart
This PR cherry-picks "Updates for #1538 (#1717)" to stable.
=> Cherry-pick "Updates for #1538 (#1717)" to stable

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_editor/supereditor_selection_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart
[SuperEditor][Desktop] Keep selection base while dragging. Resolves #1393
In the animated component demo, dragging up from a task near the bottom causes the selection base to change while the user is dragging:
https://github.com/superlistapp/super_editor/assets/7597082/fbc8a6d1-23a7-4f0a-90a3-2121c860d6a5
Currently, on each pan update, we re-compute the whole selection by checking the selection in the drag region. This is a problem if a component resizes itself, because, at the start of the drag gestures, the offset points to a component and while the user is dragging and the components are resizing, the starting offset might point to another component.
To fix that, this PR caches the starting selection base and reuses-it at each pan update. This isn't a problem on mobile, because when …
=> [SuperEditor][Desktop] Keep selection base while dragging (Resolves #1393)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart
[SuperEditor][Android] Fix drag handle flashing on double tap. Resolves #1690
Upon double tap, the drag handle quickly flashes at the top-left corner of the screen:
https://github.com/superlistapp/super_editor/assets/31278849/92af387f-a242-48e0-a1f0-0995851b280e
This happens because of the following:
- The `TapSequenceGestureRecognizer` reports both `onTapDown` and `onDoubleTapDown` (as expected), so we first show the collapsed drag handle, then we hide the collapsed drag handle and show the expanded handles.
- The `Follower` is configured to `showWhenUnlinked` (because it defaults to `true`), so when the `Leader` is unlinked, it's placed at the top-left corner. 
- The collapsed handle uses a `AnimatedOpacity` to fade in and out.
So, on double tap, the drag handle is positioned at the …
=> [SuperEditor][Android] Fix drag handle flashing on double tap (Resolves #1690)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart
[SuperEditor][Android] Make selection focal point debug visuals hidden by default (Resolves #1722)
On Android, dragging a handle is causing a red dot to appear. 
https://github.com/superlistapp/super_editor/assets/6467808/57f75372-e2a1-4360-b456-e8d3b43157e8
This is because we are always adding a debug paint information.
This PR adds a `showDebugPaint` to control whether or not we want that debug information.
=> [SuperEditor][Android] Make selection focal point debug visuals hidden by default (Resolves #1722)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart
This PR cherry-picks "[SuperEditor][Android] Fix drag handle flashing on double tap (Resolves #1690) (#1699)" to stable.
=> Cherry-pick "[SuperEditor][Android] Fix drag handle flashing on double tap (Resolves #1690) (#1699)" to stable

super_editor/lib/src/default_editor/document_gestures_touch_android.dart
This PR cherry-picks "[SuperEditor][Android] Make selection focal point debug visuals hidden by default (Resolves #1722) (#1725)" to stable.
=> Cherry-pick "[SuperEditor][Android] Make selection focal point debug visuals hidden by default (Resolves #1722) (#1725)" to stable

super_editor/lib/src/default_editor/document_ime/document_ime_interaction_policies.dart, super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
[SuperEditor][SuperTexField] Clear composing region after losing focus. Resolves #1689
When the editor/textfield has a composing region, focusing another widget doesn't cause the composing region to be cleared. This results in the composing region underline to remain visible:
https://github.com/superlistapp/super_editor/assets/31278849/ed204ea7-16fa-4f0b-bf1b-035f303a4c22
This PR changes both `SuperTextField` and `SuperEditor` to clear the composing region when losing focus. In `SuperEditor`, maybe we want that to be configurable, because clearing the selection is configurable.
=> [SuperEditor][SuperTexField] Clear composing region after losing focus (Resolves #1689)

super_editor/lib/src/default_editor/document_caret_overlay.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/test/super_editor/supereditor_caret_test.dart, super_editor/test/super_editor/supereditor_initialization_test.dart, super_text_layout/lib/src/infrastructure/blink_controller.dart
[SuperEditor][Android] Fix caret not blinking with autofocus. Resolves #1723
When the editor has autofocus, the caret is display, but it doesn't blink. We had a similar issue on iOS, which was fixed in https://github.com/superlistapp/super_editor/pull/1575
This PR applies the same solution.
=> [SuperEditor][Android] Fix caret not blinking with autofocus (Resolves #1723)

super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[super_editor_markdown] Fix list item parsing. Resolves #1711
Our list item parsing logic has two bugs.
The first is related to parsing lists with multiple levels. Example:
```
- Level 1
1. Level 2
1. Level 3
- Sublevel 1         
- Sublevel 2
2. Level 3 again
2. Level 2 returning
2. Level 1 once more
- Bullet list
- Another bullet
- Main bullet list
- Sub bullet list
- Subsub bullet list
```
Parsing this markdown results in the following document:
This issue is that we are using the `Element.textContent` as the text for the list item. When the list item contains sub-lists, `textContent` contains the text for the whole list.
This PR fixes the issue by using the `textContent` of the first child, which is the text of the list item.
The second bug is related to list items separated by empty …
=> [super_editor_markdown] Fix list item parsing (Resolves #1711)

super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/infrastructure/fill_width_if_constrained.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/test/super_textfield/super_textfield_inspector.dart, super_editor/test/super_textfield/super_textfield_scrolling_test.dart
Fix: Single-line desktop text field shouldn't be scrollable when it's content doesn't exceed viewport (Resolves #1749)
The problem was a nuanced interaction between the padding inside the desktop text field and the `FillWidthIfConstrained` widget, which expects its child to fill all of the ancestor `Scrollable`. That's a very fragile assumption, but I didn't have a better option to replace it, at the moment.
To fix the issue, I moved the padding from outside the `FillWidthIfConstrained` to inside of it.
=> Fix: Single-line desktop text field shouldn't be scrollable when it's content doesn't exceed viewport (Resolves #1749)

super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor_markdown/analysis_options.yaml, super_editor_markdown/lib/src/document_to_markdown_serializer.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/lib/src/super_editor_paste_markdown.dart, super_editor_markdown/pubspec.yaml, super_editor_markdown/test/attributed_text_markdown_test.dart, super_editor_markdown/test/custom_block_parser_test.dart, super_editor_markdown/test/super_editor_markdown_pasting_test.dart, super_editor_markdown/test/super_editor_markdown_test.dart, super_editor_markdown/test/test_tools.dart
Adds tools to easily paste Markdown from the clipboard (Resolves #1590)
To add Markdown pasting capability to a `SuperEditor` in an app, do the following:
```dart
SuperEditor(
//...
keyboardActions: [
pasteMarkdownOnCmdAndCtrlV,
...defaultKeyboardActions,
],
//...
);
```
This PR also...
* Migrates `super_editor_markdown` to Dart 3.x.
* Updates and fixes analysis warnings. 
* Adds a new request/command pair to the default list, which can insert/paste structured content.
=> Adds tools to easily paste Markdown from the clipboard (Resolves #1590)

super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/lib/src/infrastructure/strings.dart, super_editor/lib/src/test/super_editor_test/supereditor_robot.dart, super_editor/test/super_editor/text_entry/dash_conversion_test.dart, super_editor/test/super_editor/text_entry/paragraph_conversions_test.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[SuperEditor] Addem-dash conversion reaction. Resolves #1177 
This PR adds a reaction to convert 2 dashes ("--") to an em dash ("—"). 
It also allows typing three dashes at the beginning of the paragraph.  In this case, the first two dashes are converted to an em dash and after typing the third dash a horizontal rule is added before the current paragraph and the dashes are removed.
https://github.com/superlistapp/super_editor/assets/7597082/e69106be-9f26-423b-8290-7e799b7f0772
=> [SuperEditor] Add em-dash conversion reaction (Resolves #1177)

attributed_text/lib/src/attributed_spans.dart, attributed_text/test/attributed_text_test.dart
[attributed_text] Fix invalid end index with an marker that exceeds text length. Resolves #632
When an `AttributedText` has a `SpanMarker` with an end index equals to the text length (which is an invalid index, because the spans are inclusive), `collapseSpans` returns a span with an end index equal to the text length, instead of the text length -1, which is the expected index that would point to the last character.
This PR fixes the comparison that causes this behavior.
=> [attributed_text] Fix invalid end index with an marker that exceeds text length (Resolves #632)

super_editor/example/lib/demos/example_editor/_example_document.dart, super_editor/lib/src/default_editor/image.dart, super_editor_markdown/lib/src/document_to_markdown_serializer.dart, super_editor_markdown/lib/src/image_syntax.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/lib/src/super_editor_syntax.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[SuperEditor] Add image size awareness. Resolves #851
Currently, we don't have a way to specify the image size. The images don't have an initial height and the component is resized when the image is loaded.
There isn't a standard in the markdown specification for serializing an image size. However, it seems some markdown renderers use one of the following syntaxes:
1.  `![alt text](www.foo.com/image.png =800x600)` 
2. `![alt text](www.foo.com/image.png){width=800 height=600}`
This PR implements the first syntax, but I can change to the second if needed.
The markdown package doesn't have a way to plug into the image parsing, so I had to copy the whole parsing logic and change to be able to parse the size notation.
The main changes where:
- Added the `_tryParseImageSize` method.
- Added the …
=> [SuperEditor] Add image size awareness (Resolves #851)

super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/test/super_editor/text_entry/links_test.dart
[SuperEditor] Implement link attribution update when text changes. Resolves #746
Currently, we allow users to add or removes characters inside a link, but we don't update the link attribution to reflect the changes. For example, the user might type "www.google.com" and then change it to be "www.duckduckgo.com", but the link still points to "www.google.com".
I looked into some other editors. Some of them update the link, some keep the link unchanged and some remove the link entirely.
This PR adds a configuration to `LinkifyReaction` so apps can define how they want to handle changes in URL's. We could also introduce a separate reaction to this.
This PR also re-groups some existing link tests that are similar, to make the test file easier to navigate on.
=> [SuperEditor] Implement link attribution update when text changes (Resolves #746)

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/super_reader/read_only_document_mouse_interactor.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_textfield/super_textfield_gesture_scrolling_test.dart
[SuperEditor][SuperTextField] Remove calls to cancel scroll momentum on tap. Resolves #824
Flutter 3.3.3 had some changes related to scroll momentum that required us to cancel the momentum manually.  We created a `_cancelScrollMomentum` and called it in `onPointerDown`, `onPointerPanZoomStart` and `onPointerHover`.
However, after https://github.com/flutter/flutter/pull/116689 it seems these calls are not necessary anymore because the momentum is already being cancelled.
This PR removes the calls to cancel the scroll momentum `onPointerDown` and `onPointerPanZoomStart`. We also cancel the scroll momentum in `onPointerHover`, but I'm not sure why, so I didn't remove that call for now.
I modified the existing test because it was performing a full tap (down + up) before checking if the …
=> [SuperEditor][SuperTextField] Remove calls to cancel scroll momentum on tap (Resolves #824)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/touch_controls.dart, super_editor/lib/src/super_textfield/android/_editing_controls.dart, super_editor/lib/src/super_textfield/android/_user_interaction.dart, super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart, super_editor/test/super_textfield/android/super_textfield_android_selection_test.dart, super_editor/test/super_textfield/super_textfield_robot.dart
[SuperEditor][SuperTextField][Android] Show toolbar upon tap on collapsed handle. Resolves #1737
On Android, tapping on the collapsed drag handle doesn't show the popover toolbar.
This PR changes the editor/textfield to show a toolbar containing only the options "Select All" and "Paste" after tapping on the collapsed handle:
[toolbar.webm](https://github.com/superlistapp/super_editor/assets/7597082/b9b66419-3575-41e9-b3eb-5882e620ca73)
Currently, the toolbar builders don't receive the document selection, so I'm using a workaround right now. We need to decide how we want to provide this information to the toolbar builders (for both the editor and the textfield) before merging this PR.
=> [SuperEditor][SuperTextField][Android] Show toolbar upon tap on collapsed handle (Resolves #1737)

doc/website/source/quickstart.jinja, doc/website/source/super-editor-guides/quickstart.md, super_editor/example/lib/demos/demo_empty_document.dart, super_editor/example/lib/demos/in_the_lab/feature_action_tags.dart, super_editor/example/lib/demos/in_the_lab/feature_pattern_tags.dart, super_editor/example/lib/demos/in_the_lab/feature_stable_tags.dart, super_editor/example/lib/marketing_video/main_marketing_video.dart, super_editor/lib/src/core/editor.dart, super_editor/test/super_editor/bug_fix_test.dart, super_editor/test/super_editor/infrastructure/editor_test.dart, super_editor/test/super_editor/supereditor_shortcuts_test.dart, super_editor/test/super_editor/test_documents.dart, super_editor/test/super_editor/text_entry/tagging/stable_tags_test.dart, super_editor/test/super_reader/test_documents.dart, super_editor_markdown/test/super_editor_markdown_pasting_test.dart
[SuperEditor][SuperReader] Adds empty document constructor to MutableDocument (Resolves #1758)
Currently, creating an empty document is somewhat verbose and makes it a bit difficult for users to get started with `super_editor`.
Current approach to creating an empty document: 
```dart
_document = MutableDocument(nodes: [ParagraphNode(id: Editor.createNodeId(), text: AttributedText())]);
```
This PR adds an `.empty()` factory constructor to `MutableDocument` which will create the empty document using exactly what's mentioned above but hides away the complexity of creating one and allows users to get started quickly with using the package.
```dart
factory MutableDocument.empty() {
return MutableDocument(
nodes: [
ParagraphNode(
id: Editor.createNodeId(),
text: AttributedText(),
),
],
);
} …
```
=> [SuperEditor][SuperReader] Adds empty document constructor to MutableDocument (Resolves #1758)

super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/l10n/app_en.arb, super_editor/example/lib/l10n/app_es.arb, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/test/super_editor/supereditor_single_column_layout_test.dart
[SuperEditor][DemoApp] Fix image resizing. Resolves #1708, Resolves #1529
We have an image toolbar on the demo app the lets users switch the image from full width to limited width. However, using this toolbar isn't updating the layout immediately.
The reason is that we are directly mutating the node, instead of using the request/command pipeline.
This PR adds  `ChangeComponentStylesRequest` and `ChangeComponentStylesCommand` to handle the style changes.
=> [SuperEditor][DemoApp] Fix image resizing (Resolves #1708)(Resolves #1529)

super_editor/example/lib/demos/demo_empty_document.dart, super_editor/example/lib/demos/in_the_lab/feature_action_tags.dart, super_editor/example/lib/demos/in_the_lab/feature_pattern_tags.dart, super_editor/example/lib/demos/in_the_lab/feature_stable_tags.dart, super_editor/example/lib/marketing_video/main_marketing_video.dart, super_editor/lib/src/core/editor.dart, super_editor/test/super_editor/bug_fix_test.dart, super_editor/test/super_editor/infrastructure/editor_test.dart, super_editor/test/super_editor/supereditor_shortcuts_test.dart, super_editor/test/super_editor/test_documents.dart, super_editor/test/super_editor/text_entry/tagging/stable_tags_test.dart, super_editor/test/super_reader/test_documents.dart, super_editor_markdown/test/super_editor_markdown_pasting_test.dart
Cherry-Pick: [SuperEditor][SuperReader] Adds empty document constructor to MutableDocument (Resolves #1758)
=> Cherry-Pick: [SuperEditor][SuperReader] Adds empty document constructor to MutableDocument (Resolves #1758) 

super_editor/example/lib/demos/example_editor/_example_document.dart
Fix demo app compilation error due to ExpectedSize
There is a file that wasn't pushed after the last changes in https://github.com/superlistapp/super_editor/pull/1738
The `ExpectedSize` was changed to have positional parameters instead of named parameters, but the `_example_document.dart` wasn't push with the proper change.
This PR fixes this compilation error.
=> Fix demo app compilation error due to ExpectedSize

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart, super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart
[SuperEditor][Android] Fix drag handles when selection collapses due to dragging. Resolves #1736
Dragging an expanded drag handle can cause the selection to collapse. When that happens, the expanded handles are painted in the top left corner:
https://github.com/superlistapp/super_editor/assets/31278849/69bf3eab-b2ef-41e5-8b89-ccff68a141c9
This happens because `AndroidControlsDocumentLayerState` is computing a collapsed handle layout data, while we want to display expanded handles.
This PR changes `AndroidControlsDocumentLayerState` to compute layout data for a expanded handles when the selection is collapsed but we are displaying expanded handles.
After the changes:
[expanded_handles.webm](https://github.com/superlistapp/super_editor/assets/7597082/391d9127-a98b-4382-87b9-adcc266d4f19)
=> [SuperEditor][Android] Fix drag handles when selection collapses due to dragging (Resolves #1736)

super_editor/lib/src/core/document_layout.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/test/super_editor/supereditor_copy_and_paste_test.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart, super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart, super_editor/test/super_editor/supereditor_multi_editor_test.dart, super_editor/test/super_editor/supereditor_robot_test.dart, super_editor/test/super_editor/supereditor_selection_test.dart, super_editor/test/super_editor/text_entry/dash_conversion_test.dart, super_editor/test/super_editor/text_entry/links_test.dart, super_editor/test/super_editor/text_entry/paragraph_conversions_test.dart, super_editor/test/super_editor/text_entry/super_editor_common_text_entry_test.dart, super_editor/test/super_editor/text_entry/tagging/action_tags_test.dart, super_editor/test/super_editor/text_entry/tagging/pattern_tags_test.dart, super_editor/test/super_editor/text_entry/tagging/stable_tags_test.dart
[SuperEditor] Fix selection shifting when moving between nodes. Resolves #1761
In the "Animated task height" demo, moving the caret between nodes using UP or DOWN arrow is shifting the selection horizontally:
https://github.com/superlistapp/super_editor/assets/31278849/0b810924-ba05-4a8f-91c1-9fca023baad6
This would happen to any component that mixes in `ProxyDocumentComponent`. 
To move the selection vertically between nodes we first get the current offset for the selected position and then compute 
which position in the upstream/downstream node is closer to this offset.
The issue is that for `ProxyDocumentComponent`, `getOffsetForPosition` only considers the text inside the component, not the whole component. In the example of the task component, it ignores the checkbox that appears …
=> [SuperEditor] Fix selection shifting when moving between nodes (Resolves #1761)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart
[SuperEditor][Android] Fix magnifier position inside an ancestor scrollable. Resolves #1810
If the editor is inside a `CustomScrollView` with other widgets above the editor, the magnifier isn't positioned correctly when dragging the drag handle:
https://github.com/superlistapp/super_editor/assets/31278849/bba51f3a-6ca4-4f2a-b29c-91c31e6f00e1
I noticed we are positioning the drag handle leader using the mobile interactor coordinate space, and it seems the we need to position it using the global coordinate space.
Modifying the android interactor to position the leader using the global coordinates seems to solve the issue:
Inside a `CustomScrollView`: 
[android_with_scrollable.webm](https://github.com/superlistapp/super_editor/assets/7597082/dfd7587c-2c55-498c-af0d-634efcdc5fe4)
Without an …
=> [SuperEditor][Android] Fix magnifier position inside an ancestor scrollable (Resolves #1810)

super_text_layout/test/super_text_test.dart
The default value of `disableRoundingHack` is now true, the migration flag is no longer needed and will be removed soon.
=> Remove the remaining reference to the text painter rounding migration flag.

super_editor/lib/src/super_textfield/android/_editing_controls.dart, super_editor/lib/src/super_textfield/android/_user_interaction.dart, super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/ios/_editing_controls.dart, super_editor/lib/src/super_textfield/ios/_user_interaction.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/test/super_textfield/super_textfield_caret_test.dart, super_editor/test/super_textfield/super_textfield_robot.dart, super_text_layout/lib/src/caret_layer.dart
[SuperTextField][Android][ios] Disables text field caret blink while dragging caret (Resolves #1705)
Text field's caret keeps blinking while caret's being dragged within the text field. On both Android and iOS, in the native apps, the caret stops blinking as long as the user's dragging the caret. Same is expected from super text field on android and ios.
`SuperTextField` behaviour on Android and iOS:
https://github.com/superlistapp/super_editor/assets/65209850/6465ba53-134a-4d05-aeec-3107463c7bee
This PR updates both `SuperAndroidTextField` and `SuperIOSTextField` and their necessary internal components to match the native behaviour for caret blinking when user's dragging the caret within text field.  As long as the drag's is happening, caret blinking is disabled, and once the drag ends, …
=> [SuperTextField][Android][iOS] Disables text field caret blink while dragging caret (Resolves #1705)

super_text_layout/test/super_text_test.dart
This PR cherry-picks "[Flutter Team] - Remove the remaining reference to the text painter rounding migration flag. (#1829)" to stable
=> Cherry-pick "[Flutter Team] - Remove the remaining reference to the text painter rounding migration flag. (#1829)" to stable

super_editor/lib/src/default_editor/list_items.dart, super_editor/test/super_editor/components/list_items_test.dart
[SuperEditor] Clear composing region after splitting list items (Resolves #1039)
On a Samsung device using the Samsung default keyboard, typing at the end of a list item and pressing the new line button causes the editor to stop responding.
The issue is that we are not clearing the composing region when we split a list item. The Samsung keyboard generates a composing region when we start typing at the end of the list item, so after we split the item and send the new editing value to the IME, we were trying to map a composing region pointing to the node that was split. This causes a mapping error and crashes the editor.
This PR changes the `SplitListItemCommand` to clear the composing region after splitting the node.
=> [SuperEditor] Clear composing region after splitting list items (Resolves #1039)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/document_ime/document_serialization.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart
[SuperEditor][iOS] Fix applying suggestions with Korean keyboard at the beginning of a paragraph. Resolves #1828
Typing "ㅅㅛ" at the beginning of a paragraph is causing the following exception:
```console
======== Exception caught by services library ======================================================
The following _TypeError was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Null check operator used on a null value
When the exception was thrown, this was the stack: 
#0      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:153:6)
#1      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:80:9)
#2 …
```
=> [SuperEditor][iOS] Fix applying suggestions with Korean keyboard at the beginning of a paragraph (Resolves #1828)

super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart
In the short term this PR is needed to merge https://github.com/flutter/flutter/pull/143847 and then https://github.com/flutter/flutter/pull/143579.
In the long term it makes the test utilities more accurate.
=> Fix wrong key sequences

attributed_text/lib/src/attributed_text.dart, attributed_text/lib/src/test_tools.dart, attributed_text/test/attributed_text_test.dart
Fix getAllAttributionsThroughout
In https://github.com/superlistapp/super_editor/pull/1819 I found a bug on the getAllAttributionsThroughout method:
When we check each index for the attributions, we are not passing the current attribution as argument, so it was looking for any attributions.
This PR fixes the issue.
=> Fix getAllAttributionsThroughout

super_editor/lib/src/default_editor/list_items.dart, super_editor/test/super_editor/components/list_items_test.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[SuperEditor] Fix markdown sublist deserialization. Resolves #1821, Resolves #1822 
We still have some issues with our list item markdown parsing:
1. The following  input causes an infinite loop:
```
- hey there friend
- 
```
2. Parsing list with sublist still produces incorrect results. Parsing the following input produces the document of the screenshot:
```
final string_test = """
To create an outline using multiple levels of lists for the uploaded document, it appears we have the introductory sections of a chapter on quantum mechanics, specifically the following main points can be outlined:
1. Introduction to quantum mechanics
- Study of physics at small length scales
- Quantum vs. classical mechanics
- Schrodinger equation and wave properties of particles
- Application of quantum …
```
=> [SuperEditor] Fix markdown sublist deserialization (Resolves #1821) (Resolves #1822)

super_editor/lib/src/infrastructure/flutter/material_scrollbar.dart
This PR is to remove deprecated API `showTrackOnHover` from super editor repo.
These parameters are made obsolete in https://github.com/flutter/flutter/pull/111706 after v3.4.0-19.0.pre.
Part of https://github.com/flutter/flutter/issues/143956
=> Remove deprecated `showTrackOnHover`

super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
This PR aims to fix the cursor that continues to blink when typing on iOS
It seems that some logic has been added to `CaretDocumentOverlay` to manage this use case on Desktop, but this logic hasn't been replicated in `IosHandlesDocumentLayer`. The `AndroidControlsDocumentLayerState` has fixed the issue as well. 
When adding the same following logic to `IosHandlesDocumentLayer` it fixes the issue (*replicated from `CaretDocumentOverlay`*)  :
```dart
void _onSelectionChange() {
_updateCaretFlash();
setState(() {
// Schedule a new layout computation because the caret and/or handles need to move.
});
}
void _updateCaretFlash() {
_caretBlinkController.jumpToOpaque();
_startOrStopBlinking();
}
void _startOrStopBlinking() {
// TODO: allow a configurable policy as to whether to show the caret at …
```
=> Fixing iOS blinking cursor while typing.

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/document_ime/document_serialization.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/test/super_editor/supereditor_keyboard_test.dart
[SuperEditor][Web] Fix cmd + left to move selection (Resolves #1852)
On web, pressing CMD + LEFT ARROW isn't changing the selection. The selection movement on web is done using the non-text deltas that the IME generates instead of handling key presses. This causes an issue when the user tries to move the selection to the first character, because the first character the IME sees sits in the invisible region. For example, for the paragraph with the content "This is the first line", the IME content looks like this:
```
. This is the first line
```
So, when the IME moves the selection to the beginning of the line, the selection sits before the `.`. Because of that, we can't map the IME position to a document position and the selection remains unchanged.
This PR changes how we handle non-text …
=> [SuperEditor][Web] Fix cmd + left to move selection (Resolves #1852)

super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/test/super_editor/supereditor_attributions_test.dart, super_editor/test/super_editor/test_documents.dart
[SuperEditor][SuperReader] Fix setting attributions across multiple nodes (Resolves #1865)
Toggling attributions across multiple nodes selection where one node has the attribution applied already and other doesn't results in a behaviour where the attribution would be toggled off for the node that already had it and toggled on for node that didn't had that attribution. 
https://private-user-images.githubusercontent.com/31278849/308606392-dcf43a36-9ad1-498c-82b0-787df49d9641.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDMyMDMsIm5iZiI6MTcwOTc0MjkwMywicGF0aCI6Ii8zMTI3ODg0OS8zMDg2MDYzOTItZGNmNDNhMzYtOWFkMS00OThjLTgyYjAtNzg3ZGY0OWQ5NjQxLm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFte …
=> [SuperEditor][SuperReader] Fix setting attributions across multiple nodes (Resolves #1865)

super_editor/lib/src/default_editor/document_ime/document_serialization.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart
[SuperEditor][Web] Fix crash when merging paragraphs. Resolves #1921 
When pressing BACKSPACE at the beginning of a paragraph to merge it with the previous paragraph, the following crash happens:
```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown during method call
TextInputClient.updateEditingStateWithDeltas:
Unexpected null value.
```
The issue was introduced in https://github.com/superlistapp/super_editor/pull/1860, where we changed our IME code to adjust the composing region if it was reported on the invisible range.
The root cause is that the `isPositionInsidePlaceholder` method doesn't account for invalid position ( offset of `-1`).
This PR changes `isPositionInsidePlaceholder` to …
=> [SuperEditor][Web] Fix crash when merging paragraphs (Resolves #1921)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart
[SuperEditor] Avoid throwing UnimplementedError in currentAutofillScope. Resolves #1923
In `DocumentImeInputClient` we have this override throwing an `UnimplementedError`:
https://github.com/superlistapp/super_editor/blob/98762748b1a666d81c2a48f0a8a5ee6927a2f963/super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart#L163
This doesn't look like it's intentional. It's most likely that this is an auto-generated code. The docs for `currentAutofillScope` describe that we should return `null` if we don't support auto-fill. In `SuperTextField` we already do this.
This PR changes this method to return `null`.
=> [SuperEditor] Avoid throwing UnimplementedError in currentAutofillScope (Resolves #1923)

attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_text_test.dart
#1909
Added a copy() method for AttributedText to facilitate copying for mutation.
=> [attributed_text] Add a copy() method for AttributedText

attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_text_test.dart
This PR cherry-picks "[attributed_text] - Add a copy() method for AttributedText (Resolves #1909) (#1913)" to stable.
=> Cherry-pick "[attributed_text] - Add a copy() method for AttributedText (Resolves #1909) (#1913)" to stable

super_editor/lib/src/default_editor/text.dart, super_editor/test/super_editor/supereditor_attributions_test.dart
[SuperEditor] Fix toggling attributions crash. Resolves #1948
When selecting across nodes, starting from the end of the upstream node, and toggling any attribution the following exception happens:
```console
======== Exception caught by services library ======================================================
The following _Exception was thrown while processing the key message handler:
Exception: removeAttribution() did not satisfy start < 0 and start > end, start: 70, end: 69
```
https://github.com/superlistapp/super_editor/assets/31278849/f08bc48a-50ab-46ba-af45-7004c57ace8d
The cause is that we are trying to remove the attribution from an invalid range (start > end). Since the selection starts at the end of the upstream node, there isn't any selected text there to apply attributions. …
=> [SuperEditor] Fix toggling attributions crash (Resolves #1948)

super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart, super_editor/test/super_editor/components/list_items_test.dart
[SuperEditor] Fix ordered list items sequence computation. Resolves #1938
When an ordered list item is placed after an unordered list item, the unordered items are also being counted when we compute the ordered list item sequence. For example, consider the following markdown:
```
- First unordered item
- Second unordered item
1. First ordered item
2. Second ordered item
```
Instead of 1 and 2, the sequence is being computed as 2 and 3.
This PR fixes this issue by checking the list item type before incrementing the ordinal value.
=> [SuperEditor] Fix ordered list items sequence computation (Resolves #1938)

super_editor/lib/src/infrastructure/focus.dart
This PR cherry-picks "NonReparentingFocus - Reparent focus node in deactivate to match framework (#1961)" to stable
=> Cherry-pick "NonReparentingFocus - Reparent focus node in deactivate to match framework (#1961)" to stable

super_editor/lib/src/infrastructure/focus.dart
This reverts commit 60bb4424a0da1027a0c2ce1b92118db24d7bca0c.
This causes some issues:
```
Tried to make a child into a parent of itself.
[***]: 'package:flutter/src/widgets/focus_manager.dart':
[***]: Failed assertion: line 1013 pos 12: 'child != this'
[***]: 
[***]: Either the assertion indicates an error in the framework itself, or we should provide substantially
[***]: more information in this error message to help you determine and fix the underlying cause.
[***]: In either case, please report this assertion by filing a bug on GitHub:
[***]:   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
[***]: 
[***]: When the exception was thrown, this was the stack:
[***]: #2      FocusNode._reparent (package:flutter/src/widgets/focus_manager.dart:1013:12)
[***]: #3 …
```
=> Revert "NonReparentingFocus - Reparent focus node in deactivate to match framework

super_editor/lib/src/infrastructure/focus.dart
This PR cherry-picks "Revert "NonReparentingFocus - Reparent focus node in deactivate to match framework (#1969)" to stable
=> Cherry-pick "Revert "NonReparentingFocus - Reparent focus node in deactivate to match framework (#1969)" to stable

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/super_reader/read_only_document_mouse_interactor.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart
[SuperEditor][SuperReader] Do not stop scroll momentum on mouse move. Resolves #1946
On desktop, moving the mouse while the content is scrolling causes the scrolling to stop.  We introduced this change sometime ago, when the Flutter team made changes related to scroll momentum.
Now, Flutter has a dedicated signal for cancelling the scroll momentum: `PointerScrollInertiaCancelEvent`, which is already handled by `Scrollable`. Therefore, we don't need to cancel momentum ourselves.
This PR changes the mouse interactor to avoid cancelling momentum on mouse move.
=> [SuperEditor][SuperReader] Do not stop scroll momentum on mouse move (Resolves #1946)

super_editor/lib/src/infrastructure/content_layers.dart
This PR cherry-picks "Optimize ContentLayers._isSubtreeDirty to reduce significant overhead caused by logs (#1964)" to stable
=> Cherry-pick "Optimize ContentLayers._isSubtreeDirty to reduce significant overhead caused by logs (#1964)" to stable

super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart
[SuperTextField] Fix setState called during build phase. Resolves #1980
The focus change callback seems to be invoked during the build phase sometimes. In our focus change callback we call `setState`, which causes a Flutter violation (calling `markNeedsBuild` during build phase).
I wasn't able to reproduce this issue locally, but the fix should be obvious: when the callback is invoked during build, we need to defer the call to `setState` until the end of the frame.
=> [SuperTextField] Fix setState called during build phase (Resolves #1980)

super_editor/example/lib/demos/demo_markdown_serialization.dart, super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example/lib/demos/super_reader/example_document.dart, super_editor/example_docs/lib/toolbar.dart, super_editor/lib/src/default_editor/attributions.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/test/super_editor/infrastructure/common_editor_operations_test.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart, super_editor/test/super_editor/test_documents.dart, super_editor/test/super_editor/text_entry/attributions_test.dart, super_editor/test/super_editor/text_entry/links_test.dart, super_editor/test/super_editor/text_entry/super_editor_content_conversion_test.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/test/custom_parsers/callout_block.dart, super_editor_markdown/test/super_editor_markdown_test.dart
Changed LinkAttribution to allow invalid (unchecked) URLs (Resolves #1927)
The `LinkAttribution`'s `url` property is now a `String` instead of a `Uri`, so that `LinkAttribution`s can hold invalid URLs.
For easy `Uri` access, I added a `uri` property, which parses the `url` when it's accessed. This is a convenience so that users don't have to explicitly parse a `Uri` all over the place.
FYI: The motivation for this change is that an existing document, possibly from another source, is parsed and loaded into `SuperEditor`. This process fails for a document that happens to contain links for invalid URLs.
=> Changed LinkAttribution to allow invalid (unchecked) URLs (Resolves #1927)

doc/website/source/super-editor-guides/add-a-popover-toolbar.md
Update docs website with a guide about how to add a Popover Toolbar
This PR adds docs on how to add a popover toolbar, make it follow the selected content and confine it to the screen bounds.
=> Update docs website with a guide about how to add a Popover Toolbar

super_editor/lib/src/default_editor/document_gestures_touch_android.dart
[SuperEditor][Android] Fix magnified area (Resolves #1957)
On some Android devices, the magnified area is wrong:
This is caused because we use a magic number on the offset from focal point, which doesn't work for different pixel densities.
This PR fixes this issue by calculating the offset taking the pixel density into account.
[pixel_3a.webm](https://github.com/superlistapp/super_editor/assets/7597082/65f6e592-857c-41eb-bc68-7aee5c30f12e)
[pixel_7_pro.webm](https://github.com/superlistapp/super_editor/assets/7597082/a89fa960-6ccf-4764-ba1f-4e176ea277ea)
https://github.com/superlistapp/super_editor/pull/1973 should fix the issue for iOS
=> [SuperEditor][Android] Fix magnified area (Resolves #1957)

doc/website/source/super-reader-guides/quickstart.md
Update docs website with a quickstart guide for SuperReader
This PR adds a quickstart guide on how to display a `SuperReader` widget.
=> Update docs website with a quickstart guide for SuperReader

doc/website/source/super-editor-guides/style-a-document.md
Update docs website with a guide on how to use custom stylesheets.
This PR adds a guide on how to use stylesheets to style the document. Includes an explanation on how the editor handles multiple matching styles.
=> Update docs website with a guide on how to use custom stylesheets

super_editor/example/lib/demos/supertextfield/_mobile_textfield_demo.dart
[SuperEditor][DemoApp] Fix content being deleted on iOS textfield demo. Resolves #2006
On the iOS textfield demo using the "Empty" option, after typing something and pressing the action button the text is being deleted.
The issue is that we are calling the `_createDemoConfig()` during the build method. This method ends up changing the `_textController`'s text.
This PR removes that call from the build method and places in `initState` and when the user changes the selected demo.
https://github.com/superlistapp/super_editor/assets/7597082/7d6c1489-669f-4acd-81b1-e59f75483b20
=> [SuperEditor][DemoApp] Fix content being deleted on iOS textfield demo (Resolves #2006)

super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart
[SuperEditor][iOS] Fix IME mapping error after pressing the newline button (Resolve #2007)
On iOS, typing "run tom" and pressing the new line button causes the following crash:
```console
======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '. '
IME position: TextPosition(offset: 6, affinity: TextAffinity.downstream)
When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:309:5)
#1      DocumentImeSerializer.imeToDocumentSelection …
```
=> [SuperEditor][iOS] Fix IME mapping error after pressing the newline button (Resolve #2007)

website/lib/homepage/editor_toolbar.dart, website/lib/homepage/featured_editor.dart, website/lib/infrastructure/super_editor_item_selector.dart, website/pubspec.yaml
[SuperEditor][Website] Fix formatting toolbar. Resolves #1925 
On the demo website, the formatting toolbar isn't displayed after selecting some content. Also, it's not using editor commands to make changes in the document.
This PR applies the same toolbar that we have in the example app to the demo website.
For the other issues mentioned in the ticket:
- Cannot enter spaces: this was already fixed in a previous PR
- Cannot delete text after pasting text: I couldn't reproduce this issue, even with Opera on Windows 11
https://github.com/superlistapp/super_editor/assets/7597082/0fa8b98c-3a9e-4f16-a777-03bd2247ea9a
=> [SuperEditor][Website] Fix formatting toolbar (Resolves #1925)

super_editor/example/lib/demos/editor_configs/demo_mobile_editing_ios.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/infrastructure/platforms/ios/magnifier.dart, super_editor/lib/src/infrastructure/platforms/mobile_documents.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/lib/src/super_textfield/ios/_editing_controls.dart, super_editor/lib/src/super_textfield/ios/_user_interaction.dart
[SuperEditor][SuperReader][SuperTextField] Update iOS magnifier. Resolves #1958
The current appearance and behavior of our iOS magnifier doesn't match the native appearance and behavior.
Native iOS:
[native ios magnifier.webm](https://github.com/superlistapp/super_editor/assets/6229343/0825347e-4264-4819-a513-df6c2702e542)
SuperEditor:
[supereditor ios magnifier.webm](https://github.com/superlistapp/super_editor/assets/6229343/62d2f692-571f-4884-bd1b-2b15a3e8c13b)
This PR adds entrance/exit animations and updates the size and shape of the magnifier:
https://github.com/superlistapp/super_editor/assets/7597082/f0de708a-2efa-4f58-b74c-05515f371e6c
Here's the appearance with slow animations:
https://github.com/superlistapp/super_editor/assets/7597082/a83a351c-5349-4a89-bab2-bbff88391a75
This …
=> [SuperEditor][SuperReader][SuperTextField] Update iOS magnifier (Resolves #1958)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart
[SuperEditor] Show software keyboard upon tap. Resolves #1816
Steps to reproduce:
1. Place the selection at an arbitrary position
2. Close the software keyboard using the system button
3. Tap again on the same selected position
After that, the software keyboard isn't shown.
The reason is that we show the software keyboard when selection changes. Because the selection didn't change, the software keyboard isn't show.
This PR forwards `SoftwareKeyboardController` to the Android touch interactor so it can show the keyboard upon tap.
I couldn't reproduce this on iOS because I didn't find any system button to close the keyboard. We have an above-the-keyboard panel button to close the keyboard, but in reality we are closing the IME connection when tapping on it. I noticed that Flutter doesn't …
=> [SuperEditor] Show software keyboard upon tap (Resolves #1816)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart, super_editor/test/super_editor/mobile/super_editor_ios_overlay_controls_test.dart
[SuperEditor][Android] Hide expanded drag handles after deleting the selected text. Resolves #1936
On Android with an expanded selection, performing any action that causes text to be deleted, such as cutting, deleting, pasting or typing to replace the text, keeps the expanded handles visible. Trying to drag those handles throws an exception:
```console
════════ Exception caught by gesture ═══════════════════════════════════════════
The following _Exception was thrown while handling a gesture:
Exception: Tried to drag an expanded Android handle but the selection is collapsed.
```
The expanded handles are kept visible because of https://github.com/superlistapp/super_editor/pull/1754, where we changed the expanded handles to be allowed to be visible even with a collapsed selection. However, …
=> [SuperEditor][Android] Hide expanded drag handles after deleting the selected text (Resolves #1936)

super_editor/lib/src/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart
[SuperTextField][iOS] Ignore auto-corrections after handling input actions. Resolves #2004
On iOS, auto-corrections can happen after pressing the action button. For example, the user might edit some content, press "done", and after the "done" action is handled the IME reports the text replacement.
This PR prevents that by ignoring text replacements in the same frame that input actions are reported, except for `TextInputAction.newLine`.  `TextInputAction.newLine` can't prevent replacements from being applied, otherwise the user won't be able to replace the selected content with a new line.
=> [SuperTextField][iOS] Ignore auto-corrections after handling input actions (Resolves #2004)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart
[SuperEditor][Android] Show expanded handles when expanding the selection. Resolves #1937
When the selection changes from collapsed to expanded, the collapsed handle is visible at the beginning of the selection, and the expanded handles aren't visible:
[collapsed.webm](https://github.com/superlistapp/super_editor/assets/7597082/c2eb5476-5887-4c2c-a33d-a30e693aa849)
This PR fixes the issue by changing the visibility of the handles when needed.
=> [SuperEditor][Android] Show expanded handles when expanding the selection (Resolves #1937)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor_markdown/test/markdown_inline_upstream_plugin_test.dart
[SuperEditor] Fix composing region mapping when using markdown plugin. Resolves #2028
Steps to reproduce:
- Run the app with a Brazilian Keyboard with the markdown plugin enable
- Add a new line
- Type "\~b~"
With these steps the following crash happens:
```console
════════ Exception caught by services library ══════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '. ~b~'
IME position: TextPosition(offset: 4, affinity: TextAffinity.downstream)
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:30 …
```
=> [SuperEditor] Fix composing region mapping when using markdown plugin (Resolves #2028)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/test/super_editor/components/task_test.dart
[SuperEditor] Convert empty task to paragraph on ENTER. Resolves #1898
Pressing enter on an empty task isn't  converting it to a paragraph. This is the default behavior for list items.
This PR change the new line handling, both with keyboard and deltas to convert empty list items to paragraphs.
=> [SuperEditor] Convert empty task to paragraph on ENTER (Resolves #1898)

super_editor/lib/src/super_textfield/ios/_user_interaction.dart, super_editor/test/super_textfield/super_textfield_gestures_test.dart, super_editor/test/super_textfield/super_textfield_inspector.dart
[SuperTextField][iOS] Don't show the mobile toolbar upon first tap. Resolves #2005 
On iOS, tapping to focus the textfield is showing the toolbar. Looking at some iOS app, it seems the toolbar should only be displayed on tap if the textfield already has focus.
This PR changes the iOS textfield to only show the toolbar on tap if it already has focus.
For Android, it seems that doesn't show the toolbar even if the textfield already has focus.
=> [SuperTextField][iOS] Don't show the mobile toolbar upon first tap (Resolves #2005)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart
[SuperEditor][Android] Fix scrolling when dragging at empty space. Resolves #2001
When the user drags starting from an empty space, for example, the area of the document padding, the following crash happens and the editor does not scroll:
```console
════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value
#0      _AndroidDocumentTouchInteractorState._onPanStart (package:super_editor/src/default_editor/document_gestures_touch_android.dart:997:100)
document_gestures_touch_android.dart:997
#1      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:785:53) …
```
=> [SuperEditor][Android] Fix scrolling when dragging at empty space (Resolves #2001)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart
[SuperEditor][Android] Fix auto-scrolling start region. Resolves #2000
On Android, the auto-scrolling only starts when the user drags near the top of the screen. This causes problems when there are widgets above the editor, like an `AppBar`:
[before.webm](https://github.com/superlistapp/super_editor/assets/7597082/2961af48-10c5-4937-982f-ca3bede79daf)
The reason is that we are not converting the `Offset` to the offset inside the viewport.
This PR fixes the issue by converting the `Offset`:
[after.webm](https://github.com/superlistapp/super_editor/assets/7597082/1fc6e8fb-cbec-4af0-ad86-df28279a678c)
=> [SuperEditor][Android] Fix auto-scrolling start region (Resolves #2000)

super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart, super_editor_markdown/test/markdown_inline_upstream_plugin_test.dart
[super_editor_markdown] Prevent empty syntax from being converted. Resolves #2033
Typing "~~" or "``" is causing the text to be removed.
This happens because the markdown plugin looks for opening and closing syntaxes, but does not check if there is any text between then. As a result, we try to apply strikethrough/code attributions to an empty text.
This PR changes the markdown plugin to check the parsed text length. If it's exactly the length of the opening + closing characters, we don't perform any conversion.
=> [super_editor_markdown] Prevent empty syntax from being converted (Resolves #2033)

super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/default_editor/unknown_component.dart, super_editor/test/super_editor/components/task_test.dart, super_editor/test/super_editor/supereditor_components_test.dart
[SuperEditor] Fix missing default task component builder. Resolves #2048
`SuperEditor` crashes with the default configuration if the content contains a task:
```console
======== Exception caught by widgets library =======================================================
The following _Exception was thrown building _StandardEditor(state: _StandardEditorState#cb5c0):
Exception: Couldn't find styler to create component for document node: TaskNode
```
The reason is that we don't add the task component builder by default.
This PR adds a `TaskComponentBuilder` when the app uses the default component builders.
Additionally, we have an `UnknownComponentBuilder` to render unknown components, but it only creates the component, not the view model. As a result, any unknown node causes the editor to …
=> [SuperEditor] Fix missing default task component builder (Resolves #2048)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/test/super_editor/text_entry/links_test.dart
Changed linkification on paste to match URL parsing within the linkification reaction (Resolves #2031)
Linkification when pasting content wasn't recognizing URLs without www and https. This is because we have two different linkification paths. One for pasting, which happens at the moment the text is pasted. Another for reacting to user input.
This PR alters the existing pasting behavior to match the link extraction of the linkification reaction.
I'd like to move linkification entirely into the reaction, but it's not completely clear how to determine whether or not the user pasted the content vs got it some other way. I filed a proposal to add such details to all changes: https://github.com/superlistapp/super_editor/issues/2044
This PR solves the problem without doing a much larger …
=> Changed linkification on paste to match URL parsing within the linkification reaction (Resolves #2031)

super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/test/super_editor/text_entry/paragraph_conversions_test.dart
[SuperEditor] Allow continuing list item sequence by typing. Resolves #1894 
Type: 
```
1. List item
```
Press enter. This will result in the following:
```
1. List Item
2.
```
Delete `2.` and type `2.` again.
The editor doesn't convert `2.` to a list item.
Most apps do convert the `2.` to a list item, allowing the user to continue the sequence. Some of them allow numbers out of sequence, like:
```
1. List Item
2. List Item
5.
```
And some of them allows starting a list with a number different from `1`.
This PR adds the ability to continue the list, by typing the next number in the sequence. For example, given the list
```
1. List Item
2. List Item
|
```
Typing `3.` will convert the paragraph to a list item, but typing any other number will not.
We cannot allow starting lists with numbers …
=> [SuperEditor] Allow continuing list item sequence by typing (Resolves #1894)

attributed_text/lib/src/attributed_spans.dart, attributed_text/lib/src/attributed_text.dart, attributed_text/pubspec.yaml, attributed_text/test/attributed_spans_test.dart, super_editor/lib/src/default_editor/text.dart, super_editor/pubspec.yaml, super_editor/test/super_editor/supereditor_attributions_test.dart
[SuperEditor] Split incompatible attributions. Resolves #1983
Valued attributions, like `ColorAttribution` can't be applied in a range where another `ColorAttribution` exists.
Although it doesn't make sense to have two `ColorAttribution`s in the same range, users should be able to change the color of an already attributed range.
For example, consider the following range, fully attributed with blue:
```
blue green blue
b [xxxxxxxxxxxxxxx]
```
Users should be able to apply green color to the word "green", causing the blue attributed range to be split:
```
blue green blue
b [xxxxx-----xxxxx]
g [-----xxxxx-----]
```
This PR changes `AddTextAttributionsCommand` and `ToggleTextAttributionsCommand` to find and remove any conflicting attributions in the range before trying to apply the desired …
=> [SuperEditor] Split incompatible attributions (Resolves #1983)

super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/super_editor.dart
[SuperEditor][Web] Prevent Cmd + Z and Ctrl + Z shortcuts from bubbling up. Resolves #2060 
On Web, deleting a portion of a paragraph and then pressing the undo shortcut crashes the editor with the following exception: 
```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Assertion failed:
file:///Users/angelosilvestre/dev/flutter/packages/flutter/lib/src/services/text_editing_delta.dart:129:14
_debugTextRangeIsValid(newSelection, oldText)
"The selection range: TextSelection(baseOffset: 30, extentOffset: 104, isDirectional: false) is not
within the bounds of text: . Super Editor is a toolkit to of length: 30"
When the exception was …
```
=> [SuperEditor][Web] Prevent Cmd + Z and Ctrl + Z shortcuts from bubbling up (Resolves #2060)

super_editor/lib/src/default_editor/horizontal_rule.dart, super_editor/lib/src/default_editor/image.dart, super_editor/lib/src/default_editor/layout_single_column/_styler_user_selection.dart, super_editor/lib/src/default_editor/layout_single_column/selection_aware_viewmodel.dart, super_editor/lib/src/default_editor/selection_aware_viewmodel.dart, super_editor/lib/super_editor.dart, super_editor/test/super_editor/supereditor_component_selection_test.dart, super_editor/test/super_editor/supereditor_components_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart, super_editor_markdown/test/test_tools.dart
[SuperEditor] Allow custom view models to be aware of node selection. Resolves #1944
Currently, during the styling pass, we only apply the selection and selection color to our own viewmodels: `TextComponentViewModel`, `ImageComponentViewModel` and `HorizontalRuleComponentViewModel`.
Because of that, app-level view models, don't receive this information
https://github.com/superlistapp/super_editor/assets/7597082/e0e89088-f030-4013-bd64-0db68ae2f5e7
This PR introduces a `SelectionAwareViewModelMixin`. Any view model that mixes it in will receive the `DocumentNodeSelection` and selection color during the style pass.
Using this mixin, app-level components can easily render their selection:
https://github.com/superlistapp/super_editor/assets/7597082/c9c01546-b601-49f7-bd77-e1d145c88d9d
=> [SuperEditor] Allow custom view models to be aware of node selection (Resolves #1944)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/infrastructure/multi_tap_gesture.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/test/infrastructure/multi_tap_gesture_test.dart, super_editor/test/super_editor/mobile/super_editor_ios_swipe_to_pop_test.dart
[SuperEditor] Prevent long-press to resolve when swiping to pop. Resolves #1947
On mobile, dragging from left to right starts a swipe-to-pop gesture. However, when doing so we are changing the selection on both mobile platforms, showing the magnifier on iOS and showing the mobile toolbar on Android:
[android_swipe_before.webm](https://github.com/superlistapp/super_editor/assets/7597082/dba2c11b-bc28-4b80-9758-ac26da7a9274)
https://github.com/superlistapp/super_editor/assets/7597082/ea9484bc-1c88-4897-b5f5-b2ca9f61c07b
The issue is that, even though the horizontal drag recognizer is winning in the gesture arena, the `onTapDown` is still called, causing the long-press timer to be started.
To resolve that, we need to cancel the timer when we lose on the arena. 
I found another issue, where …
=> [SuperEditor] Prevent long-press to resolve when swiping to pop (Resolves #1947)

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart, super_editor/test/super_editor/mobile/super_editor_ios_overlay_controls_test.dart, super_editor/test_goldens/editor/supereditor_text_layout_test.dart
[SuperEditor][iOS] Don't show toolbar upon first tap. Resolves #2073
On iOS, tapping to change the selection from one empty paragraph to another is causing the toolbar to appear.
The issue is that, when we check if the user tapped on an existing selection, we aren't checking for the node id. Therefore, whenever the user places the caret to another paragraph at the same offset as the previous selection, the toolbar is displayed:
https://github.com/superlistapp/super_editor/assets/7597082/ba7deab0-be10-478c-9462-b9e5ff26c5cc
This PR fixes the issue by adding the node id to the comparison.
=> [SuperEditor][iOS] Don't show toolbar upon first tap (Resolves #2073)

attributed_text/lib/src/attributed_text.dart, super_editor/lib/src/default_editor/layout_single_column/_styler_user_selection.dart, super_editor/pubspec.yaml, super_editor/test/super_editor/supereditor_selection_test.dart
[SuperEditor] Fix crash due to conflicting attributions in SelectedTextColorStrategy. Resolves #2084
When using a `SelectedTextColorStrategy` to change the color of the selected text, an exception happens if the selected range already has a `ColorAttribution`.
The cause is that `AttributedText.addAttribution` doesn't expose `overwriteConflictingSpans` as `AttributedSpans` does, defaulting it to `false`.
This PR exposes `overwriteConflictingSpans` in `AttributedText`'s public API and changes the selection styler to pass `true` to it. I copied the docs from `AttributedSpans` regarding attribution merging.
We'll need to release another version of the attributed_text package.
=> [SuperEditor] Fix crash due to conflicting attributions in SelectedTextColorStrategy (Resolves #2084)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/test/super_editor/text_entry/links_test.dart, super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart, super_editor_markdown/test/markdown_inline_upstream_plugin_test.dart, super_editor_markdown/test/super_editor_markdown_pasting_test.dart
Fix crash in linkification reaction, also add linkification to inline markdown parsing (Resolves #2074)
Repro: Type `[google](www.google.com)`.
Result: Crash due to the (non-Markdown) linkification reaction.
This PR does two things:
1. Don't crash in the non-Markdown linkification reaction.
2. Linkify the Markdown syntax.
Previously, I didn't include Markdown linkification in the upstream Markdown parser reaction. That's because the link syntax is a lot more complicated to parse character by character.
In this PR, I carved out the link syntax as a special case within the parser reaction. In that carve-out I use a `RegExp` to find the link. So now that parser also parses link syntax.
=> Fix crash in linkification reaction, also add linkification to inline markdown parsing (Resolves #2074)

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/text_tools.dart, super_editor/lib/src/infrastructure/platforms/ios/selection_heuristics.dart, super_editor/lib/src/super_textfield/ios/_user_interaction.dart, super_editor/lib/src/test/test_globals.dart, super_editor/lib/super_editor.dart, super_editor/test/flutter_test_config.dart, super_editor/test/infrastructure/multi_tap_gesture_test.dart, super_editor/test/super_editor/mobile/super_editor_ios_selection_test.dart, super_editor/test/super_editor/mobile/super_editor_ios_swipe_to_pop_test.dart, super_editor/test/super_editor/supereditor_caret_test.dart, super_editor/test/super_editor/supereditor_component_selection_test.dart, super_editor/test/super_editor/supereditor_selection_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart, super_editor/test/super_textfield/ios/super_textfield_ios_selection_test.dart, super_editor/test_goldens/editor/supereditor_caret_test.dart
[SuperEditor][SuperTextField][iOS] - When user taps, place caret at word boundary (Resolves #2080)
On iOS, when a user taps on text, the caret isn't placed where the user tapped - it's placed at a word boundary.
This PR updates `SuperEditor` and `SuperTextField` to use a similar heuristic for placing the caret. This PR also disables that behavior in tests by default, so that our tests can explicitly target desired caret positions.
There's some followup work in #2098
=> [SuperEditor][SuperTextField][iOS] - When user taps, place caret at word boundary (Resolves #2080)

super_editor/lib/src/default_editor/tasks.dart, super_editor/test/super_editor/components/task_test.dart
Fix: Can now convert paragraph to task and begin with task completed (Resolves #2109)
The bug was simply that we weren't passing a variable forward - instead we hardcoded `false`.
I also cleaned up the corresponding test suite by using the pump scaffold method in all tests.
=> Fix: Can now convert paragraph to task and begin with task completed (Resolves #2109)

super_editor_quill/lib/src/serializing/serializers.dart, super_editor_quill/lib/src/serializing/serializing.dart, super_editor_quill/lib/super_editor_quill.dart, super_editor_quill/pubspec.yaml, super_editor_quill/test/parsing_test.dart, super_editor_quill/test/quill_delta_comparison.dart, super_editor_quill/test/serializing_test.dart, super_editor_quill/test/test_documents.dart
[Quill] - Serialize MutableDocument to Quill Deltas document (Resolves #2117)
The Quill serializer takes a list `DeltaSerializer`s, which know how to turn some kind of `DocumentNode` into a series of insertion deltas.
The serialization process is mostly straight-forward. The only unusual aspect of the Delta format is the rules about how block-level styles (like header, alignment, etc) are applied. The block level styles are applied in the delta immediately after them. Related to that, we need to be careful where we insert newline characters to comply with the spec.
=> [Quill] - Serialize MutableDocument to Quill Deltas document (Resolves #2117)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart
On iOS with keyboard present there is occasional `didChangeMetrics` notification even if the metrics did not change. This is something that would be nice to fix in the engine, but the API itself does not make any guarantees about when the notification is called.
The problem with this is that the notification might come during scrolling, in which case it can interfere with scroll position when trying to position the cursor within the viewport.
=> Ignore spurious metrics change notification

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart
This PR cherry-picks "[SuperEditor] - Ignore spurious metrics change notification (#2127)" to stable
=> Cherry-pick "[SuperEditor] - Ignore spurious metrics change notification (#2127)" to stable

super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example_docs/lib/toolbar.dart, super_editor/lib/src/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/lib/src/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/attributed_text_editing_controller_test.dart, website/lib/homepage/editor_toolbar.dart
=> [SuperTextField] New variations of AttributedTextEditingController.clear() (Resolves #2094)

super_editor/lib/src/infrastructure/platforms/android/long_press_selection.dart, super_editor/lib/src/infrastructure/platforms/ios/long_press_selection.dart, super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart, super_editor/test/super_editor/mobile/super_editor_ios_selection_test.dart
[SuperEditor][Mobile] Fix crash on long press over non-text node. Resolves #2126.
Long-pressing on a non-text node, such as an image or a horizontal rule causes the editor to crash, and prevents the selection with the following exception:
```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      IosLongPressSelectionStrategy.onLongPressStart (package:super_editor/src/infrastructure/platforms/ios/long_press_selection.dart:48:39)
#1      _IosDocumentTouchInteractorState._onLongPressDown (package:super_editor/src/default_editor/document_gestures_touch_ios.dart:610:60)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#3      _Timer._runTimers …
```
=> [SuperEditor][Mobile] Fix crash on long press over non-text node (Resolves #2126)

super_editor/example/lib/demos/example_editor/_toolbar.dart, super_editor/example_docs/lib/toolbar.dart, super_editor/lib/src/super_textfield/infrastructure/attributed_text_editing_controller.dart, super_editor/lib/src/super_textfield/input_method_engine/_ime_text_editing_controller.dart, super_editor/test/super_textfield/attributed_text_editing_controller_test.dart, website/lib/homepage/editor_toolbar.dart
This PR cherry-picks "[AttributedText] - Replace clear() with methods that explicitly state what they clear (Resolves #2094) (#2125)" to stable.
=> Cherry-pick "[AttributedText] - Replace clear() with methods that explicitly state what they clear (Resolves #2094) (#2125)" to stable

super_editor_quill/lib/src/content/multimedia.dart, super_editor_quill/pubspec.yaml
Fix: switch super_editor_quill to local super_editor and add missing interface APIs
This PR should fix CI failures for super_editor_quill on `stable`.
=> Fix: switch super_editor_quill to local super_editor and add missing interface APIs

super_editor/clones/quill/lib/deltas/deltas_display.dart, super_editor/clones/quill/lib/editor/toolbar.dart, super_editor/clones/quill/lib/infrastructure/super_editor_extensions.dart, super_editor/lib/src/core/editor.dart, super_editor/lib/src/default_editor/blockquote.dart, super_editor/lib/src/default_editor/box_component.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/composer/composer_reactions.dart, super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/default_editor/text_tokenizing/action_tags.dart, super_editor/lib/src/default_editor/text_tokenizing/pattern_tags.dart, super_editor/lib/src/default_editor/text_tokenizing/stable_tags.dart
Publish extension methods to access MutableDocument and MutableComposer from Editor for convenience. (Resolves #2157)
This PR doesn't contain any behavior changes - it just adds extension APIs to make it easier to access the `MutableDocument` and `MutableComposer` in the `EditContext`. The standard access lets developers query for any possible `Editable`, and there's no obvious place to learn about the existence of document or composer. So these methods now appear in intellisense.
=> Publish extension methods to access MutableDocument and MutableComposer from Editor for convenience. (Resolves #2157)

super_editor/lib/src/infrastructure/platforms/mobile_documents.dart
The offset does seem to be out of range with `SliverPinnedHeader`, which causes quite a lot of jumpiness when typing. I'm not sure if there is better way to fix this, but clamping works.
=> Clamp the scroll offset in ensureOffsetIsVisible

super_editor/lib/src/infrastructure/platforms/mobile_documents.dart
This PR cherry-picks "[SuperEditor] - DragHandleAutoScroller: Clamp the scroll offset in ensureOffsetIsVisible (#2128)" to stable
=> Cherry-pick "[SuperEditor] - DragHandleAutoScroller: Clamp the scroll offset in ensureOffsetIsVisible (#2128)" to stable

super_editor/lib/src/core/editor.dart
[SuperEditor] - Fix: Document.firstOrNull was actually returning lastOrNull (Resolves #2187)
=> [SuperEditor] - Fix: Document.firstOrNull was actually returning lastOrNull (Resolves #2187)

super_editor/README_TESTS.md, super_text_layout/README_TESTS.md
This PR cherry-picks "[Infrastructure] - Add some documentation providing links to help installing Docker (#2199)" to stable.
=> Cherry-pick "[Infrastructure] - Add some documentation providing links to help installing Docker (#2199)" to stable

website/lib/homepage/featured_editor.dart, website/pubspec.yaml
[Infrastructure] Fix demo site compilation issues. Resolves #2200
The demo website was using the removed `nodes` property from `Document`. Additionally, we need to release a new version of `super_text_layout`, because there is a new constant exposed.
This PR replaces the `nodes` usage with the new API and override the `super_text_layout` dependency. After releasing a new `super_text_layout` we can remove the dependency override.
=> [Infrastructure] Fix demo site compilation issues (Resolves #2200)

super_editor/example/lib/demos/example_editor/example_editor.dart, super_editor/example/lib/main_super_editor.dart, super_editor/lib/src/core/editor.dart, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/test/super_editor/super_editor_undo_redo_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart
[SuperEditor] - Undo/redo can now be disabled (they are disabled by default) (Resolves #2214)
The `Editor` now has a property called `isHistoryEnabled`. That property is respected inside the `Editor` - `undo()` and `redo()` bail if it's `false`. Also, the locations that would otherwise add to the history only do that when the property is `true`.
I made the property a constant on each `Editor` instance because attempting to change that value over time seems more likely to create bugs than to enable desired behavior.
I also updated the test configuration system to take a value for `isHistoryEnabled`.
=> [SuperEditor] - Undo/redo can now be disabled (they are disabled by default) (Resolves #2214)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/super_editor/supereditor_input_ime_test.dart
[SuperEditor][macOS] Fix crash after merging paragraphs containing a composing region. Resolves #2218
When using a Japanese language, typing in a paragraph and then pressing delete until the paragraph is merged with the upstream paragraph crashes the editor with the following exception:
```console
════════ Exception caught by foundation library ════════════════════════════════
The following _Exception was thrown while dispatching notifications for PausableValueNotifier<DocumentSelection?>:
Exception: No such document position in the IME content: [DocumentPosition] - node: "9ca894f5-0b79-4a3a-b0bf-842011f2d2d8", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))
#0      DocumentImeSerializer._documentToImePosition …
```
=> [SuperEditor][macOS] Fix crash after merging paragraphs containing a composing region (Resolves #2218)

super_editor/lib/src/default_editor/text_tokenizing/action_tags.dart, super_editor/test/super_editor/text_entry/tagging/action_tags_test.dart
Without this fix, this could cause an exception, as the condition checks if `extent.nodePosition` is a `TextNodePosition` and then assumes that `base.nodePosition` is a `TextNodePosition`.
=> [SuperEditor] Fix ActionTagComposingReaction looking for composing tag at selection base twice instead of at base and at extent.

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/super_textfield/android/_editing_controls.dart, super_editor/lib/src/super_textfield/android/_user_interaction.dart
[SuperEditor][SuperTextField][Android] Trigger light haptic feedback when dragging collapsed or expanded handles. Resolves #2113
Currently on Android, SuperEditor and SuperTextField doesn't provided any haptic feedback when selection selection is changed as the handle (collapsed or expanded) is dragged.
This PR changes `SuperEditor` and `SuperTextField` on Android to trigger haptic feedback as the user is dragging the handles.
However, on my Samsung M51, calling `HapticFeedback.lightImpact()` doesn't produce any feedback. Only `HapticFeedback.vibrate()` seems to be working on this phone.  I noticed there is a Flutter issue tracking this: https://github.com/flutter/flutter/issues/73987. I tried changing the settings as suggested in the ticket, but it still didn't work.
=> [SuperEditor][SuperTextField][Android] Trigger light haptic feedback when dragging collapsed or expanded handles (Resolves #2113)

super_editor/lib/src/default_editor/layout_single_column/_layout.dart, super_editor/lib/src/super_reader/super_reader.dart
In https://github.com/dart-lang/sdk/issues/49025, we are splitting the `unused_element` code, so that the warning reported is `unused_element_parameter`.
In this PR, I change each ignored case to ignore each warning name, to make the code forwards-compatible.
=> Ignore unused_element_parameter for unused parameters

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
Fixes https://github.com/superlistapp/super_editor/issues/2258
The cursor geometry is currently exposed in viewport coordinates, which works correctly for autoscroll, but for correct positioning document coordinates are needed.
=> Expose floating cursor geometry in document coordinates

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
This PR cherry-picks "[SuperEditor][SuperReader] - Expose floating cursor geometry in document coordinates (#2260)" to stable
=> Cherry-pick "[SuperEditor][SuperReader] - Expose floating cursor geometry in document coordinates (#2260)" to stable

super_editor/example/lib/demos/components/demo_text_with_hint.dart, super_editor/lib/src/default_editor/text.dart, super_editor/test/super_editor/supereditor_components_test.dart
Fixes #2267 
Currently `TextWithHintComponent` does not support underline for composing region.
With this PR it changes the widget so that it resembles with other components, i.e., it receives a list underlines instead of determining these based on other variables (e.g. `composingRegion` and `showComposingUnderline` for composing region underlines or `spellingErrorUnderlineStyle` and `spellingErrors` for spelling errors underlines). 
The component builders that create a `TextWithHintComponent` will then rely on the view model to create the underlines.
=> Support configurable underlines in TextWithHintComponent

super_editor/lib/src/default_editor/composer/composer_reactions.dart, super_editor/test/super_editor/supereditor_attributions_test.dart
[SuperEditor] Fix composer attributions when collapsing the selection. Resolves #2257
After applying an attribution to an expanded selection and collapsing the selection to the extent, the applied attribution isn't applied to the composer preferences. This causes the issue that the attribution isn't applied if the user types after placing the selection:
https://github.com/user-attachments/assets/5f79f688-d752-4d0d-82e8-31d8070274e5
The issue is that the reaction that applies attributions to the composer preferences does nothing if the previous selection extent is equal to the new selection extent, which is the case when the user places the caret at the end of an expanded selection, since the base changed but the extent don't.
This PR fixes the issue by also checking if the previous …
=> [SuperEditor] Fix composer attributions when collapsing the selection (Resolves #2257)

super_editor/lib/src/default_editor/composer/composer_reactions.dart, super_editor/test/super_editor/supereditor_attributions_test.dart
Extend more types of attributions when typing (Resolves #2280)
Auto-extend `codeAttribution`s. Also auto-extend any attribution of type `ColorAttribution` or `BackgroundColorAttribution`.
I wanted to find a way to configure these extensions without needing to use a custom configuration for `Editor`, but I wasn't able to think of anything compelling.
=> Extend more types of attributions when typing (Resolves #2280)

super_editor_quill/lib/src/parsing/block_formats.dart, super_editor_quill/lib/src/parsing/parser.dart, super_editor_quill/test/parsing_test.dart
[Quill] - Fix exceptions when parsing ambiguous custom block formats (Resolves #2286)
When implementing a custom Delta format that happens to have the same key as a standard format, e.g., "list", we were blowing up with an exception because the standard format assumed the wrong value type for the given key.
=> [Quill] - Fix exceptions when parsing ambiguous custom block formats (Resolves #2286)

super_editor_quill/lib/src/parsing/block_formats.dart, super_editor_quill/lib/src/parsing/parser.dart
[Quill] - Now supports custom block-level embed parsers (Resolves #2305)
=> [Quill] - Now supports custom block-level embed parsers (Resolves #2305)

super_editor/lib/src/super_textfield/ios/_editing_controls.dart
[SuperTextField][iOS] Increase drag handle interaction area. Resolves #1926 
Our iOS text field has a small interaction area (24px wide). Looking at the SuperEditor implementation, it looks like we are already using 48px wide. Also, the textfield caret already seems to have a 48px wide interaction area.
The expanded handle ball radius was already increased in a previous PR.
This PR only changes the width of the interaction area of the expanded handles to 48px, as it was mentioned that this was the width Flutter textfield uses.
=> [SuperTextField][iOS] Increase drag handle interaction area (Resolves #1926)

super_editor/example/android/build.gradle, super_editor/example/android/gradle/wrapper/gradle-wrapper.properties, super_editor/example/pubspec.yaml
[DemoApp] Fix build Android failure. Resolves #2281
Trying to run the example app on Android fails with the following build exception:
```console
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
> Android resource linking failed
aapt2 E 08-27 19:43:04 11507 82156 LoadedArsc.cpp:94] RES_TABLE_TYPE_TYPE entry offsets overlap actual entry data.
aapt2 E 08-27 19:43:04 11507 82156 ApkAssets.cpp:149] Failed to load resources table in APK '/Users/angelosilvestre/Library/Android/sdk/platforms/android-35/android.jar'.
error: failed to load include path /Users/angelosilvestre/Library/Android/sdk/platforms/android- …
```
=> [DemoApp] Fix build Android failure (Resolves #2281)

super_editor_quill/lib/src/parsing/parser.dart, super_editor_quill/lib/src/testing/quill_delta_comparison.dart, super_editor_quill/test/parsing_test.dart, super_editor_quill/test/serializing_test.dart
[Quill] - Added tests to lock down regular text followed by block styles (Resolves #2303)
Also, forward `blockFormats` to `parseQuillDeltaOps()`, which was previously missing.
=> [Quill] - Added tests to lock down regular text followed by block styles (Resolves #2303)

super_editor/example/lib/demos/mobile_chat/demo_mobile_chat.dart, super_editor/example/lib/main.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
[SuperEditor] - Don't clip iOS drag handles, add start of chat example app
In a client app, the iOS handles were being cut off at the boundary of the editor. This PR disables clipping on the relevant `Stack`s. 
This PR also adds the start of a chat demo, which approximates the client's use-case.
=> [SuperEditor] - Don't clip iOS drag handles, add start of chat example app

super_editor/lib/src/default_editor/unknown_component.dart
[SuperEditor] Remove redundant code in `UnknownComponentBuilder`. Resolves #2309
We have an `UnknownComponent`, but it isn't being used anywhere. Instead, we are using an nearly identical widget, only with the height different.
This PR changes `UnknownComponentBuilder` to use the `UnknownComponent` and changes `UnknownComponent` to be the same height as the widget that was being returned by the `UnknownComponentBuilder`.
=> [SuperEditor] Remove redundant code in UnknownComponentBuilder (Resolves #2309)

super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_document_controls.dart
Use Timer instead of Ticker with mobile caret blink controller to avoid constantly pumping frames (Resolves #2340)
=> Use Timer instead of Ticker with mobile caret blink controller to avoid constantly pumping frames (Resolves #2340)

super_editor/lib/src/default_editor/super_editor.dart
resolves #2365 
This PR uses a collection loop in `SuperEditor`'s constructor to prepend all plugin's `componentBuilders` when initializing `SuperEditor` widget's `componentBuilders`.
=> added insertion of componentBuilders from plugins

super_editor/lib/src/default_editor/super_editor.dart
This PR cherry-picks "[SuperEditor] - Apply componentBuilders to SuperEditor widget from plugins (#2366)" to stable.
=> Cherry-pick "[SuperEditor] - Apply componentBuilders to SuperEditor widget from plugins (#2366)" to stable

super_editor/example/lib/demos/in_the_lab/spelling_error_decorations.dart
[ExampleApp] Fix crash in spelling error decorations demo. Resolves #2374
When trying to open the "Spelling Error Decorations" demo the editor crashes with the following exception:
```console
flutter: Creating paragraph view model with style: Instance of 'SquiggleUnderlineStyle'
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
RenderViewport does not support returning intrinsic dimensions.
Calculating the intrinsic dimensions would require instantiating every child of the viewport, which defeats the point of viewports being lazy.
If you are merely trying to shrink-wrap the viewport in the main axis direction, consider a RenderShrinkWrappingViewport render object (ShrinkWrappingViewport widget), …
```
=> [ExampleApp] Fix crash in spelling error decorations demo (Resolves #2374)

super_editor/lib/src/core/document.dart, super_editor/lib/src/default_editor/box_component.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart, super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart, super_editor/lib/src/default_editor/horizontal_rule.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/test/super_editor/infrastructure/common_editor_operations_test.dart, super_editor/test/super_editor/supereditor_undeletable_content_test.dart
[SuperEditor] Add ability to set a block node as undeletable. Resolves #2334
The issue ticket also mentions making block nodes unselectable. This is already possible by setting `isVisuallySelectable` `true` in  `BoxComponent`. There is a demo in `UnselectableHrDemo`.
This PR adds the ability to mark a node as undeletable. The goal at this moment is for us to decide if this is the approach that we want and also confirm the expected behavior for some cases. After that, I'll add tests to the PR.
Marking a node as undeletable can be achieved by setting a flag in the node's metadata:
```dart
HorizontalRuleNode(
id: Editor.createNodeId(),
metadata: {
NodeMetadata.deletable: false,
},
),
```
https://github.com/user-attachments/assets/56bbeb27-7275-47dc-98ab-089af5fea128 …
=> [SuperEditor] Add ability to set a block node as non-deletable (Resolves #2334)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart, super_editor/test/test_runners.dart
[SuperEditor][Web] Fix selection change with CMD + RIGHT. Resolves #2304
Steps to reproduce: 
1. Run the example app with Chrome 
2. Place cursor on the beginning of the line "To get started with your own editing experience, take the following steps:"
3. Press CMD+Right arrow
Expected: Cursor is placed at the end of the line, Actual: Cursor is placed at the beginning of the word "steps"
This wrong offset is being reported by the selection change delta. On web, Flutter relies on html inputs to handle text input. When the user presses CMD + RIGHT, the browser moves the selection to where it thinks the end of the line is, and the Flutter code generates text deltas for us.
I haven't dug deep into this, but this seems our text layout and the browser text layout are different. For example, in …
=> [SuperEditor][Web] Fix selection change with CMD + RIGHT (Resolves #2304)

super_editor/pubspec.yaml, super_text_layout/lib/src/super_text.dart
[SuperTextField] Fix golden failure. Resolves #2343
The goldens are failing due to a layout crash with the following exception:
```console
The following assertion was thrown during performLayout():
RenderLeaderLayer does not meet its constraints.
Constraints:
BoxConstraints(200.0<=w<=Infinity, 0.0<=h<=20.0)
Size:
Size(200.0, 23.0)
```
This seems to be introduced by https://github.com/superlistapp/super_editor/pull/2338.
The crash is happening for an empty `SuperTextField` without any padding. The cause is that the height reported by the workaround code is bigger than the incoming constraints. This causes a crash during layout, because we are supposed to respect the incoming constraints.
This PR only fixes the crash by constraining the computed height, but we probably want to dig deeper to …
=> [SuperTextField] Fix golden failure (Resolves #2343)

super_editor_markdown/lib/src/image_syntax.dart, super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/pubspec.yaml, super_editor_markdown/test/custom_parsers/callout_block.dart, super_editor_markdown/test/super_editor_markdown_test.dart
This upgrades the markdown package to 7.2.1, also fixes an issue where encodeHtml is not passed to the markdown parser.
=> upgrade markdown package reference

super_editor/lib/src/default_editor/document_gestures_mouse.dart, super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/document_scrollable.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/documents/document_scaffold.dart, super_editor/lib/src/infrastructure/flutter/eager_pan_gesture_recognizer.dart, super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_ios_touch_interactor.dart, super_editor/lib/src/super_reader/read_only_document_mouse_interactor.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_reader/super_reader_scrolling_test.dart, super_editor/test_goldens/editor/mobile/mobile_selection_test.dart
This PR reworks gesture handling inside interactors with the goal of super_editor gesture detectors playing nicely with other detectors. With this PR it is no longer necessary for interactor to drive scrolling and it is now possible to have working dismissable rows in the editor.
The gesture recognizer configuration on mobile has been changed so that the document contents is sandwiched between pan and tap recognizers, i.e.
- `EagerPanGestureRecognizer` (above document)
- Document contents
- `TapSequenceGestureRecognizer` (below document)
`EagerPanGestureRecognizer` always wins, but it gets only accepted conditionally (if user drags handles or long press is in progress). 
`TapSequenceGestureRecognzer` is below document so that it doesn't interfere with checkboxes or buttons inside …
=> Rework interaction gesture handling

super_editor/lib/src/default_editor/debug_visualization.dart, super_editor/lib/src/infrastructure/content_layers.dart
Fixes https://github.com/superlistapp/super_editor/issues/2254
- Changes `Stack` in `SuperEditorImeDebugVisuals` to `SliverHybridStack` because the render object now lives in a sliver
- Implements `forgetChild` inside `ContentLayersElement`. This is necessary because the `content` of `ContentLayersElement` is being reparented using `GlobalKey` so it needs to be excluded from `visitChildren` when unmounting.
=> Fix toggling debug info crashing the editor

super_editor/example/lib/demos/mobile_chat/demo_mobile_chat.dart, super_editor/lib/src/infrastructure/sliver_hybrid_stack.dart, super_editor/test/super_editor/super_editor_shrinkwrap_test.dart
This PR cherry-picks "[SuperEditor][SuperReader] - Fix layout exception with shrinkwrap (#2326)" to stable.
=> Cherry-pick "[SuperEditor][SuperReader] - Fix layout exception with shrinkwrap (#2326)" to stable

super_editor/lib/src/default_editor/debug_visualization.dart, super_editor/lib/src/infrastructure/content_layers.dart
This PR cherry-picks "[SuperEditor][SuperReader] - Fix toggling debug info crashing the editor in demo app (#2255)" to stable.
=> Cherry-pick "[SuperEditor][SuperReader] - Fix toggling debug info crashing the editor in demo app (#2255)" to stable

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/test/super_editor/supereditor_undeletable_content_test.dart
[SuperEditor] Fix crashing when deleting all content which contains a non-deletable node at an edge. Resolves #2393
When all content in the document is selected using CMD+A and then pressing delete or backspace, it will throw exceptions if there is a non-deletable node at the start and/or end of the document.
When the user attempts to delete all content, `SuperEditor` inserts a new empty paragraph at the first deleted node's index and with the first deleted node's id, and places the caret on it. 
When a non-deletable node is at the beginning or end of the selection, it was breaking this logic. We were not inserting a new empty paragraph and we were trying to place a text selection for a block node.
This PR fixes this issue by also inserting a new empty paragraph when all deletable nodes …
=> [SuperEditor] Fix crashing when deleting all content which contains a non-deletable node at an edge (Resolves #2393)

super_editor/lib/src/default_editor/document_gestures_touch_android.dart, super_editor/lib/src/infrastructure/platforms/android/drag_handle_selection.dart, super_editor/lib/src/infrastructure/platforms/mobile_documents.dart, super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart, super_editor/test/super_editor/supereditor_test_tools.dart
[SuperEditor][Android] Honor handle builders. Resolves #1934
`SuperEditorAndroidControlsController` exposes `collapsedHandleBuilder` and `expandedHandlesBuilder`, but neither of them are being used anywhere.
This PR changes the android touch interactor to honor the provided builders.
The drag handles involve various gesture callbacks to place/expand/collapse the selection, start/stop the blinking caret, show/hide the toolbar, among other things. It would be very difficult for developers to do that on their own.
Because of that, this PR introduces an object called `DocumentHandleGestureCallbacks`, which holds the gesture callbacks that should be attached to the drag handle. Developers would wrap the handle with a `GestureDetector` and set each property to its corresponding …
=> [SuperEditor][Android] Honor handle builders (Resolves #1934)

attributed_text/pubspec.yaml, super_editor/example/pubspec.yaml, super_editor/example_docs/pubspec.lock, super_editor/example_docs/pubspec.yaml, super_editor/pubspec.yaml, super_editor_markdown/pubspec.yaml, super_editor_quill/pubspec.yaml, super_text_layout/pubspec.yaml
Bump dependencies. Resolves #2336
This PR bumps the versions for all dependencies that could be updated. I couldn't update `collection` and `characters` because it caused a version conflict with the test package.
The example docs started to fail the build with an error the seems to be related to the uuid package. Because of that, I re-generated the pubspec.lock file.
=> Bump dependencies (Resolves #2336)

super_editor_markdown/lib/src/super_editor_paste_markdown.dart
[super_editor_markdown] Fix compilation error
Now `CommonEditorOperations.getDocumentPositionAfterExpandedDeletion` returns a nullable type. This caused a compilation error in `pasteMarkdown`.
This PR fixes that issue.
=> [super_editor_markdown] Fix compilation error

doc/website/source/index.jinja
[Guides] Fix quickstart link. Resolves #2330
The link to the quickstart was pointing to "/super-editor-guides/quickstart" where it should be pointing to "/super-editor/guides/quickstart"
=> [Guides] Fix quickstart link (Resolves #2330)

super_editor/lib/src/core/document_selection.dart, super_editor/lib/src/core/editor.dart, super_editor/lib/src/core/styles.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/layout_single_column/_presenter.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/lib/src/default_editor/tap_handlers/tap_handlers.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/infrastructure/platforms/android/drag_handle_selection.dart
[SuperEditor][SuperReader] - Reduce uses of node index queries in Document (Resolves #2434)
This PR changes as many calls as possible from index-based node access to either getting a node by ID, or getting a node before/after another node. This is in preparation for changes to a tree document, for which those behaviors still make sense, but accessing at an index doesn't.
=> [SuperEditor][SuperReader] - Reduce uses of node index queries in Document (Resolves #2434)

attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_spans_placeholders_test.dart, attributed_text/test/attributed_text_placeholders_test.dart
Adds placeholders to AttributedText (Resolves #2440)
We want to display inline widgets in `SuperEditor`. This requires a way to represent the existence of such widgets within the text model, which is `AttributedText`.
This PR adds placeholders to `AttributedText`. A placeholder is an `Object` that takes up the space of a single character. This spacing allows for text positions before and after the placeholder, but not within the placeholder.
Each placeholder is represented by some kind of `Object`. We currently don't place any restriction on what that is. Mapping from placeholders to widgets is handled by the visual system.
=> Adds placeholders to AttributedText (Resolves #2440)

super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/test/super_editor/infrastructure/common_editor_operations_test.dart
[SuperEditor] Make getDocumentPositionAfterExpandedDeletion return null for collapsed selections. Resolves #2431
The `CommonEditorOperations.getDocumentPositionAfterExpandedDeletion` returns a `TextNodePosition` even when the selection is collapsed. In this situation, we expect nothing to be deleted and no selection change.
Currently, if all nodes in the selection are non-deletable, this method returns `null`. To keep consistency, this PR changes this method to also return `null` when the selection is collapsed.f
=> [SuperEditor] Make getDocumentPositionAfterExpandedDeletion return null for collapsed selections (Resolves #2431)

super_editor/lib/src/default_editor/tasks.dart
This PR cherry-picks "[Flutter Team] - Update `TaskNode`s `Checkbox` visual density to depend on the `ThemeData.visualDensity` (#2444)" to stable.
=> Cherry-pick "[Flutter Team] - Update `TaskNode`s `Checkbox` visual density to depend on the `ThemeData.visualDensity` (#2444)" to stable

website/lib/homepage/featured_editor.dart, website/lib/homepage/home_page.dart
Fix Sliver crash in Demo Website. Resolves #2329
The original ticket mentions a different issue, which I could not reproduce. With the latest main, the editor is crashing immediately with the following exception:
```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building DocumentMouseInteractor(dependencies: [MediaQuery],
state: _DocumentMouseInteractorState#72a71):
TypeError: Instance of '_RenderSliverHybridStack': type '_RenderSliverHybridStack' is not a subtype
of type 'RenderBox'
The relevant error-causing widget was:
DocumentMouseInteractor
DocumentMouseInteractor:file:///Users/angelosilvestre/dev/super_editor/super_editor/lib/src/default_editor/super_editor.dart:865:16
```
The issue is …
=> Fix Sliver crash in Demo Website (Resolves #2329)

super_editor/lib/src/core/editor.dart, super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/test/super_editor/supereditor_content_deletion_test.dart
[SuperEditor] Add `ClearDocumentRequest`. Resolves #2360
Clearing a document involves:
- Removing all the nodes
- Adding a new empty paragraph
- Placing the caret at the newly created paragraph
- Clearing the composing region
This PR adds a `ClearDocumentRequest`, which packs all of those actions in a single request.
=> [SuperEditor] Add `ClearDocumentRequest` (Resolves #2360)

super_editor/lib/src/infrastructure/content_layers.dart, super_editor/test/super_editor/supereditor_theme_switching_test.dart
[SuperEditor] Add test to demonstrate that changing layer builders does not re-layout
Changing `SuperEditor` overlay builders doesn't trigger a re-layout. An overlay can change, for example, to switch the caret color depending on the theme.
This was discussed in https://github.com/superlistapp/super_editor/issues/2042
This PR adds tests to demonstrate that issue. The first test, which only switches the theme, fails. The second test, that types a character after switching themes, passes.
=> [SuperEditor] Add test to demonstrate that changing layer builders does not re-layout

super_editor/example/lib/demos/in_the_lab/feature_ios_native_context_menu.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/infrastructure/platforms/ios/ios_system_context_menu.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart
[SuperEditor][SuperTextField][iOS] Fix focal point for native toolbar. Resolves #2345
When using the native iOS toolbar, the toolbar has a wrong focal point:
https://github.com/user-attachments/assets/e87b8b7e-b326-4fa3-8e2f-10be3fc39ae7
We compute the toolbar anchor using the `LeaderLink`'s offset and size. The issue is that we are trying to get the leader size before it is computed, because the toolbar builder is being called before the `Leader` runs `performLayout`.
I added some print statements to show what's happening:
```console
flutter: after RenderLeader performLayout(), leader size: Size(0.0, 25.2)
flutter: building toolbar, leader size: Size(0.0, 25.2)
flutter: after RenderLeader performLayout(), leader size: Size(85.3, 21.5)
```
The first `performLayout` runs after the first …
=> [SuperEditor][SuperTextField][iOS] Fix focal point for native toolbar (Resolves #2345)

super_text_layout/example/pubspec.lock, website/pubspec.lock
[Demo] Fix demo website deployment. Resolves #2465 
The website build is failing with a version conflict in attributed_text:
https://app.netlify.com/sites/suspicious-kepler-28398e/deploys/6764d117544a5c00087ae34b
The pubspec.yaml looks correct, but the pubspec.lock still points to attributed_text version 0.3.2. I deleted an re-generated the pubspec.lock.
Maybe we could try to use the new dart feature to monorepos to see if this issues don't happen anymore.
=> [Demo] Fix demo website deployment (Resolves #2465)

super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/default_editor/text_tokenizing/action_tags.dart, super_editor/lib/src/default_editor/text_tokenizing/tags.dart, super_editor/test/super_editor/text_entry/tagging/action_tags_test.dart, super_editor/test/super_editor/text_entry/tagging/pattern_tags_test.dart, super_editor/test/super_editor/text_entry/tagging/stable_tags_test.dart
[SuperEditor] Limit tag expansion to caret position. Resolves #2240, #2241, #2242
Steps to reproduce:
1. Go to the "Action Tags" section of the example app
2. Type some text
3. Place the cursor in the middle of the text
4. Type "/"
5. Press backspace
6. Type "/" again
The editor crashes with the following exception:
```console
════════ Exception caught by services library ══════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: removeAttribution() did not satisfy start < 0 and start > end, start: 6, end: 5
#0      AttributedSpans.removeAttribution (package:attributed_text/src/attributed_spans.dart:514:7)
attributed_spans.dart:514
#1 …
```
=> [SuperEditor] Limit tag expansion to caret position (Resolves #2240, #2241, #2242)

super_editor/lib/src/default_editor/text_tokenizing/action_tags.dart, super_editor/test/super_editor/text_entry/tagging/action_tags_test.dart
[SuperEditor] Fix crash with selection across nodes when using the tags plugin. Resolves #2479
To reproduce the issue:
Select a paragraph node completely (all text) and then continue the selection to another paragraph node above it. Or simply select multiple nodes partially.
Exception:
```
Exception has occurred.
RangeError (RangeError (end): Invalid value: Not in inclusive range 10..56: 68)
```
The issue is that we are trying to use the caret position to extract the text. However, when multiple paragraphs are selected, we are always trying to extract the text using the end position of the selection, which will be invalid when one paragraph is larger then another.
We discussed about modifying the tag find logic for the action tags to only care about collapsed selections, because an action …
=> [SuperEditor] Fix crash with selection across nodes when using the tags plugin (Resolves #2479)

super_editor/example/lib/demos/supertextfield/_interactive_demo.dart, super_editor/lib/src/infrastructure/document_gestures_interaction_overrides.dart, super_editor/lib/src/super_textfield/android/_user_interaction.dart, super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart, super_editor/lib/src/super_textfield/infrastructure/text_field_gestures_interaction_overrides.dart, super_editor/lib/src/super_textfield/infrastructure/text_field_tap_handlers.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/lib/src/super_textfield/ios/user_interaction.dart, super_editor/lib/src/super_textfield/super_textfield.dart, super_editor/lib/super_text_field.dart, super_editor/test/super_textfield/super_textfield_gestures_interaction_overrides_test.dart, super_editor/test/super_textfield/super_textfield_robot.dart
[SuperTextField] Add ability to override tap gestures. Resolves #2447
This PR allows apps to register custom handlers, to enable features like changing the mouse cursor when hovering content with specific attributions, like a `LinkAttribution` and performing custom logic when tapping on it.
The implementation is based on the `SuperEditor`'s `ContentTapDelegate`.
I noticed we also have a `RightClickListener`. We could probably deprecate this property and make everything available through the new `SuperTextFieldTapHandler`.
This PR includes a `SuperTextFieldLaunchLinkTapHandler` that changes the mouse cursor when hovering a link, and opens the URL when tapping on it.
On `SuperEditor`, we have the concept of "interaction mode", which is enabled when the users presses CMD. The mouse cursor …
=> [SuperTextField] Add ability to override tap gestures (Resolves #2447)

super_editor/lib/src/default_editor/document_gestures_touch_ios.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/super_textfield/ios/user_interaction.dart, super_editor/test/flutter_test_config.dart, super_editor/test/super_editor/mobile/super_editor_ios_overlay_controls_test.dart, super_editor/test/super_editor/supereditor_caret_test.dart, super_editor/test/super_editor/supereditor_robot_test.dart, super_editor/test/super_textfield/ios/super_textfield_ios_selection_test.dart
[SuperEditor][SuperTextField][iOS] Make caret word snapping less aggressive. Resolves #2152
On iOS, the caret snaps to the edges of a word. However, this shouldn't happen when the user taps at the caret position.
This PR changes `SuperEditor` and `SuperTextField` to avoid snapping the caret when tapping at the caret.
Some required adjustments:
- The check for a tap over the caret was using the snapped position instead of the tap position. Modified to use the exact tap  position.
- The check for a tap over the caret was expanding the caret 24px in all directions. This causes an issue, because tapping on a line below (or up) can be interpreted as a tap on the caret. Modified to expand only horizontally.
We still have a problem in `SuperEditor` regarding showing the toolbar when tapping at …
=> [SuperEditor][SuperTextField][iOS] Make caret word snapping less aggressive (Resolves #2152)

super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/test/super_textfield/ios/super_textfield_ios_selection_test.dart
[SuperTextField][iOS] Fix selection highlight. Resolves #2346
When using a `SuperIOSTextField` (not a `SuperTextField`), the selection highlight doesn't appear. This only happens if we don't provide a `textController` in `SuperIOSTextField` constructor.
The issue is that, in the places we check for an existing selection to add the highlights, we are always checking for the  `textController` provided by the widget constructor instead of using the internal controller (which uses the constructor's `textController` if provided).
This PR fixes the issue by making `SuperIOSTextField` always use the internal `textController`.
I'm not sure the text is good, since we are looking at too much implementation details. Maybe we should just use a golden test instead.
=> [SuperTextField][iOS] Fix selection highlight (Resolves #2346)

super_editor/CHANGELOG.md, super_editor/pubspec.yaml
Updated CHANGELOG and pubspec.yaml for super_editor release v0.3.0-dev.12
I forgot to push these changes and a tag when I released super_editor v0.3.0-dev.12. This PR updates the tracking info, but we're missing a dedicated commit for this release.
=> Updated CHANGELOG and pubspec.yaml for super_editor release v0.3.0-dev.12

super_editor/example/lib/demos/mobile_chat/demo_mobile_chat.dart, super_editor/lib/src/infrastructure/keyboard_panel_scaffold.dart, super_editor/test/infrastructure/keyboard_panel_scaffold_test.dart
Fix: Make KeyboardScaffoldSafeArea work when not at bottom of screen (Resolves #2489)
Apparently when I recently created the new implementation of the keyboard scaffold I never tested with widgets below the chat editor, such as bottom nav tabs. When there's a widget below the editor, we were pushing the editor up too far, equal to the height of whatever was below it before pushing it up.
There's one known shortcoming even with the PR. When the content below the editor changes size, the editor position is one frame behind, leading to some jitter. This is likely to happen because the widget at the bottom of the screen is probably wrapped in a `SafeArea` to deal with bottom insets.
Here's an example of the jitter:
https://github.com/user-attachments/assets/c19d4e96-d27d-424b-ba0f-87e9fa61daf5 …
=> Fix: Make KeyboardScaffoldSafeArea work when not at bottom of screen (Resolves #2489)

super_editor/example/lib/demos/interaction_spot_checks/url_launching_spot_checks.dart, super_editor/example/lib/main.dart, super_editor/lib/src/default_editor/attributions.dart, super_editor/lib/src/default_editor/common_editor_operations.dart, super_editor/lib/src/default_editor/default_document_editor_reactions.dart, super_editor/lib/src/default_editor/tap_handlers/tap_handlers.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/src/super_textfield/infrastructure/text_field_tap_handlers.dart, super_editor/test/super_editor/text_entry/links_test.dart
[Super Editor] - Make emails clickable with "mailto:", and linkify app URLs like "obsidian://" (Resolves #2426, Resolves #2427)
I added some nuance to how we store info in `LinkAttribution`. We now store a plain text version of a URI and (if provided) a structured `Uri` object.
The reason we need to support plain-text URIs is because content might come from existing documents, with invalid or incomplete URIs. Even a value like "google.com" can't be given a `Uri` with confidence. We'd have to assume the scheme. So sometimes the best we can do is plain text.
However, it's often possible to provide the scheme, e.g., "https://", "mailto:", "obsidian://". When possible, a structured `Uri` object should be provided to a `LinkAttribution`.
When we have a scheme, we have a launchable URI. When we …
=> [Super Editor] - Make emails clickable with "mailto:", and linkify app URLs like "obsidian://" (Resolves #2426, Resolves #2427)

super_editor/example/lib/demos/example_editor/example_editor.dart, website/lib/homepage/featured_editor.dart
[DemoApp] Fix editor not re-gaining focus when the app is brought to foreground. Resolves #2279
There are some places where we request focus to the editor's focus node when the toolbar is closed. These code paths can be called in response to the app going to background. Doing this prevents the editor from re-gaining focus when the app is restored.
This PR changes these places to only request focus to the editor if the primary focus is not at the root  `FocusScopeNode` (which might signify that the app is going to background).
=> [DemoApp] Fix editor not re-gaining focus when the app is brought to foreground (Resolves #2279)

super_editor/clones/quill/pubspec.lock, super_editor/example_docs/pubspec.lock, super_editor/lib/src/infrastructure/keyboard_panel_scaffold.dart, super_editor/test/infrastructure/keyboard_panel_scaffold_test.dart
[Super Editor] - Fix KeyboardScaffoldSafeArea so that when there's only a single scope, that scope is used instead of MediaQuery (Resolves #2502)
The `KeyboardScaffoldSafeArea` and `KeyboardScaffoldSafeAreaScope` talk to each other in the widget tree so that they respect their ancestors. However, I focused so much on that intercommunication that I screwed up the case of a single safe area scope. This PR fixes that issue by applying the safe area insets from the singular safe area scope, when there's no ancestor.
=> [Super Editor] - Fix KeyboardScaffoldSafeArea so that when there's only a single scope, that scope is used instead of MediaQuery (Resolves #2502)

super_editor/clones/quill/lib/app.dart, super_editor_quill/README.md, super_editor_quill/lib/src/parsing/parser.dart, super_editor_quill/test/parsing/multiline_parsing_test.dart, super_editor_quill/test/parsing/parsing_test.dart
[Quill] - Make consecutive node merges configurable (Resolves #2510)
We previously hard-coded the merging of consecutive code blocks into a single block, which seemed to be the standard Quill editor behavior. The Quill editor didn't seem to merge any other blocks.
However, an app might want to merge any number of block types, including blockquotes. An app might also want to merge custom block types, which this package can't possibly know about. Therefore, this PR makes the merge decision configurable.
=> [Quill] - Make consecutive node merges configurable (Resolves #2510)

attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_text_placeholders_test.dart, attributed_text/test/attributed_text_test.dart
[Attributed Text] - Fix: A few methods still (erroneously) using plain text length without accounting for placeholders (Resolves #2515)
Apparently I missed some uses of `_text.length` in `AttributedText` when I implemented placeholders. Except for special situations of internal accounting, we should never use `_text.length` anymore because it misses the placeholders.
I added a failing test for each effected method.
=> [Attributed Text] - Fix: A few methods still (erroneously) using plain text length without accounting for placeholders (Resolves #2515)

super_editor/lib/super_editor.dart, super_editor/lib/super_editor_test.dart
Exports `src/infrastructure/platforms/platform.dart` that it's possible to access `debugIsWebOverride` in tests.
=> Export src/infrastructure/platforms/platform.dart

super_editor_spellcheck/pubspec.yaml
[Spellcheck] - Upgrade `super_editor` dependency from 0.3.0-dev.3 to ^0.3.0-dev.15 to get access to new APIs that otherwise create a compilation error.
=> [Spellcheck] - Upgrade super_editor dependency from 0.3.0-dev.3 to ^0.3.0-dev.15.

super_editor_spellcheck/.run/main.dart.run.xml, super_editor_spellcheck/example/lib/main_super_editor_spellcheck.dart, super_editor_spellcheck/example/pubspec.lock, super_editor_spellcheck/lib/src/super_editor/spelling_and_grammar_plugin.dart
[Spellcheck] - Check for spelling errors on initial document content (Resolves #2526)
Editors can begin with non-empty Documents. In that case, we need to find spelling errors in the initial content. This PR does that.
=> [Spellcheck] - Check for spelling errors on initial document content (Resolves #2526)

super_editor/lib/src/default_editor/document_gestures_mouse.dart
[SuperEditor][web] Fix double tap closing the IME connection on Safari/Firefox. Resolves #2513
On Safari/Firefox, double tapping to select a word and then pressing backspace, delete, or any letter does nothing and stops the editor from responding to key presses.
I noticed this only happens when the selection is expanded by double tapping. When expanding by dragging, or pressing SHIFT + ARROW key it works correctly. What's happening is that we are closing the IME connection and then immediately reopening it, and it doesn't seem to work correctly on Safari/Firefox. This is the sequence of events:
- The user double taps
- We clear the existing selection
- Because the default value of `SuperEditorImePolicies.closeKeyboardOnSelectionLost` is `true`, we close the IME connection
- We place the …
=> [SuperEditor][web] Fix double tap closing the IME connection on Safari/Firefox (Resolves #2513)

super_editor/test/super_editor/mobile/super_editor_ios_swipe_to_pop_test.dart, super_editor/test/super_editor/supereditor_content_insertion_test.dart, super_editor/test/super_editor/supereditor_gestures_test.dart, super_editor/test/super_editor/supereditor_scrolling_test.dart, super_editor/test/super_editor/text_entry/links_test.dart, super_editor/test/super_textfield/super_textfield_emoji_test.dart, super_editor/test/super_textfield/super_textfield_ime_test.dart, super_editor/test/super_textfield/super_textfield_theme_test.dart, super_editor/test/test_runners.dart
[Infrastructure] Add test platform suffixed by default (Resolves #2274)
In some of the tests that are specific to a single platform, we are adding the platform suffixes manually. For example: `testWidgetsOnAndroid("test something", (tester) async{});`
We already made the change to include the platform suffix to the test methods from the `flutter_test_runners` package a while ago (https://github.com/Flutter-Bounty-Hunters/testing/pull/1), but we did not release a new version since, so we should release a new version.
This PR removes the manually added suffixes and also modify some test runners declared directly in this repo.
=> [Infrastructure] Add test platform suffixed by default (Resolves #2274)

super_editor/lib/src/default_editor/super_editor.dart
Fix typo in "_openSoftareKeyboard"  (Resolves #2355).
This PR fixes a typo: "_openSoftareKeyboard" -> "_openSoftwareKeyboard".
=> Fix typo in "_openSoftareKeyboard" (Resolves #2355)

super_editor/example/lib/demos/demo_animated_task_height.dart, super_editor/example/lib/demos/super_reader/demo_super_reader.dart, super_editor/example/lib/demos/super_reader/example_document.dart, super_editor/example_perf/lib/demos/rebuild_demo.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/src/super_reader/tasks.dart, super_editor/test/super_reader/components/task_test.dart, super_editor/test/super_reader/reader_test_tools.dart
[SuperReader] Add support for rendering tasks (Resolves #2354)
Currently, render a read-only document that contains a task node results in the reader rendering an unknown component:
This PR adds support for rendering read-only tasks in `SuperReader`. 
I modified the `TaskComponentViewModel.setComplete` to be nullable, but I can changed it to add an additional `readOnly` property, if preferable.
https://github.com/user-attachments/assets/1694e5af-dd8f-46e2-a522-0bff6aec30db
=> [SuperReader] Add support for rendering tasks (Resolves #2354)

super_editor/lib/src/default_editor/layout_single_column/_styler_user_selection.dart, super_editor/test/super_editor/supereditor_selection_test.dart
[SuperEditor] Fix crash with selected color strategy in an empty paragraph (Resolves #2253)
When the editor has a `selectedTextColorStrategy` configured, triple tapping on an empty paragraph crashes the editor with the following exception:
```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: 'package:attributed_text/src/span_range.dart': Failed assertion: line 20 pos 16: 'end >= -1': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:63:4)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:45:5)
#2      new SpanRange (package:attributed_text/src/span_range.dart:20:16)
#3      SingleColumnLayoutSelectionStyler._applySelection (package:super_editor/src/default_editor/layout_single_column/_styler_user_selection.d …
```
=> [SuperEditor] Fix crash with selected color strategy in an empty paragraph (Resolves #2253)

super_editor/lib/src/default_editor/default_document_editor.dart, super_editor/lib/src/default_editor/text.dart, super_editor/test/super_editor/text_entry/inline_widgets_test.dart
[Super Editor] - Fix: applying styles to text with inline placeholders deletes the placeholders (Resolves #2555)
The problem was that the code to toggle the styles was only copying the "plain text" version of the `AttributedText`, which then ignored any inline placeholders. The result was a loss of all placeholders when toggling styles.
=> [Super Editor] - Fix: applying styles to text with inline placeholders deletes the placeholders (Resolves #2555)

attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_text_placeholders_test.dart
[AttributedText] - Fix incorrect character lookup by index (Resolves #2531)
We need to lookup text characters while accounting for placeholders. Previously were were looking up characters in the plain text string.
=> [AttributedText] - Fix incorrect character lookup by index (Resolves #2531)

super_editor/lib/src/default_editor/spelling_and_grammar/spelling_and_grammar_styler.dart
[SuperEditor] Fix immutability violation in spellchecking styler (Resolves #2560)
A crash was reported within `spelling_and_grammar.dart` within `_applyErrors()` where we try to do the following:
```dart
viewModel.grammarErrors
..clear()
..addAll([
//....
]);
```
I didn't find any places where we return an unmodifiable list from the the `grammarErrors`, but I think it's safer to replace  the list instead of modifying it, because apps can add custom view models, that might return an unmodifiable list for `grammarErrors`.
This PR changes the `SpellingAndGrammarStyler` to override the viewmodel's `spellingErrors` and `grammarErrors`.
=> [SuperEditor] Fix immutability violation in spellchecking styler (Resolves #2560)

attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_text_placeholders_test.dart, super_editor/pubspec.yaml, super_editor/test/super_editor/text_entry/inline_widgets_test.dart
[SuperEditor][AttributedText] Fix placeholder breaking attribution behavior (Resolves #2565)
Inserting an empty text with a placeholder, with an attribution around it, causes the editor to crash when trying to type.
```console
════════ Exception caught by services library ══════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Another AttributedSpans can only be appended after the final marker in this AttributedSpans. Final marker: [SpanMarker] - attribution: [NamedAttribution]: bold, offset: 1, type: SpanMarkerType.end
#0      AttributedSpans.addAt (package:attributed_text/src/attributed_spans.dart:714:7)
#1      AttributedText.copyAndAppend …
```
=> [SuperEditor][AttributedText] Fix placeholder breaking attribution behavior (Resolves #2565)

super_editor_spellcheck/example/lib/main_super_editor_spellcheck.dart, super_editor_spellcheck/lib/src/super_editor/spelling_and_grammar_plugin.dart
[SuperEditorSpellCheck] Add API to ignore text during spellcheck (Resolves #2564)
This PR adds an optional `ignoreRules` to the plugin constructor, so apps can choose to ignore certain texts, like links, tags, etc.
Each rule is a function that returns a list of `TextRange`s that should be ignored. All ranges from all rules are ignored.
Since on mobile we pass the whole text at once to the spellchecker, we need a workaround to do this. This PR replaces all the ignored ranges with whitespaces, so the spellchecker doesn't report anything on those ranges.
This PR implements built-in rules for ignore by pattern, attribution and attribution filters.
Without the ignored ranges:
With ignored ranges:
=> [SuperEditorSpellCheck] Add API to ignore text during spellcheck (Resolves #2564)

super_editor/test/super_editor/mobile/super_editor_ios_overlay_controls_test.dart
[SuperEditor] Make iOS overlay controls test use iOS selection heuristics (Resolves #2470)
iOS has a specific behavior for placing the caret by tapping: it always places the caret at word boundaries. In `SuperEditor`, we call this behavior "iOS selection heuristics". This heuristics are enabled by default on `SuperEditor`, but disabled by default in tests. They are disable because, on most cases, we just want to place the caret at a specific position. 
While the heuristics being disabled makes sense for some tests, tests that care about interacting with the caret should use these heuristics. One example is https://github.com/superlistapp/super_editor/issues/2152, where we have a test to make sure the toolbar is displayed when tapping on the caret, but the test didn't catch the bug because …
=> [SuperEditor] Make iOS overlay controls test use iOS selection heuristics (Resolves #2470)

.github/workflows/pr_validation.yaml, super_editor_spellcheck/lib/src/super_editor/spelling_and_grammar_plugin.dart, super_editor_spellcheck/pubspec.yaml, super_editor_spellcheck/test/spellcheck_ignore_rules_test.dart
[Spellcheck] Add tests for ignore rules (Resolves #2573)
This is a follow up PR for https://github.com/superlistapp/super_editor/pull/2567.
We added support for "ignore rules", to allow apps to ignore from spellcheck certain pieces of text, like mentions, tags, texts with specific attributions, etc.
This PR modifies the `SpellingAndGrammarPlugin` to take an optional `SpellCheckService` parameter. This allows us to provide a fake spellchecker in tests, to verify which portions of texts were queried.
=> [Spellcheck] Add tests for ignore rules (Resolves #2573)

super_editor/example/android/app/build.gradle, super_editor/example/android/build.gradle, super_editor/example/android/settings.gradle
[DemoApp][Android] Migrate to Gradle plugins DSL (Resolves #2576)
On Flutter 3.29, the demo app is failing to build with the following error:
```console
FAILURE: Build failed with an exception.
* Where:
Script 'FLUTTER_LOCATION/packages/flutter_tools/gradle/app_plugin_loader.gradle' line: 9
* What went wrong:
A problem occurred evaluating script.
> You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is not possible anymore. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply
2
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at …
```
=> [DemoApp][Android] Migrate to Gradle plugins DSL (Resolves #2576)

.github/workflows/pr_validation.yaml
[Infrastructure] Update actions/upload-artifact to v4 (Resolves #2585)
Our golden tests are failing with the following message:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
This is the action we use to upload the golden images in case of failures.
This PR simply bumps the version to v4.
=> [Infrastructure] Update actions/upload-artifact to v4 (Resolves #2585)

super_editor/lib/src/super_reader/read_only_document_android_touch_interactor.dart, super_editor/test/super_reader/super_reader_phone_rotation_test.dart
[SuperReader][Android] Fix crash when rotating the phone with an expanded selection (Resolves #2580)
When rotating the phone the reader crashes if it has an expanded selection:
```console
════════ Exception caught by scheduler library ═════════════════════════════════
The following _TypeError was thrown during a scheduler callback:
type 'RenderSliverToBoxAdapter' is not a subtype of type 'RenderBox' in type cast
#0      _ReadOnlyAndroidDocumentTouchInteractorState._ensureSelectionExtentIsVisible (package:super_editor/src/super_reader/read_only_document_android_touch_interactor.dart:325:77)
read_only_document_android_touch_interactor.dart:325
#1      _ReadOnlyAndroidDocumentTouchInteractorState.didChangeMetrics.<anonymous closure> …
```
=> [SuperReader][Android] Fix crash when rotating the phone with an expanded selection (Resolves #2580)

super_editor/lib/src/default_editor/list_items.dart
[FEATURE] - inline widgets in List Item Component (https://github.com/superlistapp/super_editor/issues/2608)
Inline widget builders passed from componentViewModel to List Item Components. Inline widget builders preserved in UnorderedListItemComponentViewModel and OrderedListItemComponentViewModel copy methods.
=> [FEATURE] - inline widgets in List Item Component #2608

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/test/super_editor/mobile/super_editor_ios_selection_test.dart
[SuperEditor][iOS] Fix selecting all document when using the native toolbar (Resolves #2579).
When using the iOS native toolbar, "select all" only selects the paragraph with the caret:
https://github.com/user-attachments/assets/02e1344a-9038-4cf4-8ce2-6a1cbcc07fe8
This happens because we only send to the IME the text of the currently selected nodes. So the IME "thinks" that this is the entire text.
Ideally, Flutter should report an action for us to handle that, but I'm not sure if this is possible.
To workaround this, whenever we receive a non-text delta selecting an entire node, on iOS, we select then entire document instead:
https://github.com/user-attachments/assets/230786d5-b756-4aa2-8cf8-7444c4fbe5ba
=> [SuperEditor][iOS] Fix selecting all document when using the native toolbar (Resolves #2579)

super_editor_spellcheck/lib/src/super_editor/spelling_error_suggestion_overlay.dart
[SuperEditor][iOS] Update spellcheck popover suggestions dimensions (Resolves #2577)
It was reported that the buttons in the spell check suggestions popover don't have the same dimensions that the native toolbar has.
I measured the dimensions from Apple Notes, and it seems the only thing we need is to increase the horizontal padding and the font size:
Apple Notes:
SuperEditor (currently):
SuperEditor (This PR):
=> [SuperEditor][iOS] Update spellcheck popover suggestions dimensions (Resolves #2577)

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/test/super_editor/components/list_items_test.dart, super_editor/test/super_editor/components/task_test.dart
[SuperEditor][Android][Web] Fix ENTER not correctly splitting list items and tasks (Resolves #2600)
On Android, pressing ENTER on a list item or task does not correctly splits the list item:
https://github.com/user-attachments/assets/2c9137a4-3c04-4f50-a31e-b1bd770ad5c2
On Android native, pressing ENTER generates only a new line insertion delta. Because of that, when receive a new line insertion, we call `onPerformAction` to notify that the `TextInputAction.newline` happened.
The issue is that, on Android Web, pressing ENTER generates both an `onPerformAction` call and a new line insertion delta. So we end up with `onPerformAction` being called twice. This causes a new list item to be inserted and being immediately converted to a paragraph.
This PR modifies the IME code to avoid calling …
=> [SuperEditor][Android][Web] Fix ENTER not correctly splitting list items and tasks (Resolves #2600)

super_editor/lib/src/infrastructure/attributed_text_styles.dart, super_editor/lib/src/super_textfield/android/android_textfield.dart, super_editor/lib/src/super_textfield/ios/ios_textfield.dart, super_editor/test/super_editor/supereditor_inline_widgets_test.dart, super_editor/test/super_textfield/super_textfield_inline_widgets_test.dart
[SuperEditor][SuperTextField] Fix text layout invalidating when selection changes (Resolves #2611)
In `SuperTextField` in iOS and Android, when there are placeholders present, double tapping causes the textfield to crash with the following exception:
```console
The following _TypeError was thrown building MultiListenableBuilder(dirty, state: _MultiListenableBuilderState#19999):
Null check operator used on a null value
When the exception was thrown, this was the stack: 
#0      SuperTextState.textLayout (package:super_text_layout/src/super_text.dart:70:89)
#1      _IOSEditingControlsState._textLayout (package:super_editor/src/super_textfield/ios/editing_controls.dart:148:74)
#2      _IOSEditingControlsState._buildDraggableOverlayHandles …
```
=> [SuperEditor][SuperTextField] Fix text layout invalidating when selection changes (Resolves #2611)

super_editor_quill/lib/src/serializing/serializers.dart, super_editor_quill/test/serializing_test.dart
[Quill][Bug] - Fix exception when serializing empty document (Resolves #2635)
=> [Quill][Bug] - Fix exception when serializing empty document (Resolves #2635)

super_editor_spellcheck/example/android/settings.gradle, super_editor_spellcheck/example/pubspec.lock, super_editor_spellcheck/lib/src/super_editor/spelling_and_grammar_plugin.dart
[Spellcheck][Android] - Fix empty paragraph platform error, and concurrent spell check platform error (Resolves #2640)
Problem 1: Android throws error when running spell check with an empty string (and Flutter doesn't guard against it).
Problem 2: Android throws error when trying to running 2+ spell checks concurrently.
Unrelated: This PR updates the Gradle version (or something related to it) because I couldn't build and deploy without doing that.
=> [Spellcheck][Android] - Fix empty paragraph platform error, and concurrent spell check platform error (Resolves #2640)

super_editor/lib/src/infrastructure/attributed_text_styles.dart, super_editor/test/infrastructure/inline_span_test.dart
[SuperEditor] Fix text duplicated when a placeholder is inserted in a text with attributions (Resolves #2595)
When inserting a placeholder after an attributed region, the editor duplicates the text:
https://github.com/user-attachments/assets/2a66b975-5a8a-4f00-b454-16adfe7595eb
The node's text itself isn't duplicated, the issue lives in the `InlineSpan` computation:
https://github.com/superlistapp/super_editor/blob/068aeb0114ca6ac5307217c26ae04906f65d9400/super_editor/lib/src/infrastructure/attributed_text_styles.dart#L64-L81
When there is a placeholder, we are assuming that the placeholder belongs in the current text span, which isn't always the case when there are attributions before the placeholder.
This PR fixes the issue by checking if the placeholder isn't part of a subsequent span. …
=> [SuperEditor] Fix text duplicated when a placeholder is inserted in a text with attributions (Resolves #2595)

super_keyboard/android/src/main/kotlin/com/flutterbountyhunters/superkeyboard/super_keyboard/SuperKeyboardPlugin.kt, super_keyboard/example/android/.gitignore, super_keyboard/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, super_keyboard/example/lib/main.dart, super_keyboard/example/pubspec.lock, super_keyboard/ios/Classes/SuperKeyboardPlugin.swift, super_keyboard/lib/src/keyboard.dart, super_keyboard/lib/src/super_keyboard_android.dart, super_keyboard/lib/src/super_keyboard_ios.dart, super_keyboard/lib/src/super_keyboard_unified.dart, super_keyboard/lib/test/keyboard_simulator.dart, super_keyboard/test/keyboard_simulation_test.dart
[SuperKeyboard] - Report all changes together, also add bottom insets (Resolves #2686)
This PR reports changes to the keyboard state and keyboard height at the same time in a new geometry data structure. This was done to prevent issues that might come from order of operations where the keyboard state change is reported and THEN the keyboard height change is reported, or vis-a-versa. 
This PR also adds reporting of bottom padding on Android as a way to work around a buggy lifecycle on Android.
The buggy lifecycle on Android was found to be caused by incorrect handling of permissions in a client app. However, that lifecycle issue also demonstrated that when it happens, Flutter loses synchronization with the bottom insets and bottom padding, reporting it incorrectly for the remainder of the …
=> [SuperKeyboard] - Report all changes together, also add bottom padding (Resolves #2686)

super_keyboard/lib/test/keyboard_simulator.dart
[SuperKeyboard] - Fix keyboard test simulator (Resolves #2692)
This PR respects the desired simulation keyboard height which was overriden with hard coded values in the previous release by accident.
=> [SuperKeyboard] - Fix keyboard test simulator (Resolves #2692)

super_editor/example/pubspec.yaml, super_editor/example_chat/lib/message_page_scaffold_demo/demo_super_editor_message_page.dart, super_editor/example_chat/pubspec.lock, super_editor/example_chat/pubspec.yaml, super_editor/lib/src/chat/message_page_scaffold.dart, super_editor/lib/src/infrastructure/keyboard_panel_scaffold.dart, super_editor/pubspec.yaml, super_keyboard/README.md
[SuperEditor][Chat] - Add option for KeyboardPanelScaffold to bypass MediaQuery (Resolves #2689)
Apps can now explicitly request that `KeyboardPanelScaffold` pull the keyboard height from `SuperKeyboard` instead of `MediaQuery`. See the original issue for an explanation why.
=> [SuperEditor][Chat] - Add option for KeyboardPanelScaffold to bypass MediaQuery (Resolves #2689)

super_clones/slack/lib/chat_thread.dart, super_clones/slack/lib/domain/message.dart, super_clones/slack/lib/domain/user.dart, super_clones/slack/lib/fake_data/fake_messages.dart, super_clones/slack/lib/fake_data/fake_users.dart, super_clones/slack/lib/main.dart, super_clones/slack/lib/mobile_message_editor.dart, super_clones/slack/lib/styles.dart, super_clones/slack/pubspec.yaml
[Clones] Add Slack clone.
This PR adds a clone of Slack's message page. The implementation is based on the `example_chat` project, which uses the newly introduced `MessagePageScaffold` widget.
Each message tile uses a separate `SuperReader` to render the message. The message editor uses a `SuperEditor`.
The dimensions don't match perfectly Slack's dimensions and, at the moment, we have only the mobile UI.
[slack.webm](https://github.com/user-attachments/assets/3bef62f3-0fd8-4a30-b40d-c217c8d09a17)
=> [Clones] Add Slack clone

super_editor_spellcheck/example/lib/main_super_editor_spellcheck.dart, super_editor_spellcheck/lib/src/super_editor/spelling_and_grammar_plugin.dart, super_editor_spellcheck/test/spellcheck_ignore_rules_test.dart
[Spellcheck] - Ignore entire text blocks, add configurable delay after edit before running spellcheck (Resolves #2651)
=> [Spellcheck] - Ignore entire text blocks, add configurable delay after edit before running spellcheck (Resolves #2651)

doc/website/source/super-editor/guides/_data.yaml, doc/website/source/super-editor/guides/styling/text-underlines.md, super_editor/example/lib/demos/in_the_lab/feature_custom_underlines.dart, super_editor/example/lib/main.dart, super_editor/lib/src/core/styles.dart, super_editor/lib/src/default_editor/attributions.dart, super_editor/lib/src/default_editor/blockquote.dart, super_editor/lib/src/default_editor/document_layers/attributed_text_bounds_overlay.dart, super_editor/lib/src/default_editor/list_items.dart, super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/super_editor.dart, super_editor/lib/src/default_editor/tasks.dart, super_editor/lib/src/default_editor/text.dart, super_editor/lib/src/default_editor/text/custom_underlines.dart, super_editor/lib/src/infrastructure/attribution_layout_bounds.dart, super_editor/lib/src/super_reader/super_reader.dart, super_editor/lib/super_editor.dart, super_editor/pubspec.yaml, super_text_layout/lib/src/text_underline_layer.dart
[SuperEditor][SuperReader] - Custom underline style configuration (Resolves #2675)
Text can now be attributed for a custom underline, and that custom underline is painted by `SuperEditor` and `SuperReader`.
The first step is to attribute some text with a `CustomUnderlineAttribution`. This attribution includes a `type` which is a `String` that can be anything. The `type` is interpreted by the style system, so as long as the `type` maps to an underline style, it will be honored. An unknown type will paint a straight black underline.
Each `TextComponentViewModel` has the stylesheet applied to it in `applyStyles()`. Each text view model now looks for a collection of underline styles: `customUnderlineStyles = styles[Styles.customUnderlineStyles];`. Each `TextComponentViewModel` holds on to …
=> [SuperEditor][SuperReader] - Custom underline style configuration (Resolves #2675)

super_editor_markdown/lib/src/markdown_to_document_parsing.dart, super_editor_markdown/test/super_editor_markdown_test.dart
[super_editor_markdown] Fix deserialization of a list item followed by a task (Resolves #2714)
Consider the following markdown, where we have a list item followed by a task:
```
- list item node 
```
This markdown produces a document with two list item nodes. 
The issue is that the list item parser consumes all contiguous items in a single call to `parse`. Since the list item syntax matches the task pattern, it considers the task as a list item.
I noticed that the markdown version that we use already supports tasks with the `UnorderedListWithCheckboxSyntax` (which just signals the base list item parser to handle tasks). With this syntax, we can correctly parse task items following list items.
I chose this approach because the other option is to copy the entire list item parser to modify …
=> [super_editor_markdown] Fix deserialization of a list item followed by a task (Resolves #2714)

super_editor/example/pubspec.yaml, super_editor/pubspec.yaml
[All][Fix] - Lock follow_the_leader and overlord to specific version numbers to prevent automatic upgrades
=> [All][Fix] - Lock follow_the_leader and overlord to specific version numbers to prevent automatic upgrades

super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart, super_editor/lib/src/default_editor/multi_node_editing.dart, super_editor/lib/src/default_editor/text.dart
[Super Editor] - Delete selected content when user enters text with IME (Resolves #2747)
Root cause was that `InsertPlainTextAtCaretCommand` would immediately bail out if the `start` node for text insertion wasn't a text node. This was being triggered in the case that the user drags up from text over an image and then tries to insert a character.
I change the command to delete whatever the selection is. After deleting the selection, if we're still not in a text node, we insert a text node.
I tried writing a test for this but no matter what I tried I wasn't able to get the IME simulation to work. Something within the test structure always broke. So I gave up. I tested this manually in the Mac desktop app.
=> [Super Editor] - Delete selected content when user enters text with IME (Resolves #2747)

super_editor/lib/src/infrastructure/serialization/html/document_to_html.dart, super_editor/lib/src/infrastructure/serialization/html/html_blockquotes.dart, super_editor/lib/src/infrastructure/serialization/html/html_code.dart, super_editor/lib/src/infrastructure/serialization/html/html_headers.dart, super_editor/lib/src/infrastructure/serialization/html/html_horizontal_rules.dart, super_editor/lib/src/infrastructure/serialization/html/html_images.dart, super_editor/lib/src/infrastructure/serialization/html/html_inline_text_styles.dart, super_editor/lib/src/infrastructure/serialization/html/html_list_items.dart, super_editor/lib/src/infrastructure/serialization/html/html_paragraphs.dart, super_editor/lib/src/infrastructure/serialization/plain_text/document_to_plain_text.dart, super_editor/lib/super_editor.dart, super_editor/test/infrastructure/serialization/html/document_to_html_test.dart, super_editor_clipboard/.gitignore, super_editor_clipboard/.metadata, super_editor_clipboard/CHANGELOG.md, super_editor_clipboard/LICENSE, super_editor_clipboard/README.md, super_editor_clipboard/analysis_options.yaml, super_editor_clipboard/lib/src/document_copy.dart, super_editor_clipboard/lib/src/super_editor_copy.dart, super_editor_clipboard/lib/src/super_reader_copy.dart, super_editor_clipboard/lib/super_editor_clipboard.dart, super_editor_clipboard/pubspec.yaml
This PR adds support to copy rich text from a `Document`.
To tell the system clipboard about the rich text, we use `super_clipboard`, which is a package that knows how to talk to the OS clipboard via Rust. To avoid adding a dependency on a Rust/binary package for all `super_editor` users, the use of `super_clipboard` is done in a new package called `super_editor_clipboard`, which is introduced in this PR.
Even with `super_clipboard`, it's still the responsibility of `super_editor` to report its document content in a way that interoperates with other apps. A very common interchange format is HTML. Therefore, this PR adds HTML serialization behavior for `Document`s. The rich text copy behavior in the `super_editor_clipboard` package uses the new HTML serialization from the `super_editor` …
=> [SuperEditor][SuperEditorClipboard] - Add support for rich text copying

super_editor/lib/super_editor.dart
[SuperReader] Export ReadOnlyTaskComponentBuilder. (Resolves #2659)
We added a `ReadOnlyTaskComponentBuilder`, but forgot to export it. This PR exports the file.
=> [SuperReader] Export ReadOnlyTaskComponentBuilder. (Resolves #2659)

super_editor/lib/src/default_editor/paragraph.dart, super_editor/lib/src/default_editor/text.dart, super_editor/test/super_editor/components/hint_text_test.dart, super_editor/test/super_editor/supereditor_components_test.dart
[SuperEditor] - Fix: Use inline widget builders in hint component (Resolves #2783)
Also, delete the hint component builder that we defined within the test directory because we publish a hint component builder now.
=> [SuperEditor] - Fix: Use inline widget builders in hint component (Resolves #2783)

attributed_text/lib/src/attributed_text.dart, attributed_text/test/attributed_text_placeholders_test.dart
[AttributedText] - Make constructor agnostic to placeholder order in placeholder map (Resolves #2786)
Before this PR, if someone passes in an inline placeholder map into `AttributedText`, and the entries in that map aren't in the same order as the placeholder text positions, the constructor will blow up. This PR sorts them in the constructor to avoid that issue.
=> [AttributedText] - Make constructor agnostic to placeholder order in placeholder map (Resolves #2786)

super_editor/lib/src/default_editor/super_editor.dart, super_editor/test/super_editor/supereditor_plugin_test.dart
[SuperEditor] Detach plugins in dispose(). (Resolves #2790)
Currently, `SuperEditor` only detaches its plugins on `didUpdateWidget`. It should be also detaching on `dispose`, to give the opportunity for plugins to dispose their own dependencies when the editor is removed from the widget tree.
This PR changes `SuperEditor` to call `detach` on each plugin on `dispose`.
=> [SuperEditor] Detach plugins in dispose(). (Resolves #2790)
